import { TRPCError } from "@trpc/server";
import { and, asc, desc, eq, gte, inArray, lte, sql } from "drizzle-orm";
import { z } from "zod";
import { auditLogs, balanceLedgerEntries, branchAlerts, branchJurisdictions, branchUsers, branches, cashierShifts, creditRequests, customerProfiles, decisionLogs, goodsReceiptLines, goodsReceipts, inventoryBatches, organizationMemberships, products, purchaseOrderLines, purchaseOrders, reportTemplates, sales, suppliers } from "../../drizzle/schema";
import { getDb } from "../db";
import { protectedProcedure, router } from "../_core/trpc";
import { hashAuditRecord } from "../domain/internal-auth";

const scopeSchema = z.object({ organizationId: z.number().int().positive(), branchId: z.number().int().positive(), jurisdictionId: z.number().int().positive().nullable().optional() });
const purchaseOrderScopeSchema = scopeSchema.extend({ jurisdictionId: z.number().int().positive() });
const managementRoles = ["owner", "org_admin", "operations_manager"] as const;
type Db = NonNullable<Awaited<ReturnType<typeof getDb>>>;

async function assertScope(db: Db, userId: number, role: string, scope: z.infer<typeof scopeSchema>) {
  const branch = (await db.select({ id: branches.id }).from(branches).where(and(eq(branches.id, scope.branchId), eq(branches.organizationId, scope.organizationId), eq(branches.active, 1))).limit(1))[0];
  if (!branch) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "الفرع غير نشط أو خارج المؤسسة المحددة" });
  if (role !== "admin") {
    const member = (await db.select({ id: branchUsers.id }).from(branchUsers).where(and(eq(branchUsers.branchId, scope.branchId), eq(branchUsers.userId, userId), eq(branchUsers.active, 1))).limit(1))[0];
    if (!member) throw new TRPCError({ code: "FORBIDDEN", message: "لا يملك المستخدم نطاق الفرع المحدد" });
  }
  if (scope.jurisdictionId != null) {
    const assignment = (await db.select({ id: branchJurisdictions.id }).from(branchJurisdictions).where(and(eq(branchJurisdictions.branchId, scope.branchId), eq(branchJurisdictions.jurisdictionId, scope.jurisdictionId))).limit(1))[0];
    if (!assignment) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "الاختصاص غير مرتبط بالفرع المحدد" });
  }
}

async function assertManagement(db: Db, userId: number, role: string, organizationId: number) {
  if (role === "admin") return;
  const membership = (await db.select({ id: organizationMemberships.id }).from(organizationMemberships).where(and(eq(organizationMemberships.organizationId, organizationId), eq(organizationMemberships.userId, userId), eq(organizationMemberships.active, 1), sql`${organizationMemberships.organizationRole} in ('owner', 'org_admin', 'operations_manager')`)).limit(1))[0];
  if (!membership) throw new TRPCError({ code: "FORBIDDEN", message: "تتطلب هذه العملية اعتمادًا إداريًا" });
}

async function audit(db: Db, userId: number, scope: z.infer<typeof scopeSchema>, action: string, entityType: string, entityId: number) {
  const previous = (await db.select({ recordHash: auditLogs.recordHash }).from(auditLogs).where(and(eq(auditLogs.organizationId, scope.organizationId), eq(auditLogs.branchId, scope.branchId))).orderBy(desc(auditLogs.id)).limit(1))[0]?.recordHash ?? null;
  const createdAt = new Date().toISOString();
  const event = { eventType: action, userId, organizationId: scope.organizationId, branchId: scope.branchId, jurisdictionId: scope.jurisdictionId ?? null, requestId: `${entityType}:${entityId}`, createdAt };
  await db.insert(auditLogs).values({ userId, organizationId: scope.organizationId, branchId: scope.branchId, action, entityType, entityId: String(entityId), previousHash: previous, recordHash: hashAuditRecord(event) });
}

const lineSchema = z.object({ productId: z.number().int().positive(), orderedQuantity: z.coerce.number().positive().finite(), unitCost: z.coerce.number().nonnegative().finite(), batchNumber: z.string().trim().max(80).optional(), expiryDate: z.coerce.date().optional() });
const reportQuerySchema = scopeSchema.extend({ search: z.string().trim().max(120).optional(), status: z.enum(["all", "draft", "submitted", "approved", "partially_received", "received", "cancelled"]).default("all"), fromDate: z.coerce.date().optional(), toDate: z.coerce.date().optional(), sortKey: z.enum(["date", "amount", "status"]).default("date"), sortDirection: z.enum(["asc", "desc"]).default("desc"), limit: z.number().int().min(1).max(500).default(200) });
function reportOrder(input: z.infer<typeof reportQuerySchema>) { const column = input.sortKey === "amount" ? purchaseOrders.totalAmount : input.sortKey === "status" ? purchaseOrders.status : purchaseOrders.createdAt; return input.sortDirection === "asc" ? asc(column) : desc(column); }

export const procurementRouter = router({
  reports: router({
    purchases: protectedProcedure.input(reportQuerySchema.extend({ jurisdictionId: z.number().int().positive() })).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); await assertManagement(db, ctx.user.id, ctx.user.role, input.organizationId); const conditions = [eq(purchaseOrders.organizationId, input.organizationId), eq(purchaseOrders.branchId, input.branchId), eq(purchaseOrders.jurisdictionId, input.jurisdictionId)]; if (input.status !== "all") conditions.push(eq(purchaseOrders.status, input.status)); if (input.fromDate) conditions.push(gte(purchaseOrders.createdAt, input.fromDate)); if (input.toDate) conditions.push(lte(purchaseOrders.createdAt, input.toDate)); if (input.search) conditions.push(sql`(${purchaseOrders.orderNumber} like ${`%${input.search}%`} or ${purchaseOrders.currencyCode} like ${`%${input.search}%`})`); return db.select().from(purchaseOrders).where(and(...conditions)).orderBy(reportOrder(input)).limit(input.limit); }),
    balances: protectedProcedure.input(reportQuerySchema).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); await assertManagement(db, ctx.user.id, ctx.user.role, input.organizationId); const entries = await db.select().from(balanceLedgerEntries).where(and(eq(balanceLedgerEntries.organizationId, input.organizationId), eq(balanceLedgerEntries.branchId, input.branchId), eq(balanceLedgerEntries.approvalStatus, "approved"))).orderBy(desc(balanceLedgerEntries.createdAt)).limit(1000); const supplierBalances = new Map<number, number>(); const customerBalances = new Map<number, number>(); for (const entry of entries) { const delta = entry.direction === "debit" ? Number(entry.amount) : -Number(entry.amount); const map = entry.partyType === "supplier" ? supplierBalances : customerBalances; const id = entry.partyType === "supplier" ? entry.supplierId : entry.customerId; if (id) map.set(id, (map.get(id) ?? 0) + delta); } const rows = [...Array.from(supplierBalances.entries()).map(([partyId, balance]) => ({ partyId, balance, partyType: "supplier" as const })), ...Array.from(customerBalances.entries()).map(([partyId, balance]) => ({ partyId, balance, partyType: "customer" as const }))]; const query = input.search?.toLowerCase(); const filtered = query ? rows.filter(row => `${row.partyId} ${row.partyType}`.includes(query)) : rows; const sorted = [...filtered].sort((a, b) => { const left = input.sortKey === "status" ? a.partyType : a.balance; const right = input.sortKey === "status" ? b.partyType : b.balance; const result = left < right ? -1 : left > right ? 1 : 0; return input.sortDirection === "asc" ? result : -result; }); return sorted.slice(0, input.limit); }),
  }),
  templates: router({
    get: protectedProcedure.input(scopeSchema.extend({ reportKey: z.enum(["purchases", "balances"]) })).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); const template = (await db.select().from(reportTemplates).where(and(eq(reportTemplates.organizationId, input.organizationId), eq(reportTemplates.branchId, input.branchId), eq(reportTemplates.jurisdictionId, input.jurisdictionId ?? -1), eq(reportTemplates.reportKey, input.reportKey), eq(reportTemplates.active, 1))).limit(1))[0]; return template ?? null; }),
    upsert: protectedProcedure.input(scopeSchema.extend({ reportKey: z.enum(["purchases", "balances"]), name: z.string().trim().min(2).max(180), title: z.string().trim().min(2).max(180), subtitle: z.string().trim().max(240).optional(), columns: z.array(z.string().trim().min(1).max(80)).min(1).max(12), footer: z.string().trim().max(300).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); await assertManagement(db, ctx.user.id, ctx.user.role, input.organizationId); const existing = (await db.select({ id: reportTemplates.id }).from(reportTemplates).where(and(eq(reportTemplates.organizationId, input.organizationId), eq(reportTemplates.branchId, input.branchId), eq(reportTemplates.jurisdictionId, input.jurisdictionId ?? -1), eq(reportTemplates.reportKey, input.reportKey))).limit(1))[0]; if (existing) { await db.update(reportTemplates).set({ name: input.name, title: input.title, subtitle: input.subtitle, columnsJson: JSON.stringify(input.columns), footer: input.footer, active: 1, updatedByUserId: ctx.user.id }).where(eq(reportTemplates.id, existing.id)); await audit(db, ctx.user.id, input, "report_template_updated", "report_template", existing.id); return { templateId: existing.id, updated: true as const }; } const inserted = await db.insert(reportTemplates).values({ organizationId: input.organizationId, branchId: input.branchId, jurisdictionId: input.jurisdictionId ?? -1, reportKey: input.reportKey, name: input.name, title: input.title, subtitle: input.subtitle, columnsJson: JSON.stringify(input.columns), footer: input.footer, active: 1, updatedByUserId: ctx.user.id }); const id = Number(inserted[0].insertId); await audit(db, ctx.user.id, input, "report_template_created", "report_template", id); return { templateId: id, updated: false as const }; }),
  }),
  suppliers: router({
    list: protectedProcedure.input(scopeSchema.extend({ search: z.string().trim().max(120).optional(), status: z.enum(["active", "inactive", "all"]).default("active"), limit: z.number().int().min(1).max(500).default(200) })).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); const conditions = [eq(suppliers.organizationId, input.organizationId), eq(suppliers.branchId, input.branchId)]; if (input.status !== "all") conditions.push(eq(suppliers.active, input.status === "active" ? 1 : 0)); if (input.search) { const term = `%${input.search}%`; conditions.push(sql`(${suppliers.name} like ${term} or ${suppliers.supplierCode} like ${term} or ${suppliers.contactPerson} like ${term} or ${suppliers.phone} like ${term} or ${suppliers.taxRegistrationNumber} like ${term})`); } return db.select().from(suppliers).where(and(...conditions)).orderBy(suppliers.name).limit(input.limit); }),
    get: protectedProcedure.input(scopeSchema.extend({ supplierId: z.number().int().positive() })).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); const supplier = (await db.select().from(suppliers).where(and(eq(suppliers.id, input.supplierId), eq(suppliers.organizationId, input.organizationId), eq(suppliers.branchId, input.branchId))).limit(1))[0]; if (!supplier) throw new TRPCError({ code: "NOT_FOUND", message: "المورد خارج نطاق المؤسسة أو الفرع" }); return supplier; }),
    create: protectedProcedure.input(scopeSchema.extend({ name: z.string().trim().min(2).max(240), supplierCode: z.string().trim().max(80).optional(), contactPerson: z.string().trim().max(180).optional(), phone: z.string().trim().max(40).optional(), email: z.string().trim().email().max(240).optional(), address: z.string().trim().max(500).optional(), city: z.string().trim().max(120).optional(), countryCode: z.string().trim().length(2).toUpperCase().default("EG"), taxRegistrationNumber: z.string().trim().max(80).optional(), paymentTermsDays: z.number().int().min(0).max(365).default(0), notes: z.string().trim().max(2000).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); await assertManagement(db, ctx.user.id, ctx.user.role, input.organizationId); if (input.supplierCode) { const duplicate = (await db.select({ id: suppliers.id }).from(suppliers).where(and(eq(suppliers.organizationId, input.organizationId), eq(suppliers.branchId, input.branchId), eq(suppliers.supplierCode, input.supplierCode))).limit(1))[0]; if (duplicate) throw new TRPCError({ code: "CONFLICT", message: "كود المورد مستخدم بالفعل ضمن النطاق" }); } const result = await db.insert(suppliers).values({ organizationId: input.organizationId, branchId: input.branchId, jurisdictionId: input.jurisdictionId, name: input.name, supplierCode: input.supplierCode, contactPerson: input.contactPerson, phone: input.phone, email: input.email, address: input.address, city: input.city, countryCode: input.countryCode, taxRegistrationNumber: input.taxRegistrationNumber, paymentTermsDays: input.paymentTermsDays, notes: input.notes, createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await audit(db, ctx.user.id, input, "supplier_created", "supplier", id); return { supplierId: id }; }),
    update: protectedProcedure.input(scopeSchema.extend({ supplierId: z.number().int().positive(), name: z.string().trim().min(2).max(240), supplierCode: z.string().trim().max(80).optional(), contactPerson: z.string().trim().max(180).optional(), phone: z.string().trim().max(40).optional(), email: z.string().trim().email().max(240).optional(), address: z.string().trim().max(500).optional(), city: z.string().trim().max(120).optional(), countryCode: z.string().trim().length(2).toUpperCase(), taxRegistrationNumber: z.string().trim().max(80).optional(), paymentTermsDays: z.number().int().min(0).max(365), notes: z.string().trim().max(2000).optional(), active: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); await assertManagement(db, ctx.user.id, ctx.user.role, input.organizationId); const existing = (await db.select({ id: suppliers.id }).from(suppliers).where(and(eq(suppliers.id, input.supplierId), eq(suppliers.organizationId, input.organizationId), eq(suppliers.branchId, input.branchId))).limit(1))[0]; if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "المورد خارج نطاق المؤسسة أو الفرع" }); const duplicate = input.supplierCode ? (await db.select({ id: suppliers.id }).from(suppliers).where(and(eq(suppliers.organizationId, input.organizationId), eq(suppliers.branchId, input.branchId), eq(suppliers.supplierCode, input.supplierCode), sql`${suppliers.id} <> ${input.supplierId}`)).limit(1))[0] : null; if (duplicate) throw new TRPCError({ code: "CONFLICT", message: "كود المورد مستخدم بالفعل ضمن النطاق" }); await db.update(suppliers).set({ name: input.name, supplierCode: input.supplierCode, contactPerson: input.contactPerson, phone: input.phone, email: input.email, address: input.address, city: input.city, countryCode: input.countryCode, taxRegistrationNumber: input.taxRegistrationNumber, paymentTermsDays: input.paymentTermsDays, notes: input.notes, active: input.active ? 1 : 0 }).where(eq(suppliers.id, input.supplierId)); await audit(db, ctx.user.id, input, "supplier_updated", "supplier", input.supplierId); return { supplierId: input.supplierId, active: input.active }; }),
    requestCredit: protectedProcedure.input(scopeSchema.extend({ supplierId: z.number().int().positive(), requestedLimit: z.number().finite().nonnegative().max(100000000), currencyCode: z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/).default("EGP") })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); await assertManagement(db, ctx.user.id, ctx.user.role, input.organizationId); const supplier = (await db.select({ id: suppliers.id }).from(suppliers).where(and(eq(suppliers.id, input.supplierId), eq(suppliers.organizationId, input.organizationId), eq(suppliers.branchId, input.branchId))).limit(1))[0]; if (!supplier) throw new TRPCError({ code: "NOT_FOUND", message: "المورد خارج نطاق المؤسسة أو الفرع" }); await db.update(suppliers).set({ creditLimit: input.requestedLimit.toFixed(2), creditCurrencyCode: input.currencyCode, creditApprovalStatus: "pending", creditApprovedByUserId: null, creditApprovedAt: null }).where(eq(suppliers.id, input.supplierId)); await audit(db, ctx.user.id, input, "supplier_credit_requested", "supplier", input.supplierId); return { supplierId: input.supplierId, status: "pending" as const }; }),
    decideCredit: protectedProcedure.input(z.object({ supplierId: z.number().int().positive(), decision: z.enum(["approved", "rejected"]), note: z.string().trim().max(500).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); const supplier = (await db.select().from(suppliers).where(eq(suppliers.id, input.supplierId)).limit(1))[0]; if (!supplier) throw new TRPCError({ code: "NOT_FOUND", message: "المورد غير موجود" }); const scope = { organizationId: supplier.organizationId, branchId: supplier.branchId ?? 0, jurisdictionId: supplier.jurisdictionId }; await assertScope(db, ctx.user.id, ctx.user.role, scope); await assertManagement(db, ctx.user.id, ctx.user.role, supplier.organizationId); if (supplier.creditApprovalStatus !== "pending") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "لا يوجد طلب ائتمان معلق لهذا المورد" }); await db.update(suppliers).set({ creditApprovalStatus: input.decision, creditApprovedByUserId: ctx.user.id, creditApprovedAt: new Date(), notes: input.note ? input.note : supplier.notes }).where(eq(suppliers.id, supplier.id)); await audit(db, ctx.user.id, scope, `supplier_credit_${input.decision}`, "supplier", supplier.id); return { supplierId: supplier.id, status: input.decision }; }),
  }),
  purchaseOrders: router({
    list: protectedProcedure.input(purchaseOrderScopeSchema).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); await assertManagement(db, ctx.user.id, ctx.user.role, input.organizationId); return db.select().from(purchaseOrders).where(and(eq(purchaseOrders.organizationId, input.organizationId), eq(purchaseOrders.branchId, input.branchId), eq(purchaseOrders.jurisdictionId, input.jurisdictionId))).orderBy(desc(purchaseOrders.createdAt)).limit(100); }),
    create: protectedProcedure.input(purchaseOrderScopeSchema.extend({ orderNumber: z.string().trim().min(3).max(80), supplierId: z.number().int().positive(), currencyCode: z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/).default("EGP"), lines: z.array(lineSchema).min(1).max(500) })).mutation(async ({ ctx, input }) => {
      const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input);
      const supplier = (await db.select({ id: suppliers.id }).from(suppliers).where(and(eq(suppliers.id, input.supplierId), eq(suppliers.organizationId, input.organizationId), eq(suppliers.branchId, input.branchId), eq(suppliers.jurisdictionId, input.jurisdictionId), eq(suppliers.active, 1))).limit(1))[0]; if (!supplier) throw new TRPCError({ code: "NOT_FOUND", message: "المورد خارج نطاق المؤسسة أو الفرع أو الاختصاص، أو غير نشط" });
      const duplicate = (await db.select({ id: purchaseOrders.id }).from(purchaseOrders).where(and(eq(purchaseOrders.organizationId, input.organizationId), eq(purchaseOrders.branchId, input.branchId), eq(purchaseOrders.orderNumber, input.orderNumber.toUpperCase()))).limit(1))[0]; if (duplicate) throw new TRPCError({ code: "CONFLICT", message: "رقم أمر الشراء مستخدم بالفعل ضمن النطاق" });
      const total = input.lines.reduce((sum, line) => sum + line.orderedQuantity * line.unitCost, 0);
      const orderId = await db.transaction(async tx => { const orderResult = await tx.insert(purchaseOrders).values({ organizationId: input.organizationId, branchId: input.branchId, jurisdictionId: input.jurisdictionId, supplierId: input.supplierId, orderNumber: input.orderNumber.toUpperCase(), currencyCode: input.currencyCode, totalAmount: total.toFixed(2), createdByUserId: ctx.user.id }); const id = Number(orderResult[0].insertId); await tx.insert(purchaseOrderLines).values(input.lines.map(line => ({ purchaseOrderId: id, productId: line.productId, orderedQuantity: line.orderedQuantity.toFixed(3), unitCost: line.unitCost.toFixed(2), batchNumber: line.batchNumber, expiryDate: line.expiryDate }))); return id; });
      await audit(db, ctx.user.id, input, "purchase_order_created", "purchase_order", orderId); return { purchaseOrderId: orderId, status: "draft" as const, totalAmount: total };
    }),
    transition: protectedProcedure.input(z.object({ purchaseOrderId: z.number().int().positive(), nextStatus: z.enum(["submitted", "approved", "cancelled"]), reason: z.string().trim().min(1).max(1000).optional() })).mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });
      const order = (await db.select().from(purchaseOrders).where(eq(purchaseOrders.id, input.purchaseOrderId)).limit(1))[0];
      if (!order) throw new TRPCError({ code: "NOT_FOUND", message: "أمر الشراء غير موجود" });
      const scope = { organizationId: order.organizationId, branchId: order.branchId, jurisdictionId: order.jurisdictionId };
      await assertScope(db, ctx.user.id, ctx.user.role, scope);
      const allowed: Record<string, string[]> = { draft: ["submitted", "cancelled"], submitted: ["approved", "cancelled"], approved: ["cancelled"] };
      if (!allowed[order.status]?.includes(input.nextStatus)) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "انتقال حالة أمر الشراء غير مسموح" });
      const isReviewDecision = order.status === "submitted" && (input.nextStatus === "approved" || input.nextStatus === "cancelled");
      if (isReviewDecision) {
        await assertManagement(db, ctx.user.id, ctx.user.role, order.organizationId);
        if (!input.reason) throw new TRPCError({ code: "BAD_REQUEST", message: "سبب قرار الاعتماد أو الرفض مطلوب" });
        if (order.jurisdictionId == null) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "يلزم اختصاص قانوني مكتمل قبل تسجيل قرار المراجعة" });
      }
      const decidedAt = new Date();
      await db.transaction(async tx => {
        await tx.update(purchaseOrders).set({ status: input.nextStatus, approvedByUserId: input.nextStatus === "approved" ? ctx.user.id : order.approvedByUserId, approvedAt: input.nextStatus === "approved" ? decidedAt : order.approvedAt }).where(eq(purchaseOrders.id, order.id));
        if (!isReviewDecision) return;
        const decisionResult = await tx.insert(decisionLogs).values({ organizationId: order.organizationId, branchId: order.branchId, jurisdictionId: order.jurisdictionId!, entityType: "purchase_order", entityId: order.id, decision: input.nextStatus === "approved" ? "approved" : "rejected", reason: input.reason!, decidedByUserId: ctx.user.id, decidedAt });
        const decisionId = Number(decisionResult[0].insertId);
        const previous = (await tx.select({ recordHash: auditLogs.recordHash }).from(auditLogs).where(and(eq(auditLogs.organizationId, order.organizationId), eq(auditLogs.branchId, order.branchId))).orderBy(desc(auditLogs.id)).limit(1))[0]?.recordHash ?? null;
        const createdAt = decidedAt.toISOString();
        await tx.insert(auditLogs).values({ userId: ctx.user.id, organizationId: order.organizationId, branchId: order.branchId, action: `purchase_order_${input.nextStatus}_decision_recorded`, entityType: "decision_log", entityId: String(decisionId), previousHash: previous, recordHash: hashAuditRecord({ eventType: `purchase_order_${input.nextStatus}_decision_recorded`, userId: ctx.user.id, organizationId: order.organizationId, branchId: order.branchId, jurisdictionId: order.jurisdictionId ?? null, requestId: `decision_log:${decisionId}`, createdAt }) });
      });
      if (!isReviewDecision) await audit(db, ctx.user.id, scope, `purchase_order_${input.nextStatus}`, "purchase_order", order.id);
      return { purchaseOrderId: order.id, status: input.nextStatus, decisionRecorded: isReviewDecision };
    }),
  }),
  receiving: router({
    post: protectedProcedure.input(scopeSchema.extend({ purchaseOrderId: z.number().int().positive(), receiptNumber: z.string().trim().min(3).max(80), idempotencyKey: z.string().trim().min(12).max(180), lines: z.array(z.object({ purchaseOrderLineId: z.number().int().positive(), productId: z.number().int().positive(), batchNumber: z.string().trim().min(1).max(80), expiryDate: z.coerce.date(), quantity: z.coerce.number().positive().finite(), unitCost: z.coerce.number().nonnegative().finite() })).min(1).max(500) })).mutation(async ({ ctx, input }) => {
      const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); const existing = (await db.select({ id: goodsReceipts.id, status: goodsReceipts.status }).from(goodsReceipts).where(and(eq(goodsReceipts.organizationId, input.organizationId), eq(goodsReceipts.branchId, input.branchId), eq(goodsReceipts.idempotencyKey, input.idempotencyKey))).limit(1))[0]; if (existing) return { goodsReceiptId: existing.id, status: existing.status, idempotentReplay: true } as const;
      const order = (await db.select().from(purchaseOrders).where(and(eq(purchaseOrders.id, input.purchaseOrderId), eq(purchaseOrders.organizationId, input.organizationId), eq(purchaseOrders.branchId, input.branchId))).limit(1))[0]; if (!order || !["approved", "partially_received"].includes(order.status)) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "لا يمكن استلام أمر غير معتمد" });
      const orderLines = await db.select().from(purchaseOrderLines).where(eq(purchaseOrderLines.purchaseOrderId, order.id)); const byId = new Map(orderLines.map(line => [line.id, line])); for (const line of input.lines) { const poLine = byId.get(line.purchaseOrderLineId); if (!poLine || poLine.productId !== line.productId || Number(poLine.receivedQuantity) + line.quantity > Number(poLine.orderedQuantity) + 0.000001) throw new TRPCError({ code: "BAD_REQUEST", message: "كمية الاستلام تتجاوز الكمية المعتمدة أو أن السطر خارج أمر الشراء" }); }
      const receiptId = await db.transaction(async tx => { const result = await tx.insert(goodsReceipts).values({ organizationId: input.organizationId, branchId: input.branchId, jurisdictionId: input.jurisdictionId, purchaseOrderId: order.id, receiptNumber: input.receiptNumber.toUpperCase(), idempotencyKey: input.idempotencyKey, status: "posted", receivedByUserId: ctx.user.id, postedAt: new Date() }); const id = Number(result[0].insertId); await tx.insert(goodsReceiptLines).values(input.lines.map(line => ({ goodsReceiptId: id, purchaseOrderLineId: line.purchaseOrderLineId, productId: line.productId, batchNumber: line.batchNumber, expiryDate: line.expiryDate, quantity: line.quantity.toFixed(3), unitCost: line.unitCost.toFixed(2) }))); for (const line of input.lines) { const poLine = byId.get(line.purchaseOrderLineId)!; await tx.update(purchaseOrderLines).set({ receivedQuantity: (Number(poLine.receivedQuantity) + line.quantity).toFixed(3) }).where(eq(purchaseOrderLines.id, poLine.id)); const existingBatch = (await tx.select().from(inventoryBatches).where(and(eq(inventoryBatches.organizationId, input.organizationId), eq(inventoryBatches.branchId, input.branchId), eq(inventoryBatches.productId, line.productId), eq(inventoryBatches.batchNumber, line.batchNumber), eq(inventoryBatches.expiryDate, line.expiryDate))).limit(1))[0]; if (existingBatch) await tx.update(inventoryBatches).set({ quantityOnHand: (Number(existingBatch.quantityOnHand) + line.quantity).toFixed(3) }).where(eq(inventoryBatches.id, existingBatch.id)); else await tx.insert(inventoryBatches).values({ organizationId: input.organizationId, branchId: input.branchId, jurisdictionId: input.jurisdictionId, productId: line.productId, batchNumber: line.batchNumber, expiryDate: line.expiryDate, quantityOnHand: line.quantity.toFixed(3) }); } const nextStatus = orderLines.every(line => Number(line.receivedQuantity) + input.lines.filter(item => item.purchaseOrderLineId === line.id).reduce((sum, item) => sum + item.quantity, 0) >= Number(line.orderedQuantity) - 0.000001) ? "received" : "partially_received"; await tx.update(purchaseOrders).set({ status: nextStatus }).where(eq(purchaseOrders.id, order.id)); return id; });
      await audit(db, ctx.user.id, input, "goods_receipt_posted", "goods_receipt", receiptId); return { goodsReceiptId: receiptId, status: "posted" as const, idempotentReplay: false };
    }),
  }),
  balances: router({
    summary: protectedProcedure.input(scopeSchema).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); const entries = await db.select().from(balanceLedgerEntries).where(and(eq(balanceLedgerEntries.organizationId, input.organizationId), eq(balanceLedgerEntries.branchId, input.branchId), eq(balanceLedgerEntries.approvalStatus, "approved"))).orderBy(desc(balanceLedgerEntries.createdAt)).limit(500); const supplierBalances = new Map<number, number>(); const customerBalances = new Map<number, number>(); for (const entry of entries) { const delta = entry.direction === "debit" ? Number(entry.amount) : -Number(entry.amount); const map = entry.partyType === "supplier" ? supplierBalances : customerBalances; const id = entry.partyType === "supplier" ? entry.supplierId : entry.customerId; if (id) map.set(id, (map.get(id) ?? 0) + delta); } const credits = await db.select().from(creditRequests).where(and(eq(creditRequests.organizationId, input.organizationId), eq(creditRequests.branchId, input.branchId), inArray(creditRequests.status, ["pending", "approved"]))).orderBy(desc(creditRequests.createdAt)).limit(100); return { supplierBalances: Array.from(supplierBalances.entries()).map(([partyId, balance]) => ({ partyId, balance })), customerBalances: Array.from(customerBalances.entries()).map(([partyId, balance]) => ({ partyId, balance })), creditRequests: credits }; }),
    createEntry: protectedProcedure.input(scopeSchema.extend({ partyType: z.enum(["supplier", "customer"]), supplierId: z.number().int().positive().optional(), customerId: z.number().int().positive().optional(), direction: z.enum(["debit", "credit"]), amount: z.coerce.number().positive().finite(), sourceType: z.string().trim().min(2).max(80), sourceId: z.string().trim().min(1).max(80) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); if (input.partyType === "supplier" && !input.supplierId || input.partyType === "customer" && !input.customerId) throw new TRPCError({ code: "BAD_REQUEST", message: "يجب تحديد الطرف المطابق لنوع الرصيد" }); const existing = (await db.select({ id: balanceLedgerEntries.id }).from(balanceLedgerEntries).where(and(eq(balanceLedgerEntries.organizationId, input.organizationId), eq(balanceLedgerEntries.sourceType, input.sourceType), eq(balanceLedgerEntries.sourceId, input.sourceId))).limit(1))[0]; if (existing) throw new TRPCError({ code: "CONFLICT", message: "قيد الرصيد موجود بالفعل" }); const result = await db.insert(balanceLedgerEntries).values({ organizationId: input.organizationId, branchId: input.branchId, jurisdictionId: input.jurisdictionId, partyType: input.partyType, supplierId: input.supplierId, customerId: input.customerId, direction: input.direction, amount: input.amount.toFixed(2), sourceType: input.sourceType, sourceId: input.sourceId, approvalStatus: "pending", createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await audit(db, ctx.user.id, input, "balance_entry_created", "balance_ledger_entry", id); return { entryId: id, approvalStatus: "pending" as const }; }),
    approveEntry: protectedProcedure.input(z.object({ entryId: z.number().int().positive(), decision: z.enum(["approved", "rejected"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); const entry = (await db.select().from(balanceLedgerEntries).where(eq(balanceLedgerEntries.id, input.entryId)).limit(1))[0]; if (!entry) throw new TRPCError({ code: "NOT_FOUND", message: "قيد الرصيد غير موجود" }); await assertScope(db, ctx.user.id, ctx.user.role, { organizationId: entry.organizationId, branchId: entry.branchId ?? 0, jurisdictionId: entry.jurisdictionId }); await assertManagement(db, ctx.user.id, ctx.user.role, entry.organizationId); if (entry.approvalStatus !== "pending") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "القيد تمت مراجعته سابقًا" }); await db.update(balanceLedgerEntries).set({ approvalStatus: input.decision, approvedByUserId: ctx.user.id }).where(eq(balanceLedgerEntries.id, entry.id)); await audit(db, ctx.user.id, { organizationId: entry.organizationId, branchId: entry.branchId ?? 1, jurisdictionId: entry.jurisdictionId }, `balance_entry_${input.decision}`, "balance_ledger_entry", entry.id); return { entryId: entry.id, approvalStatus: input.decision }; }),
    requestCredit: protectedProcedure.input(scopeSchema.extend({ customerId: z.number().int().positive(), requestedLimit: z.coerce.number().positive().finite() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); const customer = (await db.select({ id: customerProfiles.id }).from(customerProfiles).where(and(eq(customerProfiles.id, input.customerId), eq(customerProfiles.organizationId, input.organizationId))).limit(1))[0]; if (!customer) throw new TRPCError({ code: "NOT_FOUND", message: "العميل خارج نطاق المؤسسة" }); const result = await db.insert(creditRequests).values({ organizationId: input.organizationId, branchId: input.branchId, jurisdictionId: input.jurisdictionId, customerId: input.customerId, requestedLimit: input.requestedLimit.toFixed(2), outstandingAmount: "0.00", status: "pending", requestedByUserId: ctx.user.id }); const id = Number(result[0].insertId); await audit(db, ctx.user.id, input, "customer_credit_requested", "credit_request", id); return { creditRequestId: id, status: "pending" as const }; }),
    decideCredit: protectedProcedure.input(z.object({ creditRequestId: z.number().int().positive(), decision: z.enum(["approved", "rejected"]), note: z.string().trim().max(500).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); const request = (await db.select().from(creditRequests).where(eq(creditRequests.id, input.creditRequestId)).limit(1))[0]; if (!request) throw new TRPCError({ code: "NOT_FOUND", message: "طلب الائتمان غير موجود" }); await assertScope(db, ctx.user.id, ctx.user.role, { organizationId: request.organizationId, branchId: request.branchId ?? 0, jurisdictionId: request.jurisdictionId }); await assertManagement(db, ctx.user.id, ctx.user.role, request.organizationId); if (request.status !== "pending") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "طلب الائتمان تمت مراجعته سابقًا" }); await db.update(creditRequests).set({ status: input.decision, approvedByUserId: ctx.user.id, approvedAt: new Date() }).where(eq(creditRequests.id, request.id)); await audit(db, ctx.user.id, { organizationId: request.organizationId, branchId: request.branchId ?? 1, jurisdictionId: request.jurisdictionId }, `customer_credit_${input.decision}`, "credit_request", request.id); return { creditRequestId: request.id, status: input.decision }; }),
  }),
  dashboard: router({
    snapshot: protectedProcedure.input(scopeSchema).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertScope(db, ctx.user.id, ctx.user.role, input); const [salesCount, openShifts, pendingOrders, lowStock, outOfStock, pendingReceipts, branch] = await Promise.all([db.select({ count: sql<number>`count(*)` }).from(sales).where(and(eq(sales.organizationId, input.organizationId), eq(sales.branchId, input.branchId), eq(sales.saleStatus, "completed"))), db.select({ count: sql<number>`count(*)` }).from(cashierShifts).where(and(eq(cashierShifts.organizationId, input.organizationId), eq(cashierShifts.branchId, input.branchId), eq(cashierShifts.status, "open"))), db.select({ count: sql<number>`count(*)` }).from(purchaseOrders).where(and(eq(purchaseOrders.organizationId, input.organizationId), eq(purchaseOrders.branchId, input.branchId), inArray(purchaseOrders.status, ["submitted", "approved", "partially_received"]))), db.select({ count: sql<number>`count(*)` }).from(inventoryBatches).where(and(eq(inventoryBatches.organizationId, input.organizationId), eq(inventoryBatches.branchId, input.branchId), sql`${inventoryBatches.quantityOnHand} > 0 and ${inventoryBatches.quantityOnHand} <= ${inventoryBatches.reorderPoint}`)), db.select({ count: sql<number>`count(*)` }).from(inventoryBatches).where(and(eq(inventoryBatches.organizationId, input.organizationId), eq(inventoryBatches.branchId, input.branchId), eq(inventoryBatches.quantityOnHand, "0"))), db.select({ count: sql<number>`count(*)` }).from(goodsReceipts).where(and(eq(goodsReceipts.organizationId, input.organizationId), eq(goodsReceipts.branchId, input.branchId), eq(goodsReceipts.status, "draft"))), db.select({ name: branches.nameAr }).from(branches).where(eq(branches.id, input.branchId)).limit(1)]); return { scope: input, branchLabel: branch[0]?.name ?? `فرع ${input.branchId}`, salesTotal: Number(salesCount[0]?.count ?? 0), openShiftCount: Number(openShifts[0]?.count ?? 0), pendingOrders: Number(pendingOrders[0]?.count ?? 0), stockLowCount: Number(lowStock[0]?.count ?? 0), stockOutCount: Number(outOfStock[0]?.count ?? 0), pendingReceipts: Number(pendingReceipts[0]?.count ?? 0) }; }),
  }),
});
