import { useMemo, useState } from "react";
import { ArchiveRestore, CheckCircle2, Clock3, Database, HardDriveDownload, Loader2, Plus, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { useLocalization } from "@/contexts/LocalizationContext";
import { trpc } from "@/lib/trpc";

type Props = { organizationId: number | null; branchId: number | null };

export default function BackupManagementWorkspace({ organizationId, branchId }: Props) {
  const { language, direction } = useLocalization();
  const isEnglish = language === "en";
  const copy = isEnglish ? {
    selectScope: "Choose an organization and branch first to manage backups inside a protected scope.", dataProtection: "Data protection", policies: "Policies", lastVerification: "Latest verification", verified: "Verified", noResult: "No result yet", onlineOffline: "Online + Offline", protectionDetail: "External storage with a verifiable reference and integrity record; file contents are never stored in the database.", policyDetail: "A separate frequency can be set for each organization or branch scope.", verificationDetail: "Every run records its checksum, record count, and outcome.", newPolicy: "New backup policy", recommended: "Recommended plan", recommendedDetail: "Create a daily Online policy, then a weekly Offline policy. Offline export never moves files to physical media automatically; an authorized person must download and store it on separate encrypted media.", configureOnline: "Configure daily Online", configureOffline: "Configure weekly Offline", policyName: "Policy name", cron: "Cron frequency — UTC (6 fields)", cronDetail: "Seconds, minutes, hour, day, month, day of week. Example: daily at 02:00 UTC.", destination: "Destination", onlineStorage: "Online — organizational storage", offlineExport: "Offline — controlled export", createSchedule: "Create & schedule", policiesAndManualRun: "Policies & manual run", retention: "Retention", days: "days", encryption: "Encryption", runNow: "Run now", noPolicies: "No policy exists yet. Start with a daily Online policy, then add a periodic Offline export under the organizational retention policy.", runLog: "Run log & verification", running: "Running", failed: "Failed", records: "records", downloadOffline: "Download temporary Offline export", openDownload: "Open temporary verified download link", noRuns: "The run log and checksum will appear after the first backup.", created: "Backup policy created and connected to the automated schedule.", createFailed: "The policy could not be created. Check the scope and six-field Cron expression.", completed: "Backup completed and its SHA-256 checksum was verified.", exportFailed: "The temporary Offline export link could not be prepared. Confirm that the backup is verified and that the export policy is in your scope.", dailyName: "MEDORA daily backup — Online", weeklyName: "MEDORA weekly export — Offline", dailyPreset: "Daily at 02:00 UTC; encrypted reference with a verifiable SHA-256 checksum.", weeklyPreset: "Saturday at 03:00 UTC; a controlled export that an authorized person must download to separate encrypted media.", online: "Online", offline: "Offline export",
  } : {
    selectScope: "اختر المؤسسة والفرع أولاً لإدارة النسخ ضمن نطاق آمن.", dataProtection: "حماية البيانات", policies: "السياسات", lastVerification: "آخر تحقق", verified: "موثّق", noResult: "لا توجد نتيجة", onlineOffline: "Online + Offline", protectionDetail: "تخزين خارجي بمرجع ونزاهة قابلة للتحقق، دون وضع محتوى الملفات داخل قاعدة البيانات.", policyDetail: "تردد مستقل لكل نطاق مؤسسة أو فرع.", verificationDetail: "كل تشغيل يسجل البصمة وعدد السجلات وحالة التنفيذ.", newPolicy: "سياسة نسخ جديدة", recommended: "الخطة الموصى بها", recommendedDetail: "أنشئ سياسة Online يومية ثم سياسة Offline أسبوعية. التصدير Offline لا ينقل الملفات تلقائيًا إلى وسيط مادي؛ يجب على مسؤول مفوض تنزيله وتخزينه على وسيط منفصل ومشفّر.", configureOnline: "إعداد Online اليومي", configureOffline: "إعداد Offline الأسبوعي", policyName: "اسم السياسة", cron: "تردد Cron — UTC (6 حقول)", cronDetail: "الثواني، الدقائق، الساعة، اليوم، الشهر، يوم الأسبوع. مثال: يوميًا 02:00 UTC.", destination: "الوجهة", onlineStorage: "Online — تخزين مؤسسي", offlineExport: "Offline — تصدير محكوم", createSchedule: "إنشاء وربط الجدولة", policiesAndManualRun: "السياسات والتشغيل اليدوي", retention: "احتفاظ", days: "يومًا", encryption: "تشفير", runNow: "تشغيل الآن", noPolicies: "لم تُنشأ سياسة بعد. ابدأ بسياسة يومية Online، ثم أضف تصدير Offline دوريًا وفق سياسة الاحتفاظ المؤسسية.", runLog: "سجل التشغيل والتحقق", running: "قيد التشغيل", failed: "فشل", records: "سجلًا", downloadOffline: "تنزيل تصدير Offline مؤقت", openDownload: "فتح رابط التنزيل المؤقت بعد التحقق", noRuns: "سيظهر هنا سجل التشغيل والبصمة بعد أول نسخة.", created: "تم إنشاء سياسة النسخ وربطها بالجدولة الآلية.", createFailed: "تعذر إنشاء السياسة. تحقق من النطاق وصيغة Cron ذات الحقول الستة.", completed: "اكتمل النسخ والتحقق من بصمة SHA-256.", exportFailed: "تعذر تجهيز رابط التصدير Offline. تأكد من أن النسخة متحققة وسياسة التصدير ضمن نطاقك.", dailyName: "نسخ MEDORA اليومي — Online", weeklyName: "تصدير MEDORA الأسبوعي — Offline", dailyPreset: "يوميًا 02:00 UTC؛ مرجع مشفّر وبصمة SHA-256 قابلة للتحقق.", weeklyPreset: "السبت 03:00 UTC؛ تصدير محكوم يجب أن ينزله المسؤول إلى وسيط منفصل ومشفّر.", online: "Online", offline: "Offline export",
  };
  const presets = useMemo(() => ({ online: { name: copy.dailyName, cronExpression: "0 0 2 * * *", retentionDays: 30, description: copy.dailyPreset }, offline_export: { name: copy.weeklyName, cronExpression: "0 0 3 * * 6", retentionDays: 90, description: copy.weeklyPreset } }), [copy]);
  const scope = organizationId ? { organizationId, branchId } : undefined;
  const utils = trpc.useUtils();
  const policies = trpc.backup.listPolicies.useQuery(scope!, { enabled: Boolean(scope), retry: false });
  const runs = trpc.backup.listRuns.useQuery(scope!, { enabled: Boolean(scope), retry: false });
  const [name, setName] = useState<string>(isEnglish ? "MEDORA daily backup — Online" : "نسخ MEDORA اليومي — Online");
  const [cronExpression, setCronExpression] = useState("0 0 2 * * *");
  const [destinationType, setDestinationType] = useState<"online" | "offline_export">("online");
  const [retentionDays, setRetentionDays] = useState(30);
  const [message, setMessage] = useState("");
  const createPolicy = trpc.backup.createPolicy.useMutation({ onSuccess: () => { setMessage(copy.created); void utils.backup.listPolicies.invalidate(); }, onError: () => setMessage(copy.createFailed) });
  const runNow = trpc.backup.runNow.useMutation({ onSuccess: () => { setMessage(copy.completed); void utils.backup.listRuns.invalidate(); } });
  const offlineExport = trpc.backup.requestOfflineExportUrl.useMutation({ onError: () => setMessage(copy.exportFailed) });
  const latestRuns = useMemo(() => (runs.data ?? []).slice(0, 8), [runs.data]);
  const statusLabel = (status: string) => status === "verified" ? copy.verified : status === "failed" ? copy.failed : copy.running;

  if (!organizationId) return <Card dir={direction}><CardContent className="p-6 text-sm text-slate-600">{copy.selectScope}</CardContent></Card>;
  return <div dir={direction} className="space-y-5">
    <div className="grid gap-4 md:grid-cols-3">
      <Card className="border-cyan-200 bg-cyan-50/60"><CardContent className="p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold text-cyan-700">{copy.dataProtection}</p><p className="mt-2 text-2xl font-bold text-cyan-950">{copy.onlineOffline}</p></div><ShieldCheck className="h-8 w-8 shrink-0 text-cyan-700" /></div><p className="mt-3 text-xs leading-5 text-cyan-900">{copy.protectionDetail}</p></CardContent></Card>
      <Card><CardContent className="p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold text-slate-500">{copy.policies}</p><p className="mt-2 text-2xl font-bold">{policies.data?.length ?? 0}</p></div><Clock3 className="h-8 w-8 shrink-0 text-slate-400" /></div><p className="mt-3 text-xs text-slate-500">{copy.policyDetail}</p></CardContent></Card>
      <Card><CardContent className="p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold text-slate-500">{copy.lastVerification}</p><p className="mt-2 text-lg font-bold">{latestRuns[0]?.status === "verified" ? copy.verified : copy.noResult}</p></div><CheckCircle2 className="h-8 w-8 shrink-0 text-emerald-600" /></div><p className="mt-3 text-xs text-slate-500">{copy.verificationDetail}</p></CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><ArchiveRestore className="h-5 w-5 text-cyan-700" />{copy.newPolicy}</CardTitle></CardHeader><CardContent className="space-y-4">
      <div className="rounded-xl border border-cyan-100 bg-cyan-50/60 p-3 text-xs leading-5 text-cyan-950"><p className="font-semibold">{copy.recommended}</p><p>{copy.recommendedDetail}</p></div>
      <div className="grid gap-3 md:grid-cols-2"><Button type="button" variant="outline" onClick={() => { const preset = presets.online; setDestinationType("online"); setName(preset.name); setCronExpression(preset.cronExpression); setRetentionDays(preset.retentionDays); setMessage(preset.description); }}>{copy.configureOnline}</Button><Button type="button" variant="outline" onClick={() => { const preset = presets.offline_export; setDestinationType("offline_export"); setName(preset.name); setCronExpression(preset.cronExpression); setRetentionDays(preset.retentionDays); setMessage(preset.description); }}>{copy.configureOffline}</Button></div>
      <div className="grid gap-4 md:grid-cols-4"><div className="space-y-2"><Label>{copy.policyName}</Label><Input value={name} onChange={event => setName(event.target.value)} /></div><div className="space-y-2"><Label>{copy.cron}</Label><Input value={cronExpression} onChange={event => setCronExpression(event.target.value)} dir="ltr" placeholder="0 0 2 * * *" /><p className="text-[11px] text-slate-500">{copy.cronDetail}</p></div><div className="space-y-2"><Label>{copy.destination}</Label><Select value={destinationType} onValueChange={value => setDestinationType(value as typeof destinationType)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="online">{copy.onlineStorage}</SelectItem><SelectItem value="offline_export">{copy.offlineExport}</SelectItem></SelectContent></Select></div><div className="flex items-end"><Button className="w-full bg-cyan-700 hover:bg-cyan-800" disabled={createPolicy.isPending || !name.trim()} onClick={() => createPolicy.mutate({ organizationId, branchId, name, destinationType, cronExpression, retentionDays, encryptionMode: "platform_managed" })}>{createPolicy.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}{copy.createSchedule}</Button></div></div>
    </CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Database className="h-5 w-5 text-slate-600" />{copy.policiesAndManualRun}</CardTitle></CardHeader><CardContent className="space-y-3">{(policies.data ?? []).map(policy => <div key={policy.id} className="flex flex-col gap-3 rounded-xl border border-slate-200 p-4 md:flex-row md:items-center md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-semibold">{policy.name}</span><Badge variant="outline">{policy.destinationType === "online" ? copy.online : copy.offline}</Badge><Badge variant="secondary">{policy.cronExpression}</Badge></div><p className="mt-1 text-xs text-slate-500">{copy.retention} {policy.retentionDays} {copy.days} · {copy.encryption} {policy.encryptionMode}</p></div><Button variant="outline" disabled={runNow.isPending} onClick={() => runNow.mutate({ policyId: policy.id, idempotencyKey: `${policy.id}-${Date.now()}` })}>{runNow.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <HardDriveDownload className="h-4 w-4" />}{copy.runNow}</Button></div>)}{!policies.data?.length && <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">{copy.noPolicies}</p>}{message && <p className="text-sm font-medium text-emerald-700">{message}</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>{copy.runLog}</CardTitle></CardHeader><CardContent className="space-y-2">{latestRuns.map(run => { const canExportOffline = run.status === "verified" && policies.data?.some(policy => policy.id === run.policyId && policy.destinationType === "offline_export"); return <div key={run.id} className="rounded-lg bg-slate-50 p-3 text-sm"><div className="flex flex-col gap-1 md:flex-row md:items-center md:justify-between"><div><span className="font-medium">{statusLabel(run.status)}</span><span className="mx-2 text-xs text-slate-500">{run.recordCount ?? 0} {copy.records}</span></div><code dir="ltr" className="text-[11px] text-slate-500">{run.manifestSha256?.slice(0, 20) ?? "—"}</code></div>{canExportOffline ? <div className="mt-2 flex flex-wrap items-center gap-2"><Button size="sm" variant="outline" disabled={offlineExport.isPending} onClick={() => offlineExport.mutate({ runId: run.id })}>{copy.downloadOffline}</Button>{offlineExport.data && offlineExport.variables?.runId === run.id ? <a className="text-xs font-medium text-cyan-800 underline-offset-4 hover:underline" href={offlineExport.data.url} target="_blank" rel="noreferrer">{copy.openDownload}</a> : null}</div> : null}</div>; })}{!latestRuns.length && <p className="text-sm text-slate-500">{copy.noRuns}</p>}</CardContent></Card>
  </div>;
}
