import { useMemo, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { GovernmentIntegrationReadinessPacket } from "@/components/GovernmentIntegrationReadinessPacket";
import { useLocalization } from "@/contexts/LocalizationContext";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Bell, CheckCircle2, Check, Clock3, Filter, Info, LockKeyhole, Search, ShieldCheck } from "lucide-react";

const stateLabels = {
  blocked: { ar: "مغلق بأمان", en: "Fail-closed", className: "border-slate-300 bg-slate-100 text-slate-700" },
  deferred: { ar: "مؤجل", en: "Deferred", className: "border-amber-300 bg-amber-50 text-amber-900" },
  ready: { ar: "جاهز للمراجعة", en: "Ready for review", className: "border-emerald-300 bg-emerald-50 text-emerald-800" },
} as const;

function SelectField({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) {
  return <label className="space-y-1 text-sm text-slate-700"><span className="block text-xs font-semibold text-slate-500">{label}</span><select value={value} onChange={event => onChange(event.target.value)} className="h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm shadow-sm outline-none focus:border-cyan-500 focus:ring-2 focus:ring-cyan-100">{children}</select></label>;
}

export function ConnectorAccreditationDashboard() {
  const [countryCode, setCountryCode] = useState("ALL");
  const [provider, setProvider] = useState("ALL");
  const [connectorType, setConnectorType] = useState("ALL");
  const [readinessState, setReadinessState] = useState("ALL");
  const [acknowledgedAlerts, setAcknowledgedAlerts] = useState<string[]>([]);
  const { language, direction } = useLocalization();
  const isArabic = language === "ar";
  const text = isArabic ? {
    loading: "جارٍ تحميل مركز الموصلات…", loadError: "تعذر تحميل اللوحة. لم يتم تغيير أي اعتماد أو محاولة اتصال خارجي.", title: "مركز الموصلات والاعتمادات", description: "تصفية ومتابعة الجاهزية التنظيمية والتأمينية. اللوحة للقراءة والتدقيق فقط ولا تفعّل أي إرسال خارجي.", failClosed: "سياسة fail-closed", failClosedHelp: "لا يتغير الموصل إلى نشط إلا بعد المواصفة الرسمية والاعتماد وبيئة الاختبار والقبول الموثق. لا تعرض اللوحة أسراراً.", filters: "فلاتر متقدمة", country: "الدولة", allCountries: "كل الدول", provider: "الجهة المزودة", allProviders: "كل الجهات", connectorType: "نوع الموصل", allTypes: "كل الأنواع", government: "حكومي وتنظيمي", payer: "تأميني / جهة دافعة", readiness: "مرحلة الجاهزية", allStages: "كل المراحل", shown: "عرض", of: "من", connectors: "موصلات", clearFilters: "مسح الفلاتر", alerts: "تنبيهات الاعتمادات وحالة الموصلات", alertsDescription: "تنبيهات داخلية للمسؤولين فقط. لا يتم إرسال أي بيانات إلى جهات خارجية.", unread: "غير مقروء", noAlerts: "لا توجد تنبيهات حالية ضمن الفلاتر.", critical: "عاجل", warning: "تنبيه", info: "معلومة", connector: "الموصل", reopen: "إعادة فتح", reviewed: "تمت المراجعة", reopenAria: "إعادة فتح التنبيه", reviewAria: "تمييز التنبيه كمقروء", englishState: "الحالة الإنجليزية", noExternal: "لا يوجد تفعيل خارجي في هذه المرحلة.", readinessPercent: "نسبة الجاهزية الداخلية", remaining: "المتطلبات المتبقية", auditTitle: "سجل تدقيق تغييرات الموصلات", auditDescription: "سجل محمي ومختصر يعرض مراجعات الحالة والتغييرات المصرح بها فقط؛ لا يتم تسجيل كلمات مرور أو مفاتيح أو رموز.", noAudit: "لا توجد سجلات مطابقة للفلاتر الحالية.", actor: "الفاعل", systemAdmin: "مسؤول النظام", scope: "النطاق", signedLog: "سجل موقّع", signedLogHelp: "سلسلة السجل موقعة بمفتاح التدقيق الخادمي، ولا يظهر المفتاح في الواجهة.", reviewedAt: "آخر مراجعة", activationPolicy: "سياسة التفعيل",
  } : {
    loading: "Loading the connector centre…", loadError: "The dashboard could not be loaded. No accreditation was changed and no external connection was attempted.", title: "Connectors and accreditation centre", description: "Filter and review regulatory and payer readiness. This dashboard is read-only and does not activate external transmission.", failClosed: "Fail-closed policy", failClosedHelp: "A connector cannot become active until its official specification, accreditation, test environment, and documented acceptance are complete. This dashboard never exposes secrets.", filters: "Advanced filters", country: "Country", allCountries: "All countries", provider: "Provider", allProviders: "All providers", connectorType: "Connector type", allTypes: "All types", government: "Government and regulatory", payer: "Insurance / payer", readiness: "Readiness stage", allStages: "All stages", shown: "Showing", of: "of", connectors: "connectors", clearFilters: "Clear filters", alerts: "Accreditation and connector alerts", alertsDescription: "Internal alerts for authorized administrators only. No data is sent to external parties.", unread: "unread", noAlerts: "There are no alerts within the selected filters.", critical: "Critical", warning: "Warning", info: "Information", connector: "Connector", reopen: "Reopen", reviewed: "Reviewed", reopenAria: "Reopen alert", reviewAria: "Mark alert as reviewed", englishState: "English state", noExternal: "No external activation is available at this stage.", readinessPercent: "Internal readiness", remaining: "Outstanding requirements", auditTitle: "Connector change audit log", auditDescription: "A protected, concise log of status reviews and authorized changes only; no passwords, keys, or tokens are recorded.", noAudit: "There are no audit records for the selected filters.", actor: "Actor", systemAdmin: "System administrator", scope: "Scope", signedLog: "Signed audit log", signedLogHelp: "The audit chain is signed with the server audit key; the key is never exposed in this interface.", reviewedAt: "Last reviewed", activationPolicy: "Activation policy",
  };
  const input = useMemo(() => ({ countryCode: countryCode as "ALL" | "EG", provider, connectorType: connectorType as "ALL" | "government-regulatory" | "insurance-payer", readinessState: readinessState as "ALL" | "blocked" | "deferred" | "ready" }), [countryCode, provider, connectorType, readinessState]);
  const readiness = trpc.auth.connectorReadiness.useQuery(input, { retry: false });
  if (readiness.isLoading) return <Card className="border-slate-200 bg-white/80" dir={direction}><CardContent className="flex items-center gap-3 p-6 text-sm text-slate-600"><Clock3 className="h-5 w-5 animate-pulse text-cyan-700" aria-hidden="true" />{text.loading}</CardContent></Card>;
  if (readiness.isError || !readiness.data) return <Card className="border-rose-200 bg-rose-50" dir={direction}><CardContent className="flex items-start gap-3 p-6 text-sm leading-6 text-rose-900" role="alert"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0" aria-hidden="true" /><span>{text.loadError}</span></CardContent></Card>;
  const { data } = readiness;
  const blockedCount = data.connectors.filter(item => item.state === "blocked").length;
  const unreadAlertCount = data.alerts.filter(alert => !acknowledgedAlerts.includes(alert.id)).length;
  const reviewedAt = new Date(data.reviewedAt).toLocaleString(isArabic ? "ar-EG" : "en-GB");
  const alertStyles = { critical: "border-rose-200 bg-rose-50 text-rose-950", warning: "border-amber-200 bg-amber-50 text-amber-950", info: "border-cyan-200 bg-cyan-50 text-cyan-950" } as const;
  const alertLabels = { critical: text.critical, warning: text.warning, info: text.info } as const;
  const reset = () => { setCountryCode("ALL"); setProvider("ALL"); setConnectorType("ALL"); setReadinessState("ALL"); };
  const localState = (state: keyof typeof stateLabels) => stateLabels[state][isArabic ? "ar" : "en"];

  return <section className="space-y-4" aria-labelledby="connector-dashboard-title" dir={direction}>
    <Card className="border-cyan-100 bg-gradient-to-br from-white to-cyan-50/50 shadow-sm"><CardHeader className="pb-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle id="connector-dashboard-title" className="flex items-center gap-2 text-xl text-slate-900"><ShieldCheck className="h-5 w-5 text-cyan-700" aria-hidden="true" />{text.title}</CardTitle><p className="mt-2 text-sm leading-6 text-slate-600">{text.description}</p></div><Tooltip><TooltipTrigger asChild><Badge variant="outline" className="cursor-help border-slate-300 bg-white text-slate-700"><LockKeyhole className="me-1 h-3.5 w-3.5" aria-hidden="true" />{text.failClosed}</Badge></TooltipTrigger><TooltipContent className="max-w-sm text-start leading-5">{text.failClosedHelp}</TooltipContent></Tooltip></div></CardHeader><CardContent className="space-y-4"><div className="flex items-center gap-2 text-sm font-semibold text-slate-800"><Filter className="h-4 w-4 text-cyan-700" aria-hidden="true" />{text.filters}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><SelectField label={text.country} value={countryCode} onChange={setCountryCode}><option value="ALL">{text.allCountries}</option><option value="EG">{isArabic ? "مصر (EG)" : "Egypt (EG)"}</option></SelectField><SelectField label={text.provider} value={provider} onChange={setProvider}><option value="ALL">{text.allProviders}</option>{data.filterOptions.providers.map(item => <option key={item} value={item}>{item}</option>)}</SelectField><SelectField label={text.connectorType} value={connectorType} onChange={setConnectorType}><option value="ALL">{text.allTypes}</option><option value="government-regulatory">{text.government}</option><option value="insurance-payer">{text.payer}</option></SelectField><SelectField label={text.readiness} value={readinessState} onChange={setReadinessState}><option value="ALL">{text.allStages}</option>{Object.keys(stateLabels).map(state => <option key={state} value={state}>{localState(state as keyof typeof stateLabels)}</option>)}</SelectField></div><div className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-white/80 p-3 text-xs text-slate-600"><span className="flex items-center gap-2"><Search className="h-4 w-4 text-cyan-700" aria-hidden="true" />{text.shown} {data.connectors.length} {text.of} {data.filterOptions.total} {text.connectors} · {blockedCount} {localState("blocked")}</span><Button type="button" variant="outline" size="sm" onClick={reset}>{text.clearFilters}</Button></div></CardContent></Card>
    <GovernmentIntegrationReadinessPacket />
    <Card className="border-amber-100 bg-gradient-to-br from-white to-amber-50/60 shadow-sm" aria-labelledby="connector-alerts-title"><CardHeader className="pb-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle id="connector-alerts-title" className="flex items-center gap-2 text-base text-slate-900"><Bell className="h-5 w-5 text-amber-700" aria-hidden="true" />{text.alerts}</CardTitle><p className="mt-1 text-xs leading-5 text-slate-600">{text.alertsDescription}</p></div><Badge variant="outline" className="border-amber-200 bg-white text-amber-900" aria-live="polite">{unreadAlertCount} {text.unread}</Badge></div></CardHeader><CardContent className="space-y-3" aria-live="polite">{data.alerts.length === 0 ? <p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-600">{text.noAlerts}</p> : data.alerts.map(alert => { const acknowledged = acknowledgedAlerts.includes(alert.id); return <article key={alert.id} className={`rounded-xl border p-3 ${alertStyles[alert.severity]} ${acknowledged ? "opacity-60" : ""}`}><div className="flex items-start justify-between gap-3"><div className="flex items-start gap-2"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" /><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold">{alert.title}</h3><Badge variant="outline" className="border-current/20 bg-white/60 text-[10px]">{alertLabels[alert.severity]}</Badge></div><p className="mt-1 text-xs leading-5">{alert.detail}</p><p className="mt-1 text-[11px] opacity-75">{text.connector}: {alert.connectorId} · {new Date(alert.occurredAt).toLocaleString(isArabic ? "ar-EG" : "en-GB")}</p></div></div><Button type="button" size="sm" variant="outline" className="shrink-0 border-current/20 bg-white/70 text-xs" onClick={() => setAcknowledgedAlerts(current => acknowledged ? current.filter(id => id !== alert.id) : [...current, alert.id])} aria-label={acknowledged ? text.reopenAria : text.reviewAria}>{acknowledged ? <Bell className="me-1 h-3.5 w-3.5" aria-hidden="true" /> : <Check className="me-1 h-3.5 w-3.5" aria-hidden="true" />}{acknowledged ? text.reopen : text.reviewed}</Button></div></article>; })}</CardContent></Card>
    <div className="grid gap-4 xl:grid-cols-2">{data.connectors.map(connector => { const state = stateLabels[connector.state]; return <Card key={connector.id} className="border-slate-200 bg-white shadow-sm"><CardHeader className="pb-3"><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-base text-slate-900">{connector.name}</CardTitle><p className="mt-1 text-xs text-slate-500">{connector.countryCode} · {connector.connectorType} · {connector.providers.join(" · ")}</p></div><Tooltip><TooltipTrigger asChild><Badge variant="outline" className={`cursor-help ${state.className}`}><LockKeyhole className="me-1 h-3.5 w-3.5" aria-hidden="true" />{localState(connector.state)}</Badge></TooltipTrigger><TooltipContent className="max-w-xs text-start leading-5">{text.englishState}: {state.en}. {text.noExternal}</TooltipContent></Tooltip></div></CardHeader><CardContent className="space-y-4"><div><div className="mb-1 flex justify-between text-xs text-slate-500"><span>{text.readinessPercent}</span><span>{connector.readinessPercent}%</span></div><Progress value={connector.readinessPercent} aria-label={`${text.readinessPercent} ${connector.name}`} /></div><div><p className="mb-2 text-sm font-semibold text-slate-800">{text.remaining}</p><ul className="space-y-2 text-sm leading-5 text-slate-600">{connector.prerequisites.map(item => <li key={item} className="flex items-start gap-2"><Info className="mt-0.5 h-4 w-4 shrink-0 text-cyan-700" aria-hidden="true" /><span>{item}</span></li>)}</ul></div><div className="flex items-start gap-2 rounded-lg bg-slate-50 p-3 text-xs leading-5 text-slate-600"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-slate-500" aria-hidden="true" />{connector.note}</div></CardContent></Card>; })}</div>
    <Card className="border-slate-200 bg-white shadow-sm"><CardHeader><CardTitle className="text-base text-slate-900">{text.auditTitle}</CardTitle><p className="text-xs leading-5 text-slate-500">{text.auditDescription}</p></CardHeader><CardContent className="space-y-2">{data.auditLog.length === 0 ? <p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-600">{text.noAudit}</p> : data.auditLog.map(entry => <div key={`${entry.connectorId}-${entry.recordHash}`} className="grid gap-2 rounded-lg border border-slate-100 bg-slate-50/70 p-3 text-xs text-slate-600 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="font-semibold text-slate-800">{entry.connectorId} · {localState(entry.newState)} · {entry.reason}</p><p className="mt-1">{text.actor}: {text.systemAdmin} · {text.country}: {entry.countryCode} · {text.scope}: {entry.connectorType}</p></div><Tooltip><TooltipTrigger asChild><span className="flex cursor-help items-center gap-1 text-emerald-700"><ShieldCheck className="h-4 w-4" aria-hidden="true" />{text.signedLog}</span></TooltipTrigger><TooltipContent>{text.signedLogHelp}</TooltipContent></Tooltip></div>)}</CardContent></Card>
    <p className="text-xs text-slate-500">{text.reviewedAt}: {reviewedAt} · {text.activationPolicy}: fail-closed</p>
  </section>;
}
