import { and, desc, eq, sql } from "drizzle-orm";
import { z } from "zod";
import { canTransitionCrmOpportunity, canTransitionCustomerCase } from "../domain/secondary-modules-policy";
import {
  auditLogs,
  branches,
  callTickets,
  customerProfiles,
  careInteractions,
  purchaseOrders,
  sales,
  branchUsers,
  branchJurisdictions,
  callInteractions,
  callQueueMembers,
  callQueues,
  crmActivities,
  crmContacts,
  crmLeads,
  crmOpportunities,
  customerCareCases,
  customerCareSatisfaction,
  customerCareTasks,
  employeeProfiles,
  hrContracts,
  hrPerformanceReviews,
  hrShifts,
  organizationMemberships,
} from "../../drizzle/schema";
import { getDb } from "../db";
import { hashAuditRecord } from "../domain/internal-auth";
import { protectedProcedure, router } from "../_core/trpc";
import { TRPCError } from "@trpc/server";
import { invokeLLM } from "../_core/llm";

type Database = NonNullable<Awaited<ReturnType<typeof getDb>>>;
const scope = z.object({ organizationId: z.number().int().positive(), branchId: z.number().int().positive().nullable().optional(), jurisdictionId: z.number().int().nonnegative().nullable().optional() });
const hasScopeValue = (value: number | null | undefined): value is number => value !== null && value !== undefined;
const managementRoles = ["owner", "org_admin", "operations_manager"] as const;

async function assertOrg(db: Database, userId: number, systemRole: string, organizationId: number) {
  if (systemRole === "admin") return;
  const rows = await db.select({ id: organizationMemberships.id }).from(organizationMemberships).where(and(eq(organizationMemberships.organizationId, organizationId), eq(organizationMemberships.userId, userId), eq(organizationMemberships.active, 1))).limit(1);
  if (!rows.length) throw new TRPCError({ code: "FORBIDDEN", message: "Organization is outside the active scope" });
}

async function assertBranch(db: Database, userId: number, systemRole: string, organizationId: number, branchId: number) {
  const branch = await db.select({ id: branches.id }).from(branches).where(and(eq(branches.id, branchId), eq(branches.organizationId, organizationId), eq(branches.active, 1))).limit(1);
  if (!branch.length) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Branch is not active for this organization" });
  if (systemRole !== "admin") {
    const membership = await db.select({ id: branchUsers.id }).from(branchUsers).where(and(eq(branchUsers.branchId, branchId), eq(branchUsers.userId, userId), eq(branchUsers.active, 1))).limit(1);
    if (!membership.length) throw new TRPCError({ code: "FORBIDDEN", message: "Branch is outside the active scope" });
  }
}

async function assertManager(db: Database, userId: number, systemRole: string, organizationId: number) {
  await assertOrg(db, userId, systemRole, organizationId);
  if (systemRole === "admin") return;
  const rows = await db.select({ organizationRole: organizationMemberships.organizationRole }).from(organizationMemberships).where(and(eq(organizationMemberships.organizationId, organizationId), eq(organizationMemberships.userId, userId), eq(organizationMemberships.active, 1))).limit(1);
  const organizationRole = rows[0]?.organizationRole;
  if (!organizationRole || !(managementRoles as readonly string[]).includes(organizationRole)) throw new TRPCError({ code: "FORBIDDEN", message: "Management access is required" });
}

async function audit(db: Database, input: { userId: number; organizationId: number; branchId?: number | null; action: string; entityType: string; entityId: number }) {
  const previous = await db.select({ recordHash: auditLogs.recordHash }).from(auditLogs).where(and(eq(auditLogs.organizationId, input.organizationId), input.branchId ? eq(auditLogs.branchId, input.branchId) : undefined)).orderBy(desc(auditLogs.id)).limit(1);
  const createdAt = new Date().toISOString();
  const recordHash = hashAuditRecord({ eventType: input.action, userId: input.userId, organizationId: input.organizationId, branchId: input.branchId ?? null, requestId: `${input.entityType}:${input.entityId}`, createdAt });
  await db.insert(auditLogs).values({ userId: input.userId, organizationId: input.organizationId, branchId: input.branchId ?? null, action: input.action, entityType: input.entityType, entityId: String(input.entityId), previousHash: previous[0]?.recordHash ?? null, recordHash });
}

async function validateScope(db: Database, ctx: { user: { id: number; role: string } }, input: { organizationId: number; branchId?: number | null; jurisdictionId?: number | null }) {
  await assertOrg(db, ctx.user.id, ctx.user.role, input.organizationId);
  if (hasScopeValue(input.branchId)) await assertBranch(db, ctx.user.id, ctx.user.role, input.organizationId, input.branchId);
  if (hasScopeValue(input.jurisdictionId)) {
    if (!hasScopeValue(input.branchId)) throw new TRPCError({ code: "BAD_REQUEST", message: "Branch is required when a jurisdiction scope is supplied" });
    const assigned = await db.select({ id: branchJurisdictions.id }).from(branchJurisdictions).where(and(eq(branchJurisdictions.branchId, input.branchId), eq(branchJurisdictions.jurisdictionId, input.jurisdictionId))).limit(1);
    if (!assigned.length) throw new TRPCError({ code: "FORBIDDEN", message: "Jurisdiction is outside the authorized branch scope" });
  }
}

async function assertScopedUser(db: Database, input: { organizationId: number; branchId?: number | null; userId?: number }) {
  if (!input.userId) return;
  const membership = await db.select({ id: organizationMemberships.id }).from(organizationMemberships).where(and(eq(organizationMemberships.organizationId, input.organizationId), eq(organizationMemberships.userId, input.userId), eq(organizationMemberships.active, 1))).limit(1);
  if (!membership.length) throw new TRPCError({ code: "FORBIDDEN", message: "Assigned user is outside the authorized organization" });
  if (input.branchId) {
    const branchMembership = await db.select({ id: branchUsers.id }).from(branchUsers).where(and(eq(branchUsers.branchId, input.branchId), eq(branchUsers.userId, input.userId), eq(branchUsers.active, 1))).limit(1);
    if (!branchMembership.length) throw new TRPCError({ code: "FORBIDDEN", message: "Assigned user is outside the authorized branch" });
  }
}

async function assertScopedCustomer(db: Database, input: { customerId: number; organizationId: number; branchId?: number | null }) {
  const customer = await db.select({ id: customerProfiles.id }).from(customerProfiles).where(and(eq(customerProfiles.id, input.customerId), eq(customerProfiles.organizationId, input.organizationId), input.branchId ? eq(customerProfiles.branchId, input.branchId) : undefined)).limit(1);
  if (!customer.length) throw new TRPCError({ code: "NOT_FOUND", message: "Customer is outside the authorized scope" });
}

async function assertScopedTicket(db: Database, input: { ticketId: number; organizationId: number; branchId?: number | null }) {
  const ticket = await db.select({ id: callTickets.id }).from(callTickets).where(and(eq(callTickets.id, input.ticketId), eq(callTickets.organizationId, input.organizationId), input.branchId ? eq(callTickets.branchId, input.branchId) : undefined)).limit(1);
  if (!ticket.length) throw new TRPCError({ code: "NOT_FOUND", message: "Ticket is outside the authorized scope" });
}

async function assertScopedCase(db: Database, input: { caseId: number; organizationId: number; branchId?: number | null; jurisdictionId?: number | null }) {
  const caseRow = await db.select({ id: customerCareCases.id }).from(customerCareCases).where(and(eq(customerCareCases.id, input.caseId), eq(customerCareCases.organizationId, input.organizationId), input.branchId ? eq(customerCareCases.branchId, input.branchId) : undefined, hasScopeValue(input.jurisdictionId) ? eq(customerCareCases.jurisdictionId, input.jurisdictionId) : undefined)).limit(1);
  if (!caseRow.length) throw new TRPCError({ code: "NOT_FOUND", message: "Case is outside the authorized scope" });
}

async function assertScopedContact(db: Database, input: { contactId: number; organizationId: number; branchId?: number | null }) {
  const contact = await db.select({ id: crmContacts.id }).from(crmContacts).where(and(eq(crmContacts.id, input.contactId), eq(crmContacts.organizationId, input.organizationId), input.branchId ? eq(crmContacts.branchId, input.branchId) : undefined)).limit(1);
  if (!contact.length) throw new TRPCError({ code: "NOT_FOUND", message: "Contact is outside the authorized scope" });
}

async function assertScopedOpportunity(db: Database, input: { opportunityId: number; organizationId: number; branchId?: number | null }) {
  const opportunity = await db.select({ id: crmOpportunities.id }).from(crmOpportunities).where(and(eq(crmOpportunities.id, input.opportunityId), eq(crmOpportunities.organizationId, input.organizationId), input.branchId ? eq(crmOpportunities.branchId, input.branchId) : undefined)).limit(1);
  if (!opportunity.length) throw new TRPCError({ code: "NOT_FOUND", message: "Opportunity is outside the authorized scope" });
}

async function assertScopedEmployee(db: Database, input: { employeeProfileId: number; organizationId: number; branchId?: number | null }) {
  const employee = await db.select({ id: employeeProfiles.id }).from(employeeProfiles).where(and(eq(employeeProfiles.id, input.employeeProfileId), eq(employeeProfiles.organizationId, input.organizationId), input.branchId ? eq(employeeProfiles.branchId, input.branchId) : undefined)).limit(1);
  if (!employee.length) throw new TRPCError({ code: "NOT_FOUND", message: "Employee is outside the authorized scope" });
}

export const secondaryModulesRouter = router({
  crm: router({
    contacts: protectedProcedure.input(scope.extend({ displayLabel: z.string().trim().min(2).max(180), contactReferenceHash: z.string().trim().max(128).optional(), consentStatus: z.enum(["unknown", "granted", "withdrawn", "not_required"]).default("unknown"), leadId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => {
      const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input);
      if (input.leadId) { const lead = await db.select({ id: crmLeads.id }).from(crmLeads).where(and(eq(crmLeads.id, input.leadId), eq(crmLeads.organizationId, input.organizationId), input.branchId ? eq(crmLeads.branchId, input.branchId) : undefined)).limit(1); if (!lead.length) throw new TRPCError({ code: "NOT_FOUND", message: "Lead is outside the authorized scope" }); }
      if (input.contactReferenceHash) { const duplicate = await db.select({ id: crmContacts.id }).from(crmContacts).where(and(eq(crmContacts.organizationId, input.organizationId), eq(crmContacts.contactReferenceHash, input.contactReferenceHash))).limit(1); if (duplicate.length) throw new TRPCError({ code: "CONFLICT", message: "A contact with this reference already exists" }); }
      const result = await db.insert(crmContacts).values({ organizationId: input.organizationId, branchId: input.branchId ?? null, jurisdictionId: input.jurisdictionId ?? null, leadId: input.leadId, displayLabel: input.displayLabel, contactReferenceHash: input.contactReferenceHash, consentStatus: input.consentStatus, createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "crm_contact_created", entityType: "crm_contact", entityId: id }); return { id };
    }),
    listContacts: protectedProcedure.input(scope).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); return db.select().from(crmContacts).where(and(eq(crmContacts.organizationId, input.organizationId), input.branchId ? eq(crmContacts.branchId, input.branchId) : undefined)).orderBy(desc(crmContacts.updatedAt)).limit(100); }),
    listOpportunities: protectedProcedure.input(scope).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); return db.select().from(crmOpportunities).where(and(eq(crmOpportunities.organizationId, input.organizationId), input.branchId ? eq(crmOpportunities.branchId, input.branchId) : undefined)).orderBy(desc(crmOpportunities.updatedAt)).limit(100); }),
    listActivities: protectedProcedure.input(scope).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); return db.select().from(crmActivities).where(and(eq(crmActivities.organizationId, input.organizationId), input.branchId ? eq(crmActivities.branchId, input.branchId) : undefined)).orderBy(desc(crmActivities.createdAt)).limit(100); }),
    opportunities: protectedProcedure.input(scope.extend({ title: z.string().trim().min(2).max(220), contactId: z.number().int().positive().optional(), amount: z.coerce.number().nonnegative().finite().optional(), probability: z.number().int().min(0).max(100).default(0), expectedCloseAt: z.coerce.date().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); if (input.contactId) await assertScopedContact(db, { contactId: input.contactId, organizationId: input.organizationId, branchId: input.branchId }); const result = await db.insert(crmOpportunities).values({ organizationId: input.organizationId, branchId: input.branchId ?? null, jurisdictionId: input.jurisdictionId ?? null, contactId: input.contactId, title: input.title, amount: input.amount?.toFixed(2), probability: input.probability, expectedCloseAt: input.expectedCloseAt, createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "crm_opportunity_created", entityType: "crm_opportunity", entityId: id }); return { id }; }),
    addActivity: protectedProcedure.input(scope.extend({ contactId: z.number().int().positive().optional(), opportunityId: z.number().int().positive().optional(), activityType: z.enum(["call", "meeting", "message", "task", "note"]), subject: z.string().trim().min(2).max(220), dueAt: z.coerce.date().optional(), assignedToUserId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); if (!input.contactId && !input.opportunityId) throw new TRPCError({ code: "BAD_REQUEST", message: "An activity requires a contact or opportunity" }); if (input.contactId) await assertScopedContact(db, { contactId: input.contactId, organizationId: input.organizationId, branchId: input.branchId }); if (input.opportunityId) await assertScopedOpportunity(db, { opportunityId: input.opportunityId, organizationId: input.organizationId, branchId: input.branchId }); await assertScopedUser(db, { organizationId: input.organizationId, branchId: input.branchId, userId: input.assignedToUserId }); const result = await db.insert(crmActivities).values({ organizationId: input.organizationId, branchId: input.branchId ?? null, jurisdictionId: input.jurisdictionId ?? null, contactId: input.contactId, opportunityId: input.opportunityId, activityType: input.activityType, subject: input.subject, dueAt: input.dueAt, assignedToUserId: input.assignedToUserId, createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "crm_activity_created", entityType: "crm_activity", entityId: id }); return { id }; }),
    transitionOpportunity: protectedProcedure.input(scope.extend({ opportunityId: z.number().int().positive(), nextStage: z.enum(["discovery", "qualified", "proposal", "negotiation", "won", "lost"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); const row = (await db.select().from(crmOpportunities).where(and(eq(crmOpportunities.id, input.opportunityId), eq(crmOpportunities.organizationId, input.organizationId), input.branchId ? eq(crmOpportunities.branchId, input.branchId) : undefined)).limit(1))[0]; if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Opportunity is outside the authorized scope" }); if (!canTransitionCrmOpportunity(row.stage, input.nextStage)) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Opportunity transition is not allowed" }); if (input.nextStage === "won") await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); await db.update(crmOpportunities).set({ stage: input.nextStage }).where(eq(crmOpportunities.id, row.id)); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: `crm_opportunity_${input.nextStage}`, entityType: "crm_opportunity", entityId: row.id }); return { id: row.id, stage: input.nextStage }; }),
    completeActivity: protectedProcedure.input(scope.extend({ activityId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); const row = (await db.select({ id: crmActivities.id }).from(crmActivities).where(and(eq(crmActivities.id, input.activityId), eq(crmActivities.organizationId, input.organizationId), input.branchId ? eq(crmActivities.branchId, input.branchId) : undefined)).limit(1))[0]; if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Activity is outside the authorized scope" }); await db.update(crmActivities).set({ completedAt: new Date() }).where(eq(crmActivities.id, row.id)); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "crm_activity_completed", entityType: "crm_activity", entityId: row.id }); return { id: row.id, completedAt: new Date() }; }),
    convertLead: protectedProcedure.input(scope.extend({ leadId: z.number().int().positive(), opportunityTitle: z.string().trim().min(2).max(220).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); if (input.branchId) await assertBranch(db, ctx.user.id, ctx.user.role, input.organizationId, input.branchId); const lead = (await db.select().from(crmLeads).where(and(eq(crmLeads.id, input.leadId), eq(crmLeads.organizationId, input.organizationId), input.branchId ? eq(crmLeads.branchId, input.branchId) : undefined)).limit(1))[0]; if (!lead) throw new TRPCError({ code: "NOT_FOUND", message: "Lead is outside the authorized scope" }); if (lead.consentStatus === "withdrawn") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "A withdrawn lead cannot be converted" }); if (lead.stage === "converted") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Lead was already converted" }); const contact = (await db.insert(crmContacts).values({ organizationId: lead.organizationId, branchId: lead.branchId, jurisdictionId: lead.jurisdictionId, leadId: lead.id, displayLabel: lead.label, contactReferenceHash: lead.contactReferenceHash, consentStatus: lead.consentStatus, createdByUserId: ctx.user.id })); const contactId = Number(contact[0].insertId); let opportunityId: number | null = null; if (input.opportunityTitle) { const opportunity = await db.insert(crmOpportunities).values({ organizationId: lead.organizationId, branchId: lead.branchId, jurisdictionId: lead.jurisdictionId, contactId, title: input.opportunityTitle, ownerUserId: lead.assignedToUserId, createdByUserId: ctx.user.id }); opportunityId = Number(opportunity[0].insertId); } await db.update(crmLeads).set({ stage: "converted" }).where(eq(crmLeads.id, lead.id)); await audit(db, { userId: ctx.user.id, organizationId: lead.organizationId, branchId: lead.branchId, action: "crm_lead_converted", entityType: "crm_lead", entityId: lead.id }); return { leadId: lead.id, contactId, opportunityId }; }),
  }),
  hr: router({
    contracts: protectedProcedure.input(scope.extend({ employeeProfileId: z.number().int().positive(), contractType: z.enum(["permanent", "temporary", "part_time", "consultant"]), startsAt: z.coerce.date(), endsAt: z.coerce.date().optional(), salaryBand: z.string().trim().max(80).optional(), documentRef: z.string().trim().max(255).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); await validateScope(db, ctx, input); await assertScopedEmployee(db, input); if (input.endsAt && input.endsAt <= input.startsAt) throw new TRPCError({ code: "BAD_REQUEST", message: "Contract end must follow its start" }); const result = await db.insert(hrContracts).values({ organizationId: input.organizationId, branchId: input.branchId ?? null, jurisdictionId: input.jurisdictionId ?? null, employeeProfileId: input.employeeProfileId, contractType: input.contractType, startsAt: input.startsAt, endsAt: input.endsAt, salaryBand: input.salaryBand, documentRef: input.documentRef, createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "hr_contract_created", entityType: "hr_contract", entityId: id }); return { id }; }),
    shifts: protectedProcedure.input(scope.extend({ employeeProfileId: z.number().int().positive(), shiftDate: z.coerce.date(), startsAt: z.coerce.date(), endsAt: z.coerce.date() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); if (!input.branchId) throw new TRPCError({ code: "BAD_REQUEST", message: "Branch is required for a shift" }); await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); await validateScope(db, ctx, input); await assertScopedEmployee(db, input); if (input.endsAt <= input.startsAt) throw new TRPCError({ code: "BAD_REQUEST", message: "Shift end must follow start" }); const result = await db.insert(hrShifts).values({ organizationId: input.organizationId, branchId: input.branchId, jurisdictionId: input.jurisdictionId ?? null, employeeProfileId: input.employeeProfileId, shiftDate: input.shiftDate, startsAt: input.startsAt, endsAt: input.endsAt, createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "hr_shift_created", entityType: "hr_shift", entityId: id }); return { id }; }),
    listContracts: protectedProcedure.input(scope).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); await validateScope(db, ctx, input); return db.select().from(hrContracts).where(and(eq(hrContracts.organizationId, input.organizationId), input.branchId ? eq(hrContracts.branchId, input.branchId) : undefined)).orderBy(desc(hrContracts.updatedAt)).limit(100); }),
    listShifts: protectedProcedure.input(scope).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); await validateScope(db, ctx, input); return db.select().from(hrShifts).where(and(eq(hrShifts.organizationId, input.organizationId), input.branchId ? eq(hrShifts.branchId, input.branchId) : undefined)).orderBy(desc(hrShifts.createdAt)).limit(100); }),
    listReviews: protectedProcedure.input(scope).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); await validateScope(db, ctx, input); return db.select().from(hrPerformanceReviews).where(and(eq(hrPerformanceReviews.organizationId, input.organizationId), input.branchId ? eq(hrPerformanceReviews.branchId, input.branchId) : undefined)).orderBy(desc(hrPerformanceReviews.updatedAt)).limit(100); }),
    review: protectedProcedure.input(scope.extend({ employeeProfileId: z.number().int().positive(), reviewPeriod: z.string().trim().min(4).max(32), score: z.number().int().min(0).max(100).optional(), goalsSummary: z.string().trim().max(4000).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); if (input.branchId) await assertBranch(db, ctx.user.id, ctx.user.role, input.organizationId, input.branchId); const result = await db.insert(hrPerformanceReviews).values({ organizationId: input.organizationId, branchId: input.branchId ?? null, employeeProfileId: input.employeeProfileId, reviewPeriod: input.reviewPeriod, score: input.score, goalsSummary: input.goalsSummary, createdByUserId: ctx.user.id }).onDuplicateKeyUpdate({ set: { score: input.score, goalsSummary: input.goalsSummary, status: "draft", updatedAt: new Date() } }); const id = Number(result[0].insertId); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "hr_review_saved", entityType: "hr_performance_review", entityId: id || input.employeeProfileId }); return { id: id || null }; }),
    transitionContract: protectedProcedure.input(scope.extend({ contractId: z.number().int().positive(), nextStatus: z.enum(["active", "expired", "terminated"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); if (input.branchId) await assertBranch(db, ctx.user.id, ctx.user.role, input.organizationId, input.branchId); const row = (await db.select().from(hrContracts).where(and(eq(hrContracts.id, input.contractId), eq(hrContracts.organizationId, input.organizationId), input.branchId ? eq(hrContracts.branchId, input.branchId) : undefined)).limit(1))[0]; if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Contract is outside the authorized scope" }); const allowed: Record<string, string[]> = { draft: ["active", "terminated"], active: ["expired", "terminated"], expired: [], terminated: [] }; if (!allowed[row.status].includes(input.nextStatus)) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Contract transition is not allowed" }); if (input.nextStatus === "active" && row.startsAt > new Date()) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "A contract cannot be activated before its start date" }); await db.update(hrContracts).set({ status: input.nextStatus }).where(eq(hrContracts.id, row.id)); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: `hr_contract_${input.nextStatus}`, entityType: "hr_contract", entityId: row.id }); return { id: row.id, status: input.nextStatus }; }),
    transitionShift: protectedProcedure.input(scope.extend({ shiftId: z.number().int().positive(), nextStatus: z.enum(["confirmed", "cancelled", "completed"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); if (!input.branchId) throw new TRPCError({ code: "BAD_REQUEST", message: "Branch is required for a shift transition" }); await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); await assertBranch(db, ctx.user.id, ctx.user.role, input.organizationId, input.branchId); const row = (await db.select().from(hrShifts).where(and(eq(hrShifts.id, input.shiftId), eq(hrShifts.organizationId, input.organizationId), eq(hrShifts.branchId, input.branchId))).limit(1))[0]; if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Shift is outside the authorized scope" }); const allowed: Record<string, string[]> = { planned: ["confirmed", "cancelled"], confirmed: ["completed", "cancelled"], completed: [], cancelled: [] }; if (!allowed[row.status].includes(input.nextStatus)) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Shift transition is not allowed" }); await db.update(hrShifts).set({ status: input.nextStatus }).where(eq(hrShifts.id, row.id)); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: `hr_shift_${input.nextStatus}`, entityType: "hr_shift", entityId: row.id }); return { id: row.id, status: input.nextStatus }; }),
    transitionReview: protectedProcedure.input(scope.extend({ reviewId: z.number().int().positive(), nextStatus: z.enum(["submitted", "approved", "draft"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); if (input.branchId) await assertBranch(db, ctx.user.id, ctx.user.role, input.organizationId, input.branchId); const row = (await db.select().from(hrPerformanceReviews).where(and(eq(hrPerformanceReviews.id, input.reviewId), eq(hrPerformanceReviews.organizationId, input.organizationId), input.branchId ? eq(hrPerformanceReviews.branchId, input.branchId) : undefined)).limit(1))[0]; if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Review is outside the authorized scope" }); const allowed: Record<string, string[]> = { draft: ["submitted"], submitted: ["draft", "approved"], approved: [] }; if (!allowed[row.status].includes(input.nextStatus)) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Review transition is not allowed" }); await db.update(hrPerformanceReviews).set({ status: input.nextStatus, reviewedByUserId: input.nextStatus === "approved" ? ctx.user.id : row.reviewedByUserId, updatedAt: new Date() }).where(eq(hrPerformanceReviews.id, row.id)); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: `hr_review_${input.nextStatus}`, entityType: "hr_performance_review", entityId: row.id }); return { id: row.id, status: input.nextStatus }; }),
  }),
  callCenter: router({
    queues: protectedProcedure.input(scope.extend({ name: z.string().trim().min(2).max(160), skill: z.string().trim().max(100).optional(), slaMinutes: z.number().int().positive().max(10080).default(60) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); if (input.branchId) await assertBranch(db, ctx.user.id, ctx.user.role, input.organizationId, input.branchId); const result = await db.insert(callQueues).values({ organizationId: input.organizationId, branchId: input.branchId ?? null, name: input.name, skill: input.skill, slaMinutes: input.slaMinutes, createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "call_queue_created", entityType: "call_queue", entityId: id }); return { id }; }),
    listQueues: protectedProcedure.input(scope).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); return db.select().from(callQueues).where(and(eq(callQueues.organizationId, input.organizationId), input.branchId ? eq(callQueues.branchId, input.branchId) : undefined)).orderBy(desc(callQueues.createdAt)).limit(100); }),
    addMember: protectedProcedure.input(scope.extend({ queueId: z.number().int().positive(), userId: z.number().int().positive(), skill: z.string().trim().max(100).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); if (!input.branchId) throw new TRPCError({ code: "BAD_REQUEST", message: "Branch is required for queue membership" }); await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); await assertBranch(db, ctx.user.id, ctx.user.role, input.organizationId, input.branchId); const queue = await db.select({ id: callQueues.id }).from(callQueues).where(and(eq(callQueues.id, input.queueId), eq(callQueues.organizationId, input.organizationId), eq(callQueues.branchId, input.branchId), eq(callQueues.active, 1))).limit(1); if (!queue.length) throw new TRPCError({ code: "NOT_FOUND", message: "Queue is outside the authorized branch" }); await assertScopedUser(db, { organizationId: input.organizationId, branchId: input.branchId, userId: input.userId }); const result = await db.insert(callQueueMembers).values({ organizationId: input.organizationId, branchId: input.branchId, queueId: input.queueId, userId: input.userId, skill: input.skill, createdByUserId: ctx.user.id }).onDuplicateKeyUpdate({ set: { active: 1, skill: input.skill } }); const id = Number(result[0].insertId); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "call_queue_member_added", entityType: "call_queue_member", entityId: id || input.queueId }); return { id: id || null }; }),
    listTickets: protectedProcedure.input(scope.extend({ status: z.enum(["open", "pending", "resolved", "closed"]).optional() })).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); return db.select().from(callTickets).where(and(eq(callTickets.organizationId, input.organizationId), input.branchId ? eq(callTickets.branchId, input.branchId) : undefined, input.status ? eq(callTickets.status, input.status) : undefined)).orderBy(desc(callTickets.updatedAt)).limit(100); }),
    listInteractions: protectedProcedure.input(scope.extend({ ticketId: z.number().int().positive() })).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); await assertScopedTicket(db, input); return db.select().from(callInteractions).where(and(eq(callInteractions.organizationId, input.organizationId), eq(callInteractions.ticketId, input.ticketId), input.branchId ? eq(callInteractions.branchId, input.branchId) : undefined)).orderBy(desc(callInteractions.createdAt)).limit(100); }),
    assignTicket: protectedProcedure.input(scope.extend({ ticketId: z.number().int().positive(), queueId: z.number().int().positive(), assignedUserId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); if (!input.branchId) throw new TRPCError({ code: "BAD_REQUEST", message: "Branch is required for ticket assignment" }); await assertManager(db, ctx.user.id, ctx.user.role, input.organizationId); await assertBranch(db, ctx.user.id, ctx.user.role, input.organizationId, input.branchId); await assertScopedTicket(db, input); const queue = (await db.select().from(callQueues).where(and(eq(callQueues.id, input.queueId), eq(callQueues.organizationId, input.organizationId), eq(callQueues.branchId, input.branchId), eq(callQueues.active, 1))).limit(1))[0]; if (!queue) throw new TRPCError({ code: "NOT_FOUND", message: "Queue is outside the authorized branch" }); await assertScopedUser(db, { organizationId: input.organizationId, branchId: input.branchId, userId: input.assignedUserId }); const member = await db.select({ id: callQueueMembers.id }).from(callQueueMembers).where(and(eq(callQueueMembers.queueId, queue.id), eq(callQueueMembers.userId, input.assignedUserId), eq(callQueueMembers.organizationId, input.organizationId), eq(callQueueMembers.branchId, input.branchId), eq(callQueueMembers.active, 1))).limit(1); if (!member.length) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Assigned user is not an active queue member" }); const now = new Date(); const slaDueAt = new Date(now.getTime() + queue.slaMinutes * 60_000); await db.update(callTickets).set({ queueId: queue.id, assignedUserId: input.assignedUserId, status: "pending", firstRespondedAt: now, slaDueAt }).where(eq(callTickets.id, input.ticketId)); const interaction = await db.insert(callInteractions).values({ organizationId: input.organizationId, branchId: input.branchId, ticketId: input.ticketId, userId: ctx.user.id, interactionType: "assignment", summary: `Assigned to queue ${queue.id}` }); const interactionId = Number(interaction[0].insertId); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "call_ticket_assigned", entityType: "call_ticket", entityId: input.ticketId }); return { id: input.ticketId, queueId: queue.id, slaDueAt, interactionId }; }),
    updateTicket: protectedProcedure.input(scope.extend({ ticketId: z.number().int().positive(), nextStatus: z.enum(["pending", "resolved", "closed"]), disposition: z.string().trim().min(2).max(120).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); const ticket = (await db.select().from(callTickets).where(and(eq(callTickets.id, input.ticketId), eq(callTickets.organizationId, input.organizationId), input.branchId ? eq(callTickets.branchId, input.branchId) : undefined)).limit(1))[0]; if (!ticket) throw new TRPCError({ code: "NOT_FOUND", message: "Ticket is outside the authorized scope" }); const allowed: Record<string, string[]> = { open: ["pending", "resolved"], pending: ["resolved", "closed"], resolved: ["pending", "closed"], closed: [] }; if (!allowed[ticket.status].includes(input.nextStatus)) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Ticket transition is not allowed" }); if (input.nextStatus === "closed" && !input.disposition && !ticket.disposition) throw new TRPCError({ code: "BAD_REQUEST", message: "A closed ticket requires a disposition" }); const now = new Date(); await db.update(callTickets).set({ status: input.nextStatus, disposition: input.disposition ?? ticket.disposition, resolvedAt: input.nextStatus === "resolved" ? now : ticket.resolvedAt }).where(eq(callTickets.id, ticket.id)); const interaction = await db.insert(callInteractions).values({ organizationId: input.organizationId, branchId: input.branchId ?? null, ticketId: ticket.id, userId: ctx.user.id, interactionType: "status_change", summary: `Status changed to ${input.nextStatus}` }); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: `call_ticket_${input.nextStatus}`, entityType: "call_ticket", entityId: ticket.id }); return { id: ticket.id, status: input.nextStatus, interactionId: Number(interaction[0].insertId) }; }),
    scheduleCallback: protectedProcedure.input(scope.extend({ ticketId: z.number().int().positive(), callbackAt: z.coerce.date(), summary: z.string().trim().min(2).max(4000) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); await assertScopedTicket(db, input); if (input.callbackAt <= new Date()) throw new TRPCError({ code: "BAD_REQUEST", message: "Callback must be scheduled in the future" }); await db.update(callTickets).set({ callbackAt: input.callbackAt, status: "pending" }).where(eq(callTickets.id, input.ticketId)); const interaction = await db.insert(callInteractions).values({ organizationId: input.organizationId, branchId: input.branchId ?? null, ticketId: input.ticketId, userId: ctx.user.id, interactionType: "callback", summary: input.summary }); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "call_ticket_callback_scheduled", entityType: "call_ticket", entityId: input.ticketId }); return { id: input.ticketId, callbackAt: input.callbackAt, interactionId: Number(interaction[0].insertId) }; }),
    slaWatch: protectedProcedure.input(scope).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); const now = new Date(); const rows = await db.select().from(callTickets).where(and(eq(callTickets.organizationId, input.organizationId), input.branchId ? eq(callTickets.branchId, input.branchId) : undefined, sql`${callTickets.status} IN ('open', 'pending')`, sql`${callTickets.slaDueAt} IS NOT NULL`, sql`${callTickets.slaDueAt} <= ${now}`)).orderBy(callTickets.slaDueAt).limit(100); return { checkedAt: now, overdue: rows }; }),
    addInteraction: protectedProcedure.input(scope.extend({ ticketId: z.number().int().positive(), interactionType: z.enum(["note", "message", "status_change", "assignment", "escalation", "callback"]), summary: z.string().trim().min(2).max(4000), metadataHash: z.string().trim().max(128).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); await assertScopedTicket(db, input); const result = await db.insert(callInteractions).values({ organizationId: input.organizationId, branchId: input.branchId ?? null, ticketId: input.ticketId, userId: ctx.user.id, interactionType: input.interactionType, summary: input.summary, metadataHash: input.metadataHash }); const id = Number(result[0].insertId); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "call_interaction_added", entityType: "call_interaction", entityId: id }); return { id }; }),
  }),
  dashboard: router({
    summary: protectedProcedure.input(scope).query(async ({ ctx, input }) => {
      const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input);
      const where = (organizationId: any, branchId: any) => and(eq(organizationId, input.organizationId), input.branchId ? eq(branchId, input.branchId) : undefined);
      const [contacts, opportunities, contracts, shifts, queues, cases, tasks, salesRows, purchaseRows, ticketRows, customerRows] = await Promise.all([
        db.select({ count: sql<number>`count(*)` }).from(crmContacts).where(where(crmContacts.organizationId, crmContacts.branchId)),
        db.select({ count: sql<number>`count(*)` }).from(crmOpportunities).where(where(crmOpportunities.organizationId, crmOpportunities.branchId)),
        db.select({ count: sql<number>`count(*)` }).from(hrContracts).where(where(hrContracts.organizationId, hrContracts.branchId)),
        db.select({ count: sql<number>`count(*)` }).from(hrShifts).where(where(hrShifts.organizationId, hrShifts.branchId)),
        db.select({ count: sql<number>`count(*)` }).from(callQueues).where(where(callQueues.organizationId, callQueues.branchId)),
        db.select({ count: sql<number>`count(*)` }).from(customerCareCases).where(where(customerCareCases.organizationId, customerCareCases.branchId)),
        db.select({ count: sql<number>`count(*)` }).from(customerCareTasks).where(where(customerCareTasks.organizationId, customerCareTasks.branchId)),
        db.select({ count: sql<number>`count(*)` }).from(sales).where(where(sales.organizationId, sales.branchId)),
        db.select({ count: sql<number>`count(*)` }).from(purchaseOrders).where(where(purchaseOrders.organizationId, purchaseOrders.branchId)),
        db.select({ count: sql<number>`count(*)` }).from(callTickets).where(where(callTickets.organizationId, callTickets.branchId)),
        db.select({ count: sql<number>`count(*)` }).from(customerProfiles).where(where(customerProfiles.organizationId, customerProfiles.branchId)),
      ]);
      return { scope: { organizationId: input.organizationId, branchId: input.branchId ?? null }, crm: { contacts: Number(contacts[0]?.count ?? 0), opportunities: Number(opportunities[0]?.count ?? 0) }, hr: { contracts: Number(contracts[0]?.count ?? 0), shifts: Number(shifts[0]?.count ?? 0) }, callCenter: { queues: Number(queues[0]?.count ?? 0), tickets: Number(ticketRows[0]?.count ?? 0) }, customerCare: { cases: Number(cases[0]?.count ?? 0), tasks: Number(tasks[0]?.count ?? 0), customers: Number(customerRows[0]?.count ?? 0) }, integrations: { sales: Number(salesRows[0]?.count ?? 0), purchaseOrders: Number(purchaseRows[0]?.count ?? 0), policyGrounding: "approved-scope-only", notifications: "existing-notification-contract" }, generatedAt: new Date() };
    }),
  }),
  ai: router({
    recommendations: protectedProcedure.input(scope.extend({ module: z.enum(["crm", "hr", "call_center", "customer_care"]), metrics: z.array(z.object({ key: z.string().trim().min(1).max(80), value: z.union([z.string().max(240), z.number().finite()]) }).strict()).max(40), question: z.string().trim().min(4).max(600) })).mutation(async ({ ctx, input }) => {
      const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input);
      const safeMetrics = input.metrics.map(metric => ({ key: metric.key, value: metric.value }));
      let content = "";
      try {
        const response = await invokeLLM({ messages: [
          { role: "system", content: "You provide conservative operational suggestions for a healthcare ERP. Return only JSON matching the schema. Never identify a person, diagnose, approve employment, move money, contact a customer, or change a record. Every suggestion must require human review." },
          { role: "user", content: JSON.stringify({ module: input.module, question: input.question, metrics: safeMetrics }) },
        ], response_format: { type: "json_schema", json_schema: { name: "medora_operational_recommendations", strict: true, schema: { type: "object", properties: { summary: { type: "string" }, recommendations: { type: "array", items: { type: "object", properties: { title: { type: "string" }, rationale: { type: "string" }, priority: { type: "string", enum: ["low", "medium", "high"] }, requiresHumanReview: { type: "boolean", const: true }, evidenceKeys: { type: "array", items: { type: "string" } } }, required: ["title", "rationale", "priority", "requiresHumanReview", "evidenceKeys"], additionalProperties: false } } }, required: ["summary", "recommendations"], additionalProperties: false } } } });
        content = typeof response.choices?.[0]?.message?.content === "string" ? response.choices[0].message.content : "";
      } catch { content = JSON.stringify({ summary: "لم تتوفر التوصيات الذكية الآن؛ استخدم المؤشرات التشغيلية دون تخمين.", recommendations: [] }); }
      await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "secondary_ai_recommendations_generated", entityType: "secondary_ai", entityId: 0 });
      return { module: input.module, scope: { organizationId: input.organizationId, branchId: input.branchId ?? null }, requiresHumanReview: true, recommendations: content };
    }),
  }),
  customerCare: router({
    customer360: protectedProcedure.input(scope.extend({ customerId: z.number().int().positive() })).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); await assertScopedCustomer(db, input); const customer = (await db.select({ id: customerProfiles.id, fullName: customerProfiles.fullName, phone: customerProfiles.phone, consentStatus: customerProfiles.consentStatus, chronicCareEnabled: customerProfiles.chronicCareEnabled, updatedAt: customerProfiles.updatedAt }).from(customerProfiles).where(and(eq(customerProfiles.id, input.customerId), eq(customerProfiles.organizationId, input.organizationId), input.branchId ? eq(customerProfiles.branchId, input.branchId) : undefined)).limit(1))[0]; const [cases, tasks, tickets, interactions] = await Promise.all([db.select().from(customerCareCases).where(and(eq(customerCareCases.organizationId, input.organizationId), eq(customerCareCases.customerId, input.customerId), input.branchId ? eq(customerCareCases.branchId, input.branchId) : undefined)).orderBy(desc(customerCareCases.updatedAt)).limit(100), db.select().from(customerCareTasks).where(and(eq(customerCareTasks.organizationId, input.organizationId), input.branchId ? eq(customerCareTasks.branchId, input.branchId) : undefined)).orderBy(desc(customerCareTasks.createdAt)).limit(100), db.select().from(callTickets).where(and(eq(callTickets.organizationId, input.organizationId), eq(callTickets.customerId, input.customerId), input.branchId ? eq(callTickets.branchId, input.branchId) : undefined)).orderBy(desc(callTickets.updatedAt)).limit(100), db.select().from(careInteractions).where(eq(careInteractions.customerId, input.customerId)).orderBy(desc(careInteractions.createdAt)).limit(100)]); const caseIds = new Set(cases.map(row => row.id)); return { customer, cases, tasks: tasks.filter(task => caseIds.has(task.caseId)), tickets, interactions }; }),
    transitionCase: protectedProcedure.input(scope.extend({ caseId: z.number().int().positive(), nextStatus: z.enum(["in_progress", "waiting_customer", "resolved", "closed"]), assignedToUserId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); const row = (await db.select().from(customerCareCases).where(and(eq(customerCareCases.id, input.caseId), eq(customerCareCases.organizationId, input.organizationId), input.branchId ? eq(customerCareCases.branchId, input.branchId) : undefined, hasScopeValue(input.jurisdictionId) ? eq(customerCareCases.jurisdictionId, input.jurisdictionId) : undefined)).limit(1))[0]; if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Case is outside the authorized scope" }); if (!canTransitionCustomerCase(row.status, input.nextStatus)) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Case transition is not allowed" }); if (input.assignedToUserId) await assertScopedUser(db, { organizationId: input.organizationId, branchId: input.branchId, userId: input.assignedToUserId }); if (input.nextStatus === "closed") { const openTasks = await db.select({ id: customerCareTasks.id }).from(customerCareTasks).where(and(eq(customerCareTasks.organizationId, input.organizationId), eq(customerCareTasks.caseId, row.id), sql`${customerCareTasks.status} IN ('open', 'in_progress')`)).limit(1); if (openTasks.length) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Complete or cancel outstanding care tasks before closing the case" }); } await db.update(customerCareCases).set({ status: input.nextStatus, assignedToUserId: input.assignedToUserId ?? row.assignedToUserId }).where(eq(customerCareCases.id, row.id)); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: `customer_care_case_${input.nextStatus}`, entityType: "customer_care_case", entityId: row.id }); return { id: row.id, status: input.nextStatus }; }),
    transitionTask: protectedProcedure.input(scope.extend({ taskId: z.number().int().positive(), nextStatus: z.enum(["in_progress", "done", "cancelled"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); const row = (await db.select().from(customerCareTasks).where(and(eq(customerCareTasks.id, input.taskId), eq(customerCareTasks.organizationId, input.organizationId), input.branchId ? eq(customerCareTasks.branchId, input.branchId) : undefined)).limit(1))[0]; if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Task is outside the authorized scope" }); await assertScopedCase(db, { caseId: row.caseId, organizationId: input.organizationId, branchId: input.branchId, jurisdictionId: input.jurisdictionId }); const allowed: Record<string, string[]> = { open: ["in_progress", "done", "cancelled"], in_progress: ["done", "cancelled"], done: [], cancelled: [] }; if (!allowed[row.status].includes(input.nextStatus)) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Task transition is not allowed" }); const completedAt = input.nextStatus === "done" ? new Date() : row.completedAt; await db.update(customerCareTasks).set({ status: input.nextStatus, completedAt }).where(eq(customerCareTasks.id, row.id)); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: `customer_care_task_${input.nextStatus}`, entityType: "customer_care_task", entityId: row.id }); return { id: row.id, status: input.nextStatus, completedAt }; }),
    cases: protectedProcedure.input(scope.extend({ customerId: z.number().int().positive(), caseNumber: z.string().trim().min(4).max(80), category: z.enum(["question", "complaint", "follow_up", "chronic_care", "service_request"]), priority: z.enum(["low", "normal", "high", "urgent"]).default("normal"), subject: z.string().trim().min(2).max(220), summary: z.string().trim().min(2).max(8000), assignedToUserId: z.number().int().positive().optional(), nextActionAt: z.coerce.date().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); await assertScopedCustomer(db, input); await assertScopedUser(db, { organizationId: input.organizationId, branchId: input.branchId, userId: input.assignedToUserId }); const result = await db.insert(customerCareCases).values({ organizationId: input.organizationId, branchId: input.branchId ?? null, jurisdictionId: input.jurisdictionId ?? null, customerId: input.customerId, caseNumber: input.caseNumber, category: input.category, priority: input.priority, subject: input.subject, summary: input.summary, assignedToUserId: input.assignedToUserId, nextActionAt: input.nextActionAt, createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "customer_care_case_created", entityType: "customer_care_case", entityId: id }); return { id, caseNumber: input.caseNumber }; }),
    list: protectedProcedure.input(scope).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); return db.select().from(customerCareCases).where(and(eq(customerCareCases.organizationId, input.organizationId), input.branchId ? eq(customerCareCases.branchId, input.branchId) : undefined)).orderBy(desc(customerCareCases.updatedAt)).limit(100); }),
    listTasks: protectedProcedure.input(scope).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); return db.select().from(customerCareTasks).where(and(eq(customerCareTasks.organizationId, input.organizationId), input.branchId ? eq(customerCareTasks.branchId, input.branchId) : undefined)).orderBy(desc(customerCareTasks.createdAt)).limit(100); }),
    task: protectedProcedure.input(scope.extend({ caseId: z.number().int().positive(), title: z.string().trim().min(2).max(220), dueAt: z.coerce.date().optional(), assignedToUserId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); await assertScopedCase(db, input); await assertScopedUser(db, { organizationId: input.organizationId, branchId: input.branchId, userId: input.assignedToUserId }); const result = await db.insert(customerCareTasks).values({ organizationId: input.organizationId, branchId: input.branchId ?? null, caseId: input.caseId, title: input.title, dueAt: input.dueAt, assignedToUserId: input.assignedToUserId, createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "customer_care_task_created", entityType: "customer_care_task", entityId: id }); return { id }; }),
    satisfaction: protectedProcedure.input(scope.extend({ caseId: z.number().int().positive(), score: z.number().int().min(1).max(5), comment: z.string().trim().max(2000).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); await validateScope(db, ctx, input); const caseRow = await db.select({ id: customerCareCases.id }).from(customerCareCases).where(and(eq(customerCareCases.id, input.caseId), eq(customerCareCases.organizationId, input.organizationId), input.branchId ? eq(customerCareCases.branchId, input.branchId) : undefined, hasScopeValue(input.jurisdictionId) ? eq(customerCareCases.jurisdictionId, input.jurisdictionId) : undefined)).limit(1); if (!caseRow.length) throw new TRPCError({ code: "NOT_FOUND", message: "Case is outside the authorized scope" }); const result = await db.insert(customerCareSatisfaction).values({ organizationId: input.organizationId, branchId: input.branchId ?? null, caseId: input.caseId, score: input.score, comment: input.comment, capturedByUserId: ctx.user.id }).onDuplicateKeyUpdate({ set: { score: input.score, comment: input.comment, capturedAt: new Date(), capturedByUserId: ctx.user.id } }); const id = Number(result[0].insertId); await audit(db, { userId: ctx.user.id, organizationId: input.organizationId, branchId: input.branchId, action: "customer_care_satisfaction_captured", entityType: "customer_care_satisfaction", entityId: id || input.caseId }); return { id: id || null }; }),
  }),
});
