import { useEffect, useState } from "react";
const S = { wrap: { maxWidth: 1120, margin: "0 auto", padding: 24, background: "#f4f6f8", minHeight: "100vh", fontFamily: "Inter, 'Segoe UI', sans-serif" } as const, card: { background: "rgba(255,255,255,.92)", border: "1px solid #d9dee5", borderRadius: 18, padding: 18, boxShadow: "0 12px 30px rgba(20,30,45,.06)" } as const };
function enc(v: unknown) { return encodeURIComponent(JSON.stringify(v)); }
async function q<T = unknown>(path: string, input: unknown): Promise<T> { const res = await fetch(`/api/trpc/${path}?batch=1&input=${enc({ "0": { json: input ?? null } })}`, { credentials: "include" }); if (!res.ok) throw new Error(`HTTP ${res.status}`); const j = (await res.json()) as { "0"?: { result?: { data?: { json?: T } | T } } }; const d = j?.["0"]?.result?.data; return ((d && typeof d === "object" && "json" in (d as object)) ? (d as { json: T }).json : d) as T; }
interface Scope { organizationId: number; branchId: number; jurisdictionId: number; }
interface Kpi { code: string; nameAr: string; value: number; target: number; unit: string; achieved: boolean; achievedPct: number; }
export default function KpiDashboard() {
  const scope: Scope = { organizationId: 1, branchId: 1, jurisdictionId: 0 };
  const [kpis, setKpis] = useState<Kpi[] | null>(null); const [err, setErr] = useState<string | null>(null); const [defs, setDefs] = useState<string[]>([]);
  useEffect(() => { Promise.all([q<{ kpis: Kpi[] }>("kpi.dashboard", scope), q<{ definitions: Array<{ code: string }> }>("kpi.definitions", scope)]).then(([d, defsData]) => { setKpis(d.kpis); setDefs((defsData.definitions ?? []).map((x) => x.code)); }).catch((e) => setErr(String((e as Error)?.message ?? e).slice(0, 160))); }, []);
  return <div style={S.wrap}><div style={{ padding: "8px 0 20px" }}><div style={{ fontSize: 12, letterSpacing: 1.2, color: "#68727e", textTransform: "uppercase" }}>MEDORA · PERFORMANCE</div><h2 style={{ margin: "5px 0", color: "#18222d", fontSize: 30 }}>لوحة مؤشرات الأداء KPI</h2><div style={{ color: "#68727e", fontSize: 13 }}>مؤشرات محسوبة من البيانات الحية ضمن نطاق MEDORA الحالي.</div></div>{err && <div style={{ ...S.card, color: "#991b1b" }}>تعذر تحميل المؤشرات: {err}</div>}{!kpis && !err && <div style={{ ...S.card, color: "#68727e" }}>جارٍ حساب المؤشرات…</div>}<div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))", gap: 14 }}>{(kpis ?? []).map((k) => <div key={k.code} style={S.card}><div style={{ fontSize: 13, color: "#4b5563", fontWeight: 700 }}>{k.nameAr}</div><div style={{ fontSize: 30, fontWeight: 800, color: "#18222d", margin: "8px 0" }}>{k.value} <span style={{ fontSize: 13, fontWeight: 500, color: "#68727e" }}>{k.unit}</span></div><div style={{ fontSize: 12, color: "#68727e" }}>الهدف: {k.target} · الإنجاز {k.achievedPct}%</div><div style={{ marginTop: 10 }}><span style={{ display: "inline-block", padding: "4px 11px", borderRadius: 999, fontSize: 12, fontWeight: 700, background: k.achieved ? "#e5f5eb" : "#f9e7e7", color: k.achieved ? "#17633a" : "#8d2424" }}>{k.achieved ? "✔ محقق" : "✖ دون الهدف"}</span></div></div>)}</div><div style={{ ...S.card, marginTop: 16 }}><div style={{ fontWeight: 800, marginBottom: 6 }}>التعاريف ومصادر القياس</div><div style={{ fontSize: 13, color: "#4b5563" }}>{defs.join(" · ") || "لا توجد تعريفات"}</div></div></div>;
}