import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

type WorkspaceBootstrapStatus = "ready" | "nda_loading" | "nda_error" | "nda_required" | "branch_loading" | "branch_error" | "branch_missing";

type ClientLocalization = {
  countryCode: string;
  locale: string;
  language: string;
  direction: "rtl" | "ltr";
  currencyCode: string;
  calendar: string;
  numberingSystem: string;
  t: (key: string) => string;
  formatCurrency: (amount: number) => string;
  setCountry: (countryCode: string) => void;
  setLanguage: (language: "ar" | "en") => void;
  branchId: number | null;
  jurisdictionId: number | null;
  branches: Array<{ id: number; nameAr: string; countryCode: string }>;
  setBranchId: (branchId: number) => void;
  branchSwitching: boolean;
  workspaceBootstrapStatus: WorkspaceBootstrapStatus;
  retryWorkspaceBootstrap: () => Promise<void>;
};

const dictionaries: Record<string, Record<string, string>> = {
  ar: {
    pharmacy: "الصيدلية",
    prescription: "الوصفة الطبية",
    invoice: "الفاتورة",
    branch: "الفرع",
    country: "الدولة",
    "pos.scopeRequired": "يلزم اختيار فرع واختصاص قانوني معتمد",
    "pos.scopeRequiredDetail": "لا يمكن فتح فاتورة منظمة أو البحث في المخزون قبل أن يؤكد الخادم نطاق الفرع والاختصاص.",
    "pos.openSale": "فتح فاتورة بيع",
    "pos.openSaleDescription": "ابحث بالاسم أو استخدم قارئ USB أو Data Matrix. تُحفظ الحمولة الخام كاملة قبل أي تحقق.",
    "pos.currentBranch": "الفرع الحالي · نطاق محمي",
    "pos.saleTools": "أدوات البيع",
    "pos.cameraScan": "مسح بالكاميرا",
    "pos.simulatedScan": "محاكاة المسح",
    "pos.heldInvoices": "المعلقة",
    "pos.cameraTitle": "مسح بالكاميرا",
    "pos.closeCamera": "إغلاق ماسح الكاميرا",
    "pos.cameraPrivacy": "سيطلب المتصفح إذن الكاميرا. لا يتم حفظ الصور أو إطارات الفيديو؛ تُرسل الحمولة المقروءة فقط إلى بحث المخزون المقيد.",
    "pos.preparingCamera": "جارٍ تجهيز الكاميرا…",
    "pos.manualEntry": "استخدام الإدخال اليدوي",
    "pos.openSimulation": "فتح المحاكاة",
    "pos.usbScanner": "قارئ USB",
    "pos.simulatedScanner": "ماسح باركود تجريبي",
    "pos.simulatedScannerDetail": "للاختبار فقط؛ لا يتصل بالكاميرا ولا يغيّر حدود البيانات. اختر صنفًا لمحاكاة قراءة باركوده.",
    "pos.searchOrWait": "اكتب بحثًا أولًا أو انتظر تحميل الأصناف المتاحة.",
    "pos.heldOnDevice": "الفواتير المعلقة على هذا الجهاز",
    "pos.items": "أصناف",
    "pos.restore": "استرجاع",
    "pos.noHeldInvoices": "لا توجد فواتير معلقة.",
    "pos.availableItems": "الأصناف المتاحة",
    "pos.searchPlaceholder": "امسح الباركود أو ابحث بالاسم / SKU",
    "pos.searchAria": "باركود أو بحث أصناف نقطة البيع",
    "pos.addBarcode": "إضافة الباركود",
    "pos.addByCode": "إضافة بالكود",
    "pos.lastScan": "آخر قراءة",
    "pos.unknown": "غير محدد",
    "pos.simulated": "تجريبية",
    "pos.device": "أجهزة",
    "pos.loadingStock": "جارٍ تحميل مخزون الفرع…",
    "pos.stockLoadFailed": "تعذر تحميل المخزون ضمن النطاق الحالي.",
    "pos.batch": "دفعة",
    "pos.available": "متاح",
    "pos.expiry": "انتهاء",
    "pos.add": "إضافة",
    "pos.noItems": "لا توجد أصناف موثقة ومتاحة بهذا البحث.",
    "pos.basketAndInvoice": "السلة والفاتورة",
    "pos.invoiceNumber": "رقم الفاتورة",
    "pos.paymentMethod": "طريقة الدفع",
    "pos.cash": "نقدي",
    "pos.meeza": "ميزة",
    "pos.instapay": "إنستا باي",
    "pos.insurance": "تأمين",
    "pos.remove": "حذف",
    "pos.decreaseQuantity": "تقليل الكمية",
    "pos.increaseQuantity": "زيادة الكمية",
    "pos.emptyBasket": "السلة فارغة. أضف صنفًا لفتح البيع.",
    "pos.totalBeforeDiscount": "الإجمالي قبل الخصم",
    "pos.holdInvoice": "تعليق الفاتورة",
    "pos.processingSale": "جارٍ تنفيذ البيع…",
    "pos.completeSale": "إتمام البيع",
    "pos.printReceipt": "طباعة الإيصال",
    "pos.shareWhatsApp": "مشاركة واتساب",
    "pos.holdSuccess": "تم تعليق الفاتورة في الخادم مع سجل تدقيق.",
    "pos.holdFailed": "تعذر تعليق الفاتورة.",
    "pos.restoreSuccess": "تم استرجاع الفاتورة المعلقة من الخادم.",
    "pos.restoreFailed": "تعذر استرجاع الفاتورة.",
    "pos.saleComplete": "اكتملت الفاتورة بنجاح، وحالة الخادم:",
    "pos.saleFailed": "تعذر تنفيذ البيع؛ لم يتم خصم أي مخزون قبل تأكيد الخادم.",
    "pos.simulatedSuccess": "تمت محاكاة مسح الصنف للاختبار فقط؛ حُفظت الحمولة كاملة.",
    "pos.addedByCamera": "أُضيف الصنف بواسطة الكاميرا.",
    "pos.addedByBarcode": "أُضيف الصنف بواسطة الباركود.",
    "pos.searchingPayload": "جارٍ البحث عن الحمولة الكاملة في مخزون الفرع…",
    "pos.cameraHttps": "يلزم فتح النظام عبر HTTPS لاستخدام الكاميرا. استخدم قارئ USB أو الإدخال اليدوي بدلًا من ذلك.",
    "pos.cameraUnsupported": "هذا المتصفح لا يدعم قراءة الباركود بالكاميرا. استخدم قارئ USB أو الإدخال اليدوي أو المحاكاة.",
    "pos.cameraPermission": "اسمح بالوصول إلى الكاميرا عند ظهور رسالة المتصفح. لا يتم حفظ الصور أو إطارات الفيديو.",
    "pos.cameraAim": "وجّه الكاميرا إلى الباركود. ستنتقل الحمولة الكاملة إلى البحث دون تخزين الصورة.",
    "pos.cameraSuccess": "تمت القراءة بنجاح؛ يمكنك متابعة السلة أو استخدام البديل عند الحاجة.",
    "pos.cameraFailed": "تعذرت القراءة من الكاميرا. استخدم قارئ USB أو الإدخال اليدوي أو المحاكاة.",
    "pos.cameraDenied": "لم يتم السماح بالكاميرا أو حدث خطأ في تشغيلها. استخدم قارئ USB أو الإدخال اليدوي أو المحاكاة.",
    "pos.replaceBasket": "السلة الحالية ستُستبدل بالفاتورة المعلقة. هل تريد المتابعة؟",
    "pos.printWindowFailed": "تعذر فتح نافذة الطباعة؛ اسمح بالنوافذ المنبثقة ثم أعد المحاولة.",
    "pos.receiptTitle": "إيصال بيع",
    "pos.saleNumber": "رقم العملية",
    "pos.receiptIssued": "تم الإصدار محليًا بعد تأكيد الخادم.",
    "branchAnalytics.selectBranch": "اختر فرعًا مصادقًا عليه لعرض مؤشرات المبيعات والتنبيهات.",
    "branchAnalytics.loading": "جارٍ تحميل مؤشرات الفرع…",
    "branchAnalytics.loadFailed": "تعذر تحميل التحليلات. لم يتم تنفيذ أي عملية حساسة.",
    "branchAnalytics.retry": "إعادة المحاولة",
    "branchAnalytics.title": "لوحة الفرع المباشرة",
    "branchAnalytics.refreshEvery": "تحديث كل 30 ثانية",
    "branchAnalytics.scopeDetail": "بيانات مقيدة بالمؤسسة والفرع والاختصاص النشطين.",
    "branchAnalytics.refreshNow": "تحديث الآن",
    "branchAnalytics.live": "مباشر",
    "branchAnalytics.totalSales": "إجمالي المبيعات",
    "branchAnalytics.invoiceCount": "عدد الفواتير",
    "branchAnalytics.inventoryAlerts": "تنبيهات المخزون",
    "branchAnalytics.trackedItems": "أصناف متتبعة",
    "branchAnalytics.days": "أيام",
    "branchAnalytics.average": "متوسط",
    "branchAnalytics.critical": "حرجة",
    "branchAnalytics.currentBranch": "ضمن الفرع الحالي",
    "branchAnalytics.salesTrend": "اتجاه المبيعات",
    "branchAnalytics.dailyTotal": "الإجمالي اليومي للفترة المختارة",
    "branchAnalytics.noCompletedSales": "لا توجد مبيعات مكتملة في الفترة.",
    "branchAnalytics.paymentMix": "مزيج الدفع",
    "branchAnalytics.invoices": "فواتير",
    "branchAnalytics.noPaymentMovements": "لا توجد حركات دفع مكتملة.",
    "branchAnalytics.inventoryTitle": "تنبيهات المخزون",
    "branchAnalytics.inventoryDetail": "الأصناف التي تحتاج متابعة بشرية قبل الشراء أو الصرف.",
    "branchAnalytics.sku": "رمز الصنف",
    "branchAnalytics.balance": "الرصيد",
    "branchAnalytics.reorder": "إعادة الطلب",
    "branchAnalytics.expiry": "الانتهاء",
    "branchAnalytics.expired": "منتهٍ",
    "branchAnalytics.day": "يوم",
    "branchAnalytics.noCriticalAlerts": "لا توجد تنبيهات حرجة حاليًا.",
    "branchAnalytics.severityCritical": "حرج",
    "branchAnalytics.severityWarning": "تحذير",
    "branchAnalytics.paymentCash": "نقدي",
    "branchAnalytics.paymentMeeza": "ميزة",
    "branchAnalytics.paymentInstapay": "إنستا باي",
    "branchAnalytics.paymentInsurance": "تأمين",
    "home.module.overview": "نظرة عامة",
    "home.module.pos": "نقطة البيع",
    "home.module.inventory": "المخزون وFEFO",
    "home.module.supplyChain": "سلاسل الإمداد والتنبؤ",
    "home.module.prescriptions": "الوصفات الذكية",
    "home.module.insurance": "التأمين والمطالبات",
    "home.module.egyptHealthcare": "المستشفيات والتأمين المصري",
    "home.module.compliance": "الامتثال الإقليمي",
    "home.module.compounding": "التحضير الصيدلي",
    "home.module.finance": "المالية والتقارير",
    "home.module.promotions": "العروض الترويجية",
    "home.module.people": "الموظفون والفروع",
    "home.module.secondaryModules": "CRM وHR والخدمة",
    "home.module.customerCare": "خدمة العملاء",
    "home.module.operations": "مركز العمليات",
    "home.module.callCentre": "مركز الاتصال",
    "home.module.catalog": "كتالوج الأصناف",
    "home.module.icd10": "بحث التشخيص المرجعي",
    "home.module.hardware": "إعداد الأجهزة والمحاكاة",
    "home.module.security": "إعدادات الحماية والمصادقة",
    "home.module.connectors": "مركز الموصلات والاعتمادات",
    "home.module.aiGovernance": "الذكاء الاصطناعي والمراقبة",
    "home.module.aiInsights": "تحليلات المشتريات والقرار",
    "home.module.antiFraud": "النزاهة ومكافحة الاحتيال",
    "home.module.assistant": "المساعد ومركز الدعم",
    "home.module.backup": "النسخ الاحتياطي والاستعادة",
    "home.module.policyKnowledge": "قاعدة معرفة سياسات النظام",
    "home.group.start": "البداية",
    "home.group.work": "العمل اليومي",
    "home.group.business": "الإدارة والتقارير",
    "home.group.control": "الامتثال والحماية",
    "home.group.other": "أخرى",
    "home.openWorkspace": "فتح مساحة العمل",
    "home.openWorkspaceDetail": "انتقل إلى مساحة العمل المعتمدة ضمن نطاقك المصرح به.",
    "home.nextStep": "اختر الإجراء المطلوب من مساحة العمل.",
    "home.loadingSession": "جارٍ التحقق من جلسة الدخول…",
    "home.brandName": "ميدورا | منظومة الرعاية الصحية المتكاملة",
    "home.offlineScopeConflict": "تعارض أو تغير في نطاق السجل؛ يلزم مراجعة يدوية.",
    "home.footerBrand": "© 2026 ميدورا | منظومة MEDORA للرعاية الصحية المتكاملة",
    "home.footerProvenance": "سجل منشأ وملكية محفوظ · استخدام مصرح فقط",
    "home.footerProvenanceTitle": "سجل منشأ معلن من المالك؛ يلزم مراجعة قانونية متخصصة للتسجيل والترخيص والتنفيذ.",
    "home.mainMenu": "القائمة الرئيسية",
    "home.workspace": "مساحة العمل",
    "home.authenticatedUser": "المستخدم المصادق",
    "home.noRole": "دون دور",
    "home.organizationAccount": "حساب مؤسسي",
    "home.logout": "تسجيل الخروج",
    "home.logoutFailed": "تعذر إنهاء الجلسة. حاول مرة أخرى.",
    "home.role": "الدور",
    "home.loginRequired": "الوضع العام: تسجيل الدخول مطلوب",
    "home.systemModules": "وحدات النظام",
    "home.actionsFor": "إجراءات",
    "home.institutionalProtection": "حماية مؤسسية",
    "home.protectionDetail": "صلاحيات الخادم، سجل تدقيق، وقواعد FEFO مركزية للعمليات الحساسة.",
    "home.closeMenu": "إغلاق القائمة",
    "home.breadcrumbHome": "الرئيسية",
    "home.searchPlaceholder": "ابحث عن وحدة أو إجراء… (Ctrl+K)",
    "home.smartSearch": "البحث الذكي في الوحدات",
    "home.results": "نتائج",
    "home.noResults": "لا توجد نتائج",
    "home.selectBranch": "اختر الفرع",
    "home.online": "متصل",
    "home.limitedMode": "وضع محدود: مسودات غير منظمة فقط",
    "home.shortcuts": "دليل الاختصارات",
    "home.notifications": "الإشعارات",
    "home.close": "إغلاق",
    "home.notificationsLogin": "الإشعارات التشغيلية تظهر بعد تسجيل الدخول.",
    "home.loadingNotifications": "جارٍ تحميل الإشعارات…",
    "home.noNotifications": "لا توجد إشعارات جديدة.",
    "home.user": "مستخدم",
    "home.login": "تسجيل الدخول",
    "home.currentScope": "النطاق الحالي:",
    "home.branchUnspecified": "فرع غير محدد",
    "home.productionData": "بيانات إنتاجية",
    "home.switching": "جارٍ التبديل…",
    "home.loadingBranch": "جارٍ تحميل بيانات الفرع…",
    "home.quickStart": "ابدأ بسرعة",
    "home.quickStartDetail": "أكثر الإجراءات استخدامًا لدورك، بدون البحث في القائمة.",
    "home.moreQuickActions": "إظهار الإجراءات الإضافية",
    "home.moreQuickActionsDetail": "كل اختصارات الدور تبقى متاحة",
    "home.moreWorkflowActions": "إظهار خطوات إضافية",
    "home.moreWorkflowActionsDetail": "كل إجراءات مساحة العمل تبقى متاحة",
    "home.assistantPrimaryTitle": "المساعد الرقمي — جاهز للعمل",
    "home.assistantPrimaryDetail": "اسأل عن الإجراء التالي، استخدم الكتابة الذكية، أو افتح تذكرة دعم. يظل تنفيذ أي قرار حساس خاضعاً للمراجعة البشرية.",
    "home.openAssistant": "فتح المساعد",
    "home.whatNext": "ماذا تريد أن تفعل الآن؟",
    "home.workspaceDetail": "اختر إجراءً واحدًا لفتح مساحة {module}؛ ستبقى الصلاحيات والعزل والتحقق الخادمي كما هي.",
    "home.loadingWorkspace": "جارٍ تحميل مساحة العمل…",
    "home.workspaceLoadFailed": "تعذر تحميل مساحة العمل الآن. أعد المحاولة أو اختر وحدة أخرى، ولن يتم تنفيذ أي عملية حساسة أثناء فشل التحميل.",
    "home.reloadWorkspace": "إعادة تحميل الواجهة",
    "home.workspaceScopeLoadFailed": "تعذر التحقق من نطاق المؤسسة المصرح به الآن. أعد المحاولة؛ لن يتم فتح أي وحدة تشغيلية قبل اكتمال النطاق.",
    "home.workspaceScopeRequired": "لا يتوفر نطاق مؤسسة/فرع/اختصاص مكتمل لهذا الحساب الآن. لا ينشئ النظام نطاقاً افتراضياً أو يمنح وصولاً تلقائياً.",
    "home.retryScope": "إعادة محاولة التحقق من النطاق",
    "home.loadingNdaScope": "جارٍ التحقق من اتفاقية الوصول الحالية قبل تحميل نطاق الفرع…",
    "home.ndaScopeLoadFailed": "تعذر التحقق من اتفاقية الوصول الحالية. لن يتم تحميل نطاق الفرع أو أي وحدة تشغيلية قبل نجاح التحقق.",
    "home.workspaceAgreementRequired": "يلزم قبول اتفاقية الوصول الحالية قبل تحميل نطاق المؤسسة أو الفرع. لا ينشئ النظام نطاقاً افتراضياً ولا يمنح وصولاً تلقائياً.",
    "home.loadingBranchScope": "جارٍ تحميل نطاق الفرع والاختصاص المصرح به…",
    "home.branchScopeLoadFailed": "تعذر تحميل نطاق الفرع والاختصاص المصرح به. أعد المحاولة؛ لن يتم فتح أي وحدة تشغيلية قبل اكتمال النطاق.",
    "home.branchScopeRequired": "لا يتوفر فرع واختصاص قانوني مكتملان لهذا الحساب ضمن المؤسسة المختارة. لا ينشئ النظام نطاقاً افتراضياً أو يمنح وصولاً تلقائياً.",
    "home.operationsCenter": "مركز عمل",
    "home.directActions": "إجراءات مباشرة",
    "home.openArea": "فتح المساحة",
    "home.today": "اليوم",
    "home.metric.sales": "مبيعات اليوم",
    "home.metric.salesHint": "تظهر بعد ربط قاعدة البيانات",
    "home.metric.inventory": "قيمة المخزون",
    "home.metric.inventoryHint": "بانتظار بيانات الفروع",
    "home.metric.claims": "مطالبات معلقة",
    "home.metric.claimsHint": "حالة مباشرة من النظام",
    "home.metric.alerts": "تنبيهات حرجة",
    "home.metric.alertsHint": "فحص يومي مجدول",
    "home.shortcutsTitle": "الاختصارات الأساسية",
    "home.shortcutsDetail": "تعمل داخل التطبيق فقط، وتتوقف تلقائياً أثناء الكتابة في الحقول.",
    "home.organizationWorkspace": "مساحة المؤسسة",
    "home.organizationDetail": "يعرض هذا النطاق المؤسسات المرتبطة بحسابك فقط. اختيار النطاق لا يمنح صلاحيات إضافية.",
    "home.institutionalIsolation": "عزل مؤسسي",
    "home.loadingOrganizations": "جارٍ تحميل المؤسسات المصرح بها…",
    "home.selectOrganization": "اختر المؤسسة",
    "home.serverEnforced": "الصلاحية خادمية",
    "home.noOrganizationScope": "لا توجد مؤسسة نشطة مرتبطة بهذا الحساب حتى الآن. لا يتم إنشاء نطاق افتراضي أو منح وصول تلقائي.",
    "home.branch": "الفرع",
    "home.jurisdiction": "الاختصاص",
    "home.notSpecified": "غير محدد",
    "home.serverApproved": "معتمد خادمياً",
    "home.operationsStart": "ابدأ من الوحدة المناسبة لإدارة دورة العمل.",
    "home.readyToConfigure": "جاهز للتهيئة",
    "home.posSummary": "صرف جزئي، خصم MOH، إيصال ETA",
    "home.inventorySummary": "FEFO، التشغيلات، الصلاحيات",
    "home.prescriptionSummary": "رفع ومراجعة الوصفة بالرؤية",
    "home.transferSummary": "تسوية المخزون بين المواقع",
    "home.systemStatus": "حالة المنظومة",
    "home.systemStatusDetail": "مراقبة الخدمات الأساسية",
    "home.authPermissions": "المصادقة والصلاحيات",
    "home.protected": "محمية",
    "home.fefoRules": "قواعد المخزون FEFO",
    "home.enabled": "مفعلة",
    "home.scheduledAlerts": "التنبيهات المجدولة",
    "home.awaitingPublication": "بانتظار النشر",
    "home.multibranchAudit": "متعدد الفروع · عزل حسب الدولة · سجل تدقيق",
    "home.recentActivity": "آخر النشاطات",
    "home.recentActivityDetail": "ستظهر الأحداث بعد تسجيل الدخول وربط الفروع.",
    "home.auditTrail": "سجل التدقيق",
    "home.noEvents": "لا توجد أحداث معروضة بعد",
    "home.noEventsDetail": "لن يتم إنشاء بيانات تجريبية. سيعرض النظام السجلات الفعلية فقط بعد تهيئة الفروع والمستخدمين.",
    "home.nonOverrideRules": "قواعد لا يمكن تجاوزها",
    "home.discountRule": "الخصم الأقصى ٧٪ وفق محرك MOH على الخادم.",
    "home.fefoRule": "الصرف من أقرب تاريخ انتهاء عبر FEFO.",
    "home.prescriptionRule": "الوصفة الذكية تحتاج مراجعة صيدلي قبل الصرف.",
    "install.bannerAria": "تثبيت اختصار MEDORA",
    "install.title": "ثبّت MEDORA على جهازك",
    "install.detail": "أضف اختصاراً سريعاً للشاشة الرئيسية أو سطح المكتب وافتح النظام كتطبيق مستقل.",
    "install.dismiss": "إخفاء إشعار التثبيت",
    "install.now": "تثبيت الآن",
    "install.showMethod": "عرض طريقة التثبيت",
    "install.deviceInstructions": "تعليمات الجهاز",
    "install.ios": "من Safari اضغط مشاركة، ثم اختر إضافة إلى الشاشة الرئيسية، ثم اضغط إضافة.",
    "install.android": "من Chrome اضغط ⋮ ثم تثبيت التطبيق أو إضافة إلى الشاشة الرئيسية.",
    "install.desktop": "من قائمة المتصفح اختر تثبيت MEDORA أو إنشاء اختصار، ثم أكد الإضافة إلى سطح المكتب.",
    "install.other": "افتح قائمة المتصفح وابحث عن تثبيت التطبيق أو إضافة إلى الشاشة الرئيسية.",
    "install.notice": "تظهر نافذة التثبيت الأصلية عندما يسمح بها المتصفح، وتظل هذه التعليمات متاحة عند عدم دعمها.",
    "home.noOrganization": "لا توجد مؤسسة نشطة مرتبطة بهذا الحساب حتى الآن. لا يتم إنشاء نطاق افتراضي أو منح وصول تلقائي.",
    "offline.connectionStatus": "حالة الاتصال والمزامنة",
    "offline.online": "متصل بالإنترنت",
    "offline.offline": "لا يوجد اتصال",
    "offline.onlineBadge": "متصل",
    "offline.offlineBadge": "دون اتصال",
    "offline.synced": "المسودات المحلية متزامنة ولا توجد عناصر معلقة.",
    "offline.pending": "الاتصال متاح؛ المسودات تنتظر تحققاً خادمياً قبل اعتمادها.",
    "offline.limited": "تعمل المساحة المحدودة محلياً؛ العمليات المنظمة لا تُعتمد دون اتصال.",
    "offline.refresh": "تحديث الحالة",
    "offline.progress": "تقدم المزامنة",
    "offline.localPending": "معلق محلياً",
    "offline.blocked": "تعارض/فشل",
    "offline.serverPending": "خادمي",
    "offline.lastCheck": "آخر تحقق",
    "offline.notYet": "لم يتم بعد",
    "offline.conflictReview": "سجل التعارضات",
    "offline.manualReview": "يلزم مراجعة يدوية",
    "offline.retry": "إعادة المحاولة",
    "offline.approvalGuard": "لا يتم اعتماد أي عملية مالية أو وصفة أو فاتورة من هذا المسار دون تحقق خادمي وصلاحيات مناسبة.",
    "integration.governmentTitle": "التكاملات الحكومية مغلقة مؤقتاً",
    "integration.governmentShort": "الربط الرسمي مع الجهات الحكومية متوقف بأمان حتى توفير الاعتمادات والمواصفات وبيئة الاختبار.",
    "integration.governmentDetails": "الوحدات الداخلية ومسودات العمل متاحة وفق صلاحياتك، لكن لا يتم إرسال مطالبات أو فواتير أو بيانات إلى UPA أو EDA أو ETA أو أي جهة حكومية خارجية قبل اعتماد الموصل رسمياً واختباره وقبول نتائجه.",
    "integration.governmentLabel": "حكومي · بانتظار الاعتماد",
    "integration.insuranceTitle": "تكامل التأمين مغلق مؤقتاً",
    "integration.insuranceShort": "التحقق الشبكي والإرسال إلى شركات التأمين متوقفان بأمان حتى اعتماد موصل مؤسسي.",
    "integration.insuranceDetails": "يمكن حفظ المسودات الداخلية القابلة للتدقيق ضمن النطاق المصرح به، بينما تبقى الأهلية والموافقات والمطالبات الخارجية غير مرسلة حتى توفير عقد API، الاعتمادات، بيئة الاختبار، ومتطلبات القبول.",
    "integration.insuranceLabel": "تأمين · بانتظار الاعتماد",
    "integration.statusDetails": "تفاصيل حالة {title}",
    "integration.noAutoExternal": "لن يتم تفعيل الإرسال الخارجي أو تجاوز الحماية تلقائياً. راجع مسؤول النظام عند توفير الاعتماد الرسمي.",
    "integration.externalStatus": "حالة التكاملات الخارجية",
  },
  en: {
    pharmacy: "Pharmacy",
    prescription: "Prescription",
    invoice: "Invoice",
    branch: "Branch",
    country: "Country",
    "pos.scopeRequired": "Select an approved branch and legal jurisdiction",
    "pos.scopeRequiredDetail": "A regulated invoice cannot be opened and inventory cannot be searched until the server confirms the branch and jurisdiction scope.",
    "pos.openSale": "Open sale invoice",
    "pos.openSaleDescription": "Search by name or use a USB scanner or Data Matrix. The raw payload is retained before validation.",
    "pos.currentBranch": "Current branch · protected scope",
    "pos.saleTools": "Sale tools",
    "pos.cameraScan": "Scan with camera",
    "pos.simulatedScan": "Simulate scan",
    "pos.heldInvoices": "Held",
    "pos.cameraTitle": "Camera scanning",
    "pos.closeCamera": "Close camera scanner",
    "pos.cameraPrivacy": "Your browser will ask for camera permission. Images and video frames are not stored; only the scanned payload is sent to the scoped stock search.",
    "pos.preparingCamera": "Preparing camera…",
    "pos.manualEntry": "Use manual entry",
    "pos.openSimulation": "Open simulation",
    "pos.usbScanner": "USB scanner",
    "pos.simulatedScanner": "Test barcode scanner",
    "pos.simulatedScannerDetail": "For testing only. It does not use the camera or change data boundaries. Select an item to simulate its barcode scan.",
    "pos.searchOrWait": "Search first or wait for available items to load.",
    "pos.heldOnDevice": "Held invoices on this device",
    "pos.items": "items",
    "pos.restore": "Restore",
    "pos.noHeldInvoices": "There are no held invoices.",
    "pos.availableItems": "Available items",
    "pos.searchPlaceholder": "Scan a barcode or search by name / SKU",
    "pos.searchAria": "POS barcode or item search",
    "pos.addBarcode": "Add barcode",
    "pos.addByCode": "Add by code",
    "pos.lastScan": "Last scan",
    "pos.unknown": "Unknown",
    "pos.simulated": "Simulated",
    "pos.device": "Device",
    "pos.loadingStock": "Loading branch inventory…",
    "pos.stockLoadFailed": "Inventory could not be loaded in the current scope.",
    "pos.batch": "Batch",
    "pos.available": "Available",
    "pos.expiry": "Expires",
    "pos.add": "Add",
    "pos.noItems": "No verified, available items match this search.",
    "pos.basketAndInvoice": "Basket and invoice",
    "pos.invoiceNumber": "Invoice number",
    "pos.paymentMethod": "Payment method",
    "pos.cash": "Cash",
    "pos.meeza": "Meeza",
    "pos.instapay": "InstaPay",
    "pos.insurance": "Insurance",
    "pos.remove": "Remove",
    "pos.decreaseQuantity": "Decrease quantity",
    "pos.increaseQuantity": "Increase quantity",
    "pos.emptyBasket": "Your basket is empty. Add an item to start a sale.",
    "pos.totalBeforeDiscount": "Total before discount",
    "pos.holdInvoice": "Hold invoice",
    "pos.processingSale": "Completing sale…",
    "pos.completeSale": "Complete sale",
    "pos.printReceipt": "Print receipt",
    "pos.shareWhatsApp": "Share on WhatsApp",
    "pos.holdSuccess": "The invoice was held on the server with an audit record.",
    "pos.holdFailed": "The invoice could not be held.",
    "pos.restoreSuccess": "The held invoice was restored from the server.",
    "pos.restoreFailed": "The held invoice could not be restored.",
    "pos.saleComplete": "The invoice was completed successfully. Server status:",
    "pos.saleFailed": "The sale could not be completed; no inventory was deducted before server confirmation.",
    "pos.simulatedSuccess": "The item scan was simulated for testing only; the full payload was retained.",
    "pos.addedByCamera": "The item was added using the camera.",
    "pos.addedByBarcode": "The item was added using the barcode.",
    "pos.searchingPayload": "Searching the full payload in branch inventory…",
    "pos.cameraHttps": "Open the system over HTTPS to use the camera. Use a USB scanner or manual entry instead.",
    "pos.cameraUnsupported": "This browser does not support camera barcode scanning. Use a USB scanner, manual entry, or simulation.",
    "pos.cameraPermission": "Allow camera access in the browser prompt. Images and video frames are not stored.",
    "pos.cameraAim": "Point the camera at the barcode. The full payload will be searched without storing an image.",
    "pos.cameraSuccess": "Scan completed. You can continue with the basket or choose an alternative.",
    "pos.cameraFailed": "The camera could not read the code. Use a USB scanner, manual entry, or simulation.",
    "pos.cameraDenied": "Camera permission was not granted or the camera could not start. Use a USB scanner, manual entry, or simulation.",
    "pos.replaceBasket": "The current basket will be replaced with the held invoice. Continue?",
    "pos.printWindowFailed": "The print window could not be opened. Allow pop-ups and try again.",
    "pos.receiptTitle": "Sales receipt",
    "pos.saleNumber": "Transaction number",
    "pos.receiptIssued": "Issued locally after server confirmation.",
    "branchAnalytics.selectBranch": "Select an authorized branch to view sales metrics and alerts.",
    "branchAnalytics.loading": "Loading branch metrics…",
    "branchAnalytics.loadFailed": "Analytics could not be loaded. No sensitive action was performed.",
    "branchAnalytics.retry": "Retry",
    "branchAnalytics.title": "Live branch dashboard",
    "branchAnalytics.refreshEvery": "Refreshes every 30 seconds",
    "branchAnalytics.scopeDetail": "Data is constrained to the active organization, branch, and jurisdiction.",
    "branchAnalytics.refreshNow": "Refresh now",
    "branchAnalytics.live": "Live",
    "branchAnalytics.totalSales": "Total sales",
    "branchAnalytics.invoiceCount": "Invoices",
    "branchAnalytics.inventoryAlerts": "Inventory alerts",
    "branchAnalytics.trackedItems": "Tracked items",
    "branchAnalytics.days": "days",
    "branchAnalytics.average": "Average",
    "branchAnalytics.critical": "critical",
    "branchAnalytics.currentBranch": "in the current branch",
    "branchAnalytics.salesTrend": "Sales trend",
    "branchAnalytics.dailyTotal": "Daily total for the selected period",
    "branchAnalytics.noCompletedSales": "No completed sales in this period.",
    "branchAnalytics.paymentMix": "Payment mix",
    "branchAnalytics.invoices": "invoices",
    "branchAnalytics.noPaymentMovements": "No completed payment movements.",
    "branchAnalytics.inventoryTitle": "Inventory alerts",
    "branchAnalytics.inventoryDetail": "Items requiring human follow-up before purchase or issue.",
    "branchAnalytics.sku": "SKU",
    "branchAnalytics.balance": "On hand",
    "branchAnalytics.reorder": "Reorder point",
    "branchAnalytics.expiry": "Expiry",
    "branchAnalytics.expired": "Expired",
    "branchAnalytics.day": "day",
    "branchAnalytics.noCriticalAlerts": "There are no critical alerts at present.",
    "branchAnalytics.severityCritical": "Critical",
    "branchAnalytics.severityWarning": "Warning",
    "branchAnalytics.paymentCash": "Cash",
    "branchAnalytics.paymentMeeza": "Meeza",
    "branchAnalytics.paymentInstapay": "InstaPay",
    "branchAnalytics.paymentInsurance": "Insurance",
    "home.module.overview": "Overview",
    "home.module.pos": "Point of Sale",
    "home.module.inventory": "Inventory & FEFO",
    "home.module.supplyChain": "Supply Chain & Forecasting",
    "home.module.prescriptions": "Smart Prescriptions",
    "home.module.insurance": "Insurance & Claims",
    "home.module.egyptHealthcare": "Egypt Healthcare & Insurance",
    "home.module.compliance": "Regional Compliance",
    "home.module.compounding": "Pharmaceutical Compounding",
    "home.module.finance": "Finance & Reports",
    "home.module.promotions": "Promotions",
    "home.module.people": "People & Branches",
    "home.module.secondaryModules": "CRM, HR & Service",
    "home.module.customerCare": "Customer Care",
    "home.module.operations": "Operations Center",
    "home.module.callCentre": "Call Center",
    "home.module.catalog": "Product Catalog",
    "home.module.icd10": "Clinical Reference Search",
    "home.module.hardware": "Hardware & Simulation",
    "home.module.security": "Security & Authentication",
    "home.module.connectors": "Connectors & Accreditation",
    "home.module.aiGovernance": "AI & Monitoring",
    "home.module.aiInsights": "Purchasing & Decision Insights",
    "home.module.antiFraud": "Integrity & Anti-Fraud",
    "home.module.assistant": "Assistant & Support Center",
    "home.module.backup": "Backup & Restore",
    "home.module.policyKnowledge": "Policy Knowledge Base",
    "home.group.start": "Start",
    "home.group.work": "Daily work",
    "home.group.business": "Management & reports",
    "home.group.control": "Compliance & protection",
    "home.group.other": "Other",
    "home.openWorkspace": "Open workspace",
    "home.openWorkspaceDetail": "Go to the authorized workspace within your permitted scope.",
    "home.nextStep": "Choose the action you need from the workspace.",
    "home.loadingSession": "Checking your session…",
    "home.brandName": "MEDORA | Integrated Health Care Eco System",
    "home.offlineScopeConflict": "The record scope changed or conflicted; manual review is required.",
    "home.footerBrand": "© 2026 MEDORA | Integrated Health Care Eco System",
    "home.footerProvenance": "Provenance and ownership record retained · Authorized use only",
    "home.footerProvenanceTitle": "Owner-declared provenance record; professional legal review is required for registration, licensing, and enforcement.",
    "home.mainMenu": "Main menu",
    "home.workspace": "Workspace",
    "home.authenticatedUser": "Authenticated user",
    "home.noRole": "No role",
    "home.organizationAccount": "Organization account",
    "home.logout": "Sign out",
    "home.logoutFailed": "The session could not be ended. Please try again.",
    "home.role": "Role",
    "home.loginRequired": "Public mode: sign-in required",
    "home.systemModules": "System modules",
    "home.actionsFor": "Actions for",
    "home.institutionalProtection": "Institutional protection",
    "home.protectionDetail": "Server permissions, an audit trail, and centralized FEFO rules protect sensitive operations.",
    "home.closeMenu": "Close menu",
    "home.breadcrumbHome": "Home",
    "home.searchPlaceholder": "Search for a module or action… (Ctrl+K)",
    "home.smartSearch": "Smart module search",
    "home.results": "results",
    "home.noResults": "No results",
    "home.selectBranch": "Select branch",
    "home.online": "Online",
    "home.limitedMode": "Limited mode: unregulated drafts only",
    "home.shortcuts": "Keyboard shortcuts",
    "home.notifications": "Notifications",
    "home.close": "Close",
    "home.notificationsLogin": "Operational notifications appear after you sign in.",
    "home.loadingNotifications": "Loading notifications…",
    "home.noNotifications": "There are no new notifications.",
    "home.user": "User",
    "home.login": "Sign in",
    "home.currentScope": "Current scope:",
    "home.branchUnspecified": "Branch not selected",
    "home.productionData": "Production data",
    "home.switching": "Switching…",
    "home.loadingBranch": "Loading branch data…",
    "home.quickStart": "Quick start",
    "home.quickStartDetail": "Your most-used actions, without searching through the menu.",
    "home.moreQuickActions": "Show more actions",
    "home.moreQuickActionsDetail": "All role shortcuts remain available",
    "home.moreWorkflowActions": "Show more steps",
    "home.moreWorkflowActionsDetail": "All workspace actions remain available",
    "home.assistantPrimaryTitle": "Digital assistant — ready to help",
    "home.assistantPrimaryDetail": "Ask for the next step, use Smart Typing, or open a support ticket. Any sensitive decision remains subject to human review.",
    "home.openAssistant": "Open assistant",
    "home.whatNext": "What would you like to do now?",
    "home.workspaceDetail": "Choose one action to open {module}. Permissions, isolation, and server-side validation remain in place.",
    "home.loadingWorkspace": "Loading workspace…",
    "home.workspaceLoadFailed": "The workspace could not be loaded right now. Try again or select another module; no sensitive operation will run while loading has failed.",
    "home.reloadWorkspace": "Reload interface",
    "home.workspaceScopeLoadFailed": "The authorized organization scope could not be verified right now. Retry the check; no operational workspace will open before the scope is complete.",
    "home.workspaceScopeRequired": "No complete organization, branch, and jurisdiction scope is available for this account. The system does not create a default scope or grant automatic access.",
    "home.retryScope": "Retry scope check",
    "home.loadingNdaScope": "Checking the current access agreement before loading branch scope…",
    "home.ndaScopeLoadFailed": "The current access agreement could not be verified. Branch scope and operational workspaces remain unavailable until verification succeeds.",
    "home.workspaceAgreementRequired": "Acceptance of the current access agreement is required before organization or branch scope can load. The system does not create a default scope or grant automatic access.",
    "home.loadingBranchScope": "Loading the authorized branch and jurisdiction scope…",
    "home.branchScopeLoadFailed": "The authorized branch and jurisdiction scope could not be loaded. Retry the check; no operational workspace will open before the scope is complete.",
    "home.branchScopeRequired": "No complete branch and legal-jurisdiction scope is available for this account within the selected organization. The system does not create a default scope or grant automatic access.",
    "home.operationsCenter": "Work center",
    "home.directActions": "Direct actions",
    "home.openArea": "Open workspace",
    "home.today": "Today",
    "home.metric.sales": "Today's sales",
    "home.metric.salesHint": "Available after the database is connected",
    "home.metric.inventory": "Inventory value",
    "home.metric.inventoryHint": "Waiting for branch data",
    "home.metric.claims": "Pending claims",
    "home.metric.claimsHint": "Live system status",
    "home.metric.alerts": "Critical alerts",
    "home.metric.alertsHint": "Scheduled daily check",
    "home.shortcutsTitle": "Core shortcuts",
    "home.shortcutsDetail": "They work only inside the application and pause while you are typing in a field.",
    "home.organizationWorkspace": "Organization workspace",
    "home.organizationDetail": "This scope lists only organizations linked to your account. Selecting a scope never grants additional permissions.",
    "home.institutionalIsolation": "Institutional isolation",
    "home.loadingOrganizations": "Loading authorized organizations…",
    "home.selectOrganization": "Select organization",
    "home.serverEnforced": "Server-enforced",
    "home.noOrganizationScope": "No active organization is linked to this account yet. The system does not create a default scope or grant automatic access.",
    "home.branch": "Branch",
    "home.jurisdiction": "Jurisdiction",
    "home.notSpecified": "Not selected",
    "home.serverApproved": "Server-approved",
    "home.operationsStart": "Start from the module that fits the workflow you need.",
    "home.readyToConfigure": "Ready to configure",
    "home.posSummary": "Partial dispensing, MOH discount, ETA receipt",
    "home.inventorySummary": "FEFO, batches, permissions",
    "home.prescriptionSummary": "Prescription upload and vision review",
    "home.transferSummary": "Inventory reconciliation between locations",
    "home.systemStatus": "System status",
    "home.systemStatusDetail": "Monitoring essential services",
    "home.authPermissions": "Authentication and permissions",
    "home.protected": "Protected",
    "home.fefoRules": "FEFO inventory rules",
    "home.enabled": "Enabled",
    "home.scheduledAlerts": "Scheduled alerts",
    "home.awaitingPublication": "Awaiting publication",
    "home.multibranchAudit": "Multi-branch · jurisdiction isolation · audit trail",
    "home.recentActivity": "Recent activity",
    "home.recentActivityDetail": "Events will appear after you sign in and connect a branch.",
    "home.auditTrail": "Audit trail",
    "home.noEvents": "No events are displayed yet",
    "home.noEventsDetail": "No sample records are created. The system will display only real records after branches and users are configured.",
    "home.nonOverrideRules": "Non-bypassable rules",
    "home.discountRule": "The maximum discount is 7% under the server-side MOH rules engine.",
    "home.fefoRule": "Dispensing uses the nearest expiry date under FEFO.",
    "home.prescriptionRule": "Smart prescriptions require pharmacist review before dispensing.",
    "install.bannerAria": "Install the MEDORA shortcut",
    "install.title": "Install MEDORA on your device",
    "install.detail": "Add a quick shortcut to your home screen or desktop and open the system as a standalone app.",
    "install.dismiss": "Dismiss install notice",
    "install.now": "Install now",
    "install.showMethod": "Show installation steps",
    "install.deviceInstructions": "Device instructions",
    "install.ios": "In Safari, tap Share, choose Add to Home Screen, then tap Add.",
    "install.android": "In Chrome, tap ⋮, then choose Install app or Add to Home screen.",
    "install.desktop": "From your browser menu, choose Install MEDORA or Create shortcut, then confirm the desktop shortcut.",
    "install.other": "Open your browser menu and look for Install app or Add to Home screen.",
    "install.notice": "The native installation prompt appears when the browser allows it; these steps remain available when it does not.",
    "home.noOrganization": "There is no active organization linked to this account yet. The system does not create a default scope or grant automatic access.",
    "offline.connectionStatus": "Connection and synchronization status",
    "offline.online": "Connected to the internet",
    "offline.offline": "No connection",
    "offline.onlineBadge": "Online",
    "offline.offlineBadge": "Offline",
    "offline.synced": "Local drafts are synchronized and there are no pending items.",
    "offline.pending": "A connection is available; drafts are waiting for server-side validation before approval.",
    "offline.limited": "The limited workspace is operating locally. Regulated operations cannot be approved without a connection.",
    "offline.refresh": "Refresh status",
    "offline.progress": "Sync progress",
    "offline.localPending": "Local pending",
    "offline.blocked": "Conflict / failed",
    "offline.serverPending": "Server pending",
    "offline.lastCheck": "Last check",
    "offline.notYet": "Not yet",
    "offline.conflictReview": "Conflict review",
    "offline.manualReview": "Manual review required",
    "offline.retry": "Retry",
    "offline.approvalGuard": "No financial transaction, prescription, or invoice can be approved through this path without server-side validation and appropriate permissions.",
    "integration.governmentTitle": "Government integrations are temporarily closed",
    "integration.governmentShort": "Official government connectivity is safely paused until accreditation, specifications, and a test environment are available.",
    "integration.governmentDetails": "Internal workspaces and drafts remain available within your permissions, but no claims, invoices, or data are sent to UPA, EDA, ETA, or any external government entity until the connector is officially accredited, tested, and accepted.",
    "integration.governmentLabel": "Government · awaiting accreditation",
    "integration.insuranceTitle": "Insurance integration is temporarily closed",
    "integration.insuranceShort": "Network validation and submissions to insurance companies are safely paused until an organization connector is accredited.",
    "integration.insuranceDetails": "Auditable internal drafts may be saved within the permitted scope, while external eligibility, approvals, and claims remain unsent until an API agreement, credentials, test environment, and acceptance requirements are available.",
    "integration.insuranceLabel": "Insurance · awaiting accreditation",
    "integration.statusDetails": "Details for {title}",
    "integration.noAutoExternal": "External submission will not be enabled and safeguards will not be bypassed automatically. Consult the system administrator when official accreditation is available.",
    "integration.externalStatus": "External integration status",
  },
};

const countryDefaults: Record<string, { locale: string; currencyCode: string }> = {
  UNSET: { locale: "ar", currencyCode: "XXX" },
  EG: { locale: "ar-EG", currencyCode: "EGP" },
  SA: { locale: "ar-SA", currencyCode: "SAR" },
  AE: { locale: "ar-AE", currencyCode: "AED" },
};

export function normalizeLanguage(value: string | null): "ar" | "en" {
  return value === "en" ? "en" : "ar";
}

export function translateLocalization(language: string, key: string): string {
  return dictionaries[normalizeLanguage(language)]?.[key] ?? dictionaries.ar[key] ?? key;
}

export function hasScopedJurisdictionId(value: number | null | undefined): value is number {
  return typeof value === "number" && Number.isInteger(value) && value > 0;
}

const LocalizationContext = createContext<ClientLocalization | null>(null);

export function LocalizationProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [languageOverride, setLanguageOverride] = useState<"ar" | "en">(() => {
    if (typeof window === "undefined") return "ar";
    return normalizeLanguage(window.localStorage.getItem("aldo-language"));
  });
  // This authenticated-only query is intentionally the only workspace-adjacent
  // bootstrap request allowed before the agreement is accepted. Branch context
  // remains unavailable until the server confirms the exact
  // current NDA version and document hash for the signed-in user.
  const ndaStatusQuery = trpc.nda.status.useQuery(undefined, { enabled: Boolean(user), retry: false, refetchOnWindowFocus: false });
  const hasAcceptedCurrentNda = ndaStatusQuery.data?.accepted === true;
  const branchRegistry = trpc.regional.myBranchJurisdictions.useQuery(undefined, { enabled: Boolean(user) && hasAcceptedCurrentNda, retry: false, refetchOnWindowFocus: false });
  const [selectedBranchId, setSelectedBranchId] = useState<number | null>(null);
  const [branchSwitching, setBranchSwitching] = useState(false);
  const branches = useMemo(() => (branchRegistry.data ?? []).filter(item => item.branch && item.profile).map(item => ({ id: item.branch!.id, nameAr: item.branch!.nameAr, countryCode: item.profile!.countryCode })), [branchRegistry.data]);
  const isUsableProfile = (profile: { active?: number | null } | null | undefined) => profile?.active === 1;
  const confirmedBranch = branches.length ? (branchRegistry.data?.find(item => item.branch?.id === selectedBranchId && hasScopedJurisdictionId(item.assignment?.jurisdictionId) && isUsableProfile(item.profile)) ?? branchRegistry.data?.find(item => hasScopedJurisdictionId(item.assignment?.jurisdictionId) && isUsableProfile(item.profile)) ?? null) : null;
  const workspaceBootstrapStatus: WorkspaceBootstrapStatus = !user
    ? "ready"
    : ndaStatusQuery.isLoading
      ? "nda_loading"
      : ndaStatusQuery.isError
        ? "nda_error"
        : hasAcceptedCurrentNda
          ? branchRegistry.isLoading
            ? "branch_loading"
            : branchRegistry.isError
              ? "branch_error"
              : confirmedBranch
                ? "ready"
                : "branch_missing"
          : "nda_required";
  const retryWorkspaceBootstrap = async () => {
    if (workspaceBootstrapStatus === "nda_error") {
      await ndaStatusQuery.refetch();
      return;
    }
    if (workspaceBootstrapStatus === "branch_error") await branchRegistry.refetch();
  };
  const countryCode = confirmedBranch?.profile?.countryCode ?? "UNSET";
  const defaults = countryDefaults[countryCode] ?? { locale: "ar", currencyCode: "XXX" };
  const language = languageOverride;
  const displayLocale = language === "en" ? "en-US" : defaults.locale;
  const setLanguage = (nextLanguage: "ar" | "en") => {
    setLanguageOverride(nextLanguage);
    try { window.localStorage.setItem("aldo-language", nextLanguage); } catch {}
  };
  const value = useMemo<ClientLocalization>(() => ({
    countryCode,
    locale: displayLocale,
    language,
    direction: language === "ar" ? "rtl" : "ltr",
    currencyCode: defaults.currencyCode,
    calendar: "gregory",
    numberingSystem: "latn",
    t: (key) => translateLocalization(language, key),
    formatCurrency: (amount) => new Intl.NumberFormat(`${displayLocale}-u-ca-gregory-nu-latn`, { style: "currency", currency: defaults.currencyCode }).format(amount),
    setCountry: () => {
      // Legal jurisdiction is controlled by the authenticated branch registry;
      // a client-side country toggle must never change regulated behavior.
    },
    setLanguage,
    branchId: confirmedBranch?.branch?.id ?? null,
    jurisdictionId: confirmedBranch?.assignment?.jurisdictionId ?? null,
    branches,
    setBranchId: (branchId) => {
      if (branches.some(branch => branch.id === branchId) && branchId !== confirmedBranch?.branch?.id) {
        setBranchSwitching(true);
        setSelectedBranchId(branchId);
      }
    },
    branchSwitching,
    workspaceBootstrapStatus,
    retryWorkspaceBootstrap,
  }), [branchSwitching, branches, confirmedBranch, countryCode, defaults.currencyCode, displayLocale, language, languageOverride, retryWorkspaceBootstrap, workspaceBootstrapStatus]);

  useEffect(() => {
    if (!branchSwitching) return;
    const timeout = window.setTimeout(() => setBranchSwitching(false), 420);
    return () => window.clearTimeout(timeout);
  }, [branchSwitching, confirmedBranch?.branch?.id]);

  useEffect(() => {
    document.documentElement.lang = value.language;
    document.documentElement.dir = value.direction;
    document.documentElement.dataset.country = value.countryCode;
  }, [value]);

  return <LocalizationContext.Provider value={value}>{children}</LocalizationContext.Provider>;
}

export function useLocalization() {
  const value = useContext(LocalizationContext);
  if (!value) throw new Error("useLocalization must be used inside LocalizationProvider");
  return value;
}
