'use client';

import Link from 'next/link';
import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { LayoutDashboard, ShoppingBag, ShoppingCart, Package, Users, Truck, UserRoundCog, ChartNoAxesCombined, Settings, CircleHelp, Search, Bell, ChevronDown, ChevronLeft, ChevronRight, ArrowLeft, ArrowUpLeft, ArrowUpRight, Plus, Download, CalendarDays, FlaskConical, ShieldCheck, RotateCcw, X, Check, CheckCheck, Circle, MoreHorizontal, SlidersHorizontal, Wallet, ArrowDownLeft, TrendingUp, Sparkles, LogOut, Building2, Menu, LoaderCircle, Trash2, Pencil, FileText, Mail, ExternalLink, Play, CheckCircle2, type LucideIcon } from 'lucide-react';
import { sections, moduleInfo, initialRecords, defaultPreferences, type Section, type Module, type DemoRecord, type Preferences } from '@/lib/demo';
import { GoalCard, RevenueChart, type Period } from './charts';

const icons: Record<string, LucideIcon> = { LayoutDashboard, ShoppingBag, ShoppingCart, Package, Users, Truck, UserRoundCog, ChartNoAxesCombined, Settings, CircleHelp };
const fallbackRecords = initialRecords.map((r, i) => ({ ...r, id: `preview-${i}` }));
const number = (v: number) => v.toLocaleString('en-US', { maximumFractionDigits: 2 });
function Brand({ small = false }: { small?: boolean }) { return <div className={`brand ${small ? 'brand-small' : ''}`}><span className="brand-symbol"><i/><i/><i/></span><div><b>مدار<span>.</span></b>{!small && <p>إدارة أعمالك، بوضوح</p>}</div></div>; }
function Modal({ title, children, close, wide = false }: { title: string; children: ReactNode; close: () => void; wide?: boolean }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const previous = document.activeElement as HTMLElement;
    ref.current?.focus();
    const oldOverflow = document.body.style.overflow; document.body.style.overflow = 'hidden';
    function key(e: KeyboardEvent) {
      if (e.key === 'Escape') close();
      if (e.key === 'Tab') {
        const nodes = ref.current?.querySelectorAll<HTMLElement>('button, input, select, textarea, a[href], [tabindex="0"]');
        if (!nodes?.length) return;
        const first = nodes[0], last = nodes[nodes.length - 1];
        if (e.shiftKey && (document.activeElement === first || document.activeElement === ref.current)) { e.preventDefault(); last.focus(); }
        else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
      }
    }
    document.addEventListener('keydown', key);
    return () => { document.removeEventListener('keydown', key); document.body.style.overflow = oldOverflow; previous?.focus(); };
  }, [close]);
  return <div className="modal-backdrop" onClick={e => { if (e.target === e.currentTarget) close(); }}><div className={`modal ${wide ? 'modal-wide' : ''}`} ref={ref} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1}><div className="modal-title"><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="إغلاق"><X size={20}/></button></div>{children}</div></div>;
}

export default function Workspace({ section }: { section: Section }) {
  const [records, setRecords] = useState<DemoRecord[]>(fallbackRecords);
  const [preferences, setPreferences] = useState<Preferences>(defaultPreferences);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [loadError, setLoadError] = useState('');
  const [toast, setToast] = useState('');
  const [modal, setModal] = useState<'record' | 'reset' | 'tour' | 'search' | null>(null);
  const [editRecord, setEditRecord] = useState<DemoRecord | null>(null);
  const [formModule, setFormModule] = useState<Module>('sales');
  const [formError, setFormError] = useState('');
  const [query, setQuery] = useState('');
  const [globalQuery, setGlobalQuery] = useState('');
  const [status, setStatus] = useState('all');
  const [period, setPeriod] = useState<Period>('month');
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<string[]>([]);
  const [filterOpen, setFilterOpen] = useState(false);
  const [popup, setPopup] = useState<'notifications' | 'profile' | 'company' | 'date' | null>(null);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [notificationsRead, setNotificationsRead] = useState(false);
  const [faq, setFaq] = useState<number | null>(0);
  const closeModal = useCallback(() => { setModal(null); setFormError(''); }, []);
  const activeLabel = sections.find(s => s.id === section)?.label || 'نظرة عامة';
  const isModule = Object.hasOwn(moduleInfo, section);
  const currentModule: Module = isModule ? section as Module : 'sales';
  const currency = preferences.currency === 'SAR' ? 'ر.س' : preferences.currency === 'AED' ? 'د.إ' : '$';

  const load = useCallback(async () => {
    try {
      const res = await fetch('/api/demo', { cache: 'no-store' });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setRecords(data.records); setPreferences(data.preferences); setLoadError('');
    } catch (e) { setLoadError(e instanceof Error ? e.message : 'تعذر الاتصال بالخادم'); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 4200); return () => clearTimeout(timer); } }, [toast]);
  useEffect(() => { const handler = (e: KeyboardEvent) => { if ((e.ctrlKey || e.metaKey) && e.key === 'k') { e.preventDefault(); setModal('search'); } if (e.key === 'Escape') { setPopup(null); setMobileOpen(false); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);
  async function mutate(body: Record<string, unknown>, message: string) {
    setBusy(true); setFormError('');
    try {
      const res = await fetch('/api/demo', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
      const data = await res.json(); if (!res.ok) throw new Error(data.error || 'تعذر تنفيذ الإجراء');
      await load(); setToast(message); return true;
    } catch (e) { const msg = e instanceof Error ? e.message : 'حدث خطأ'; setFormError(msg); setToast(msg); return false; }
    finally { setBusy(false); }
  }
  function openRecord(module: Module, record: DemoRecord | null = null) { if (loading || loadError) return; setFormModule(module); setEditRecord(record); setFormError(''); setModal('record'); }
  async function saveRecord(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const values = new FormData(e.currentTarget);
    const success = await mutate({ action: editRecord ? 'update' : 'create', id: editRecord?.id, module: formModule, name: values.get('name'), amount: Number(values.get('amount')), detail: values.get('detail'), status: values.get('status'), date: values.get('date') }, editRecord ? 'تم حفظ التعديلات في مساحتك التجريبية' : `تمت إضافة ${moduleInfo[formModule].singular} بنجاح`);
    if (success) closeModal();
  }
  function exportData(data = records.filter(r => r.module === currentModule)) {
    const safe = (v: unknown) => { let text = String(v); if (/^[=+@\-\t\r]/.test(text)) text = `'${text}`; return `"${text.replaceAll('"', '""')}"`; };
    const csv = '\uFEFF' + [['المرجع', 'الاسم', 'المبلغ', 'الحالة', 'التاريخ', 'التفاصيل'], ...data.map(r => [r.reference, r.name, r.amount, r.status, r.date, r.detail])].map(row => row.map(safe).join(',')).join('\r\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); const a = document.createElement('a'); a.href = url; a.download = `madar-${section}-demo.csv`; a.click(); URL.revokeObjectURL(url); setToast('تم تصدير البيانات التجريبية بنجاح');
  }
  const sales = records.filter(r => r.module === 'sales');
  const salesDelta = sales.reduce((a, r) => a + (r.status === 'ملغاة' ? 0 : r.amount), 0) - initialRecords.filter(r => r.module === 'sales').reduce((a, r) => a + (r.status === 'ملغاة' ? 0 : r.amount), 0);
  const totalSales = 124850 + salesDelta;
  const purchasesDelta = records.filter(r => r.module === 'purchases' && r.status !== 'ملغاة').reduce((a, r) => a + r.amount, 0) - 19400;
  const kpis: { label: string; value: number; icon: LucideIcon; trend: string; caption: string; color: string; unit: string }[] = [
    { label: 'إجمالي المبيعات', value: totalSales, icon: Wallet, trend: '12.8%', caption: 'مقارنة بالشهر السابق', color: 'mint', unit: currency },
    { label: 'إجمالي المشتريات', value: 48200 + purchasesDelta, icon: ShoppingCart, trend: '8.2%', caption: 'مقارنة بالشهر السابق', color: 'blue', unit: currency },
    { label: 'صافي الأرباح', value: totalSales - (48200 + purchasesDelta), icon: ChartNoAxesCombined, trend: '18.6%', caption: 'مقارنة بالشهر السابق', color: 'violet', unit: currency },
    { label: 'إجمالي العملاء', value: 1284 + records.filter(r => r.module === 'customers').length - 4, icon: Users, trend: '6.4%', caption: '+ ٢٤ عميل جديد هذا الشهر', color: 'orange', unit: 'عميل' },
  ];
  const filtered = records.filter(r => r.module === currentModule && (status === 'all' || r.status === status) && `${r.name} ${r.reference} ${r.detail}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => b.date.localeCompare(a.date));
  const pageSize = section === 'dashboard' ? 5 : 8;
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const visible = filtered.slice((Math.min(page, pages) - 1) * pageSize, Math.min(page, pages) * pageSize);
  const searchResults = records.filter(r => `${r.name} ${r.reference} ${r.detail}`.toLowerCase().includes(globalQuery.toLowerCase())).slice(0, 9);
  const table = (dashboard = false) => <section className={`panel transactions ${dashboard ? 'dashboard-table' : ''}`}>
    <div className="panel-head"><div><h2>{dashboard ? 'أحدث المبيعات' : `قائمة ${moduleInfo[currentModule].title}`}{!dashboard && <span className="count-pill">{filtered.length}</span>}</h2>{dashboard && <p>آخر العمليات في نشاطك التجاري</p>}</div>{dashboard ? <Link className="text-link" href="/sales">عرض الكل <ArrowLeft size={14}/></Link> : <button className="button small" onClick={() => exportData(filtered)}><Download size={15}/>تصدير القائمة</button>}</div>
    {!dashboard && <div className="table-toolbar"><div className="table-search"><Search size={17}/><input aria-label="البحث في السجلات" placeholder={`ابحث في ${moduleInfo[currentModule].title}...`} value={query} onChange={e => { setQuery(e.target.value); setPage(1); }}/></div><button className={`button small ${filterOpen ? 'active-filter' : ''}`} onClick={() => setFilterOpen(!filterOpen)}><SlidersHorizontal size={15}/>تصفية{status !== 'all' && <i className="dot green"/>}</button>{filterOpen && <select className="filter-select" aria-label="تصفية حسب الحالة" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="all">كل الحالات</option>{moduleInfo[currentModule].statuses.map(s => <option key={s}>{s}</option>)}</select>}{selected.length > 0 && <button className="button small" onClick={() => exportData(records.filter(r => selected.includes(r.id)))}><Download size={14}/>تصدير المحدد ({selected.length})</button>}</div>}
    <div className="table-scroll"><table><thead><tr><th className="checkbox-cell"><input type="checkbox" aria-label="تحديد كل السجلات المعروضة" checked={visible.length > 0 && visible.every(r => selected.includes(r.id))} onChange={e => setSelected(e.target.checked ? [...new Set([...selected, ...visible.map(r => r.id)])] : selected.filter(id => !visible.some(r => r.id === id)))}/></th><th>{currentModule === 'sales' ? 'رقم الفاتورة' : 'المرجع'}</th><th>{moduleInfo[currentModule].nameLabel}</th><th>{currentModule === 'team' ? 'المهام' : 'المبلغ'}</th><th>الحالة</th><th>التاريخ</th><th/></tr></thead><tbody>{visible.map(r => <tr key={r.id}><td className="checkbox-cell"><input type="checkbox" aria-label={`تحديد ${r.name}`} checked={selected.includes(r.id)} onChange={e => setSelected(e.target.checked ? [...selected, r.id] : selected.filter(id => id !== r.id))}/></td><td><button className="reference" onClick={() => openRecord(r.module, r)}>{r.reference}</button></td><td><span className="table-name">{r.name}</span></td><td className="table-amount"><b>{number(r.amount)}</b> <small>{currentModule === 'team' ? '' : currency}</small></td><td><span className={`status status-${['مكتملة', 'نشط', 'متوفر'].includes(r.status) ? 'success' : ['قيد الانتظار', 'مخزون منخفض'].includes(r.status) ? 'pending' : 'cancelled'}`}><i/>{r.status}</span></td><td className="table-date">{new Date(r.date + 'T12:00:00').toLocaleDateString('ar-EG', { day: 'numeric', month: 'short' })}</td><td><button className="icon-button table-more" aria-label={`عرض وتعديل ${r.name}`} onClick={() => openRecord(r.module, r)}><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table>{visible.length === 0 && <div className="empty-state"><Search size={30}/><h3>لا توجد نتائج</h3><p>جرّب البحث بكلمة أخرى أو تغيير التصفية.</p><button className="text-link" onClick={() => { setQuery(''); setStatus('all'); }}>إعادة تعيين البحث</button></div>}</div>
    <div className="table-footer"><span>{dashboard ? `عرض ${Math.min(5, filtered.length)} من ${filtered.length} عمليات` : `${filtered.length} سجل · الصفحة ${Math.min(page, pages)} من ${pages}`}</span>{dashboard ? <span className="live-label"><i/>يتم تحديث البيانات تلقائيًا</span> : <div className="pagination"><button className="icon-button" disabled={page <= 1} onClick={() => setPage(page - 1)} aria-label="الصفحة السابقة"><ChevronRight size={17}/></button><b>{Math.min(page, pages)}</b><button className="icon-button" disabled={page >= pages} onClick={() => setPage(page + 1)} aria-label="الصفحة التالية"><ChevronLeft size={17}/></button></div>}</div>
  </section>;

  return <div className="app-shell">
    {mobileOpen && <div className="sidebar-scrim" onClick={() => setMobileOpen(false)}/>}
    <aside className={`sidebar ${mobileOpen ? 'sidebar-open' : ''}`}>
      <Link href="/" className="brand-link" aria-label="مدار — الرئيسية"><Brand/></Link>
      <div className="workspace-switch"><button onClick={() => setPopup(popup === 'company' ? null : 'company')}><span className="company-icon"><Building2 size={19}/></span><span><b>{preferences.company}</b><small>مساحة العمل التجريبية</small></span><ChevronDown size={14}/></button>{popup === 'company' && <div className="workspace-popover"><ShieldCheck size={19}/><p>مساحة مستقلة وآمنة<br/><small>جميع البيانات هنا للتجربة فقط.</small></p><Link href="/settings" onClick={() => setPopup(null)}>إعدادات المساحة <ArrowLeft size={14}/></Link></div>}</div>
      <div className="nav-heading">مساحة العمل</div>
      <nav aria-label="القائمة الرئيسية">{sections.slice(0, 8).map(s => { const Icon = icons[s.icon]; return <Link key={s.id} href={s.id === 'dashboard' ? '/' : `/${s.id}`} className={`nav-item ${section === s.id ? 'active' : ''}`}><Icon size={19} strokeWidth={1.7}/><span>{s.label}</span>{s.id === 'sales' && <em>{sales.length + 18}</em>}{section === s.id && <i className="nav-active-dot"/>}</Link>; })}</nav>
      <div className="nav-divider"/><div className="nav-heading">إدارة النظام</div><nav>{sections.slice(8).map(s => { const Icon = icons[s.icon]; return <Link key={s.id} href={`/${s.id}`} className={`nav-item ${section === s.id ? 'active' : ''}`}><Icon size={19} strokeWidth={1.7}/><span>{s.label}</span></Link>; })}</nav>
      <div className="sidebar-bottom"><div className="explore-card"><span className="explore-icon"><Sparkles size={19}/></span><h3>كل إمكانات مدار، بين يديك</h3><p>اكتشف كيف تجعل إدارة أعمالك<br/>أبسط وأكثر كفاءة.</p><button onClick={() => setModal('tour')}>استكشف النظام <ArrowLeft size={15}/></button><div className="explore-decoration"/></div><div className="sidebar-account"><span className="avatar">ز</span><div><b>الزائر التجريبي</b><small><i/>حساب غير إنتاجي</small></div><button className="icon-button" title="إعادة ضبط الجلسة" aria-label="إعادة ضبط الجلسة" onClick={() => setModal('reset')}><LogOut size={18}/></button></div></div>
    </aside>
    <div className="main-shell">
      <header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" onClick={() => setMobileOpen(true)} aria-label="فتح القائمة"><Menu size={22}/></button><LayoutDashboard size={17}/><span>مساحة العمل</span><ChevronLeft size={13}/><b>{activeLabel}</b></div><div className="header-actions"><button className="global-search" onClick={() => setModal('search')}><Search size={17}/><span>ابحث عن أي شيء...</span><kbd>⌘ K</kbd></button><span className="header-divider"/><div className="popup-anchor"><button className="icon-button notification-button" aria-label="الإشعارات" onClick={() => setPopup(popup === 'notifications' ? null : 'notifications')}><Bell size={20}/>{!notificationsRead && preferences.notifications && <i/>}</button>{popup === 'notifications' && <div className="header-popover notification-popover"><div><h3>الإشعارات</h3><button className="icon-button" aria-label="تحديد الكل كمقروء" onClick={() => setNotificationsRead(true)}><CheckCheck size={18}/></button></div>{notificationsRead || !preferences.notifications ? <p className="muted-text">أنت على اطّلاع بكل جديد.</p> : <><Link href="/inventory"><Package size={18}/><span>منتجات تحتاج إلى إعادة التوريد<small>راجع مستويات المخزون التجريبي</small></span></Link><Link href="/sales"><FileText size={18}/><span>فاتورة بانتظار إتمام الدفع<small>مؤسسة النور التجارية · ٢٬٨٠٠ ر.س</small></span></Link></>}</div>}</div><div className="popup-anchor"><button className="profile-button" onClick={() => setPopup(popup === 'profile' ? null : 'profile')}><span className="avatar small-avatar">ز</span><ChevronDown size={13}/></button>{popup === 'profile' && <div className="header-popover profile-popover"><b>مرحبًا، أيها الزائر 👋</b><p>حساب تجريبي بدون بيانات دخول</p><Link href="/settings"><Settings size={16}/>إعدادات مساحة العمل</Link><button onClick={() => { setPopup(null); setModal('reset'); }}><RotateCcw size={16}/>بدء تجربة جديدة</button></div>}</div></div></header>
      <main className="main-content">
        <div className="page-heading"><div><div className="title-line"><h1>{section === 'dashboard' ? 'نظرة عامة' : activeLabel}</h1>{section === 'dashboard' && <span className="overview-tag">لوحة التحكم</span>}</div><p>{section === 'dashboard' ? 'مرحبًا بك مجددًا، إليك ما يحدث في أعمالك اليوم' : isModule ? moduleInfo[currentModule].description : section === 'reports' ? 'حوّل بياناتك إلى قرارات أفضل، وتابع نمو أعمالك.' : section === 'settings' ? 'خصّص مساحة العمل لتناسب احتياجاتك.' : 'نحن هنا لمساعدتك على الاستفادة من كل إمكانات مدار.'}{section === 'dashboard' && <span className="wave"> 👋</span>}</p></div><div className="heading-actions">{(section === 'dashboard' || section === 'reports') && <div className="popup-anchor"><button className="button date-button" onClick={() => setPopup(popup === 'date' ? null : 'date')}><CalendarDays size={16}/><span>{period === 'month' ? '١ – ٣٠ يونيو، ٢٠٢٤' : period === 'week' ? '٢٢ – ٢٨ يونيو، ٢٠٢٤' : 'يناير – ديسمبر، ٢٠٢٤'}</span><ChevronDown size={13}/></button>{popup === 'date' && <div className="header-popover date-popover"><p>الفترة المعروضة · بيانات توضيحية</p>{([['month', 'هذا الشهر · يونيو ٢٠٢٤'], ['week', 'هذا الأسبوع · ٢٢–٢٨ يونيو'], ['year', 'هذا العام · ٢٠٢٤']] as [Period, string][]).map(([v, label]) => <button key={v} onClick={() => { setPeriod(v); setPopup(null); }}>{label}{period === v && <Check size={15}/>}</button>)}</div>}</div>}{section !== 'settings' && section !== 'help' && <button className="button primary" disabled={loading || !!loadError} onClick={() => section === 'reports' ? exportData(records) : openRecord(currentModule)}>{section === 'reports' ? <Download size={17}/> : <Plus size={18}/>}<span>{section === 'reports' ? 'تصدير التقرير' : `إضافة ${moduleInfo[currentModule].singular}`}</span></button>}</div></div>
        <section className="demo-banner"><div className="demo-banner-icon"><FlaskConical size={24} strokeWidth={1.6}/></div><div className="demo-banner-copy"><h3>أنت الآن في المساحة التجريبية <span>وصول كامل</span></h3><p>جرّب جميع المزايا بحرية، بدون تسجيل دخول. بيانات تجريبية آمنة ومنفصلة تمامًا عن بيئة الإنتاج.</p></div><button onClick={() => setModal('reset')} disabled={loading || !!loadError}><RotateCcw size={15}/><span>إعادة ضبط التجربة</span></button><ShieldCheck className="banner-shield" size={67} strokeWidth={.8}/></section>
        {loadError && <div className="error-banner" role="alert">{loadError}<button onClick={() => { setLoading(true); void load(); }}>إعادة المحاولة</button></div>}
        {(section === 'dashboard' || section === 'reports') && <>
          <div className="section-label"><h2>أعمالك بالأرقام</h2><span><i className="dot green"/>ملخص يونيو ٢٠٢٤</span></div>
          <div className="kpi-grid">{kpis.map((k, index) => <div className="panel kpi-card" key={k.label}><div className="kpi-top"><span>{k.label}</span><span className={`kpi-icon ${k.color}`}><k.icon size={21} strokeWidth={1.6}/></span></div><div className="kpi-value"><strong>{number(k.value)}</strong><span>{k.unit}</span><svg className={`sparkline sparkline-${index}`} viewBox="0 0 74 30" aria-hidden="true"><path d={index === 1 ? 'M1 23L10 17L18 21L28 14L37 17L47 7L58 12L73 3' : index === 3 ? 'M1 26L11 23L20 24L29 15L39 18L49 10L59 13L73 3' : 'M1 27L12 23L20 26L30 15L40 19L50 10L60 13L73 3'} fill="none" stroke="currentColor" strokeWidth="1.7"/><path d="M1 27L12 23L20 26L30 15L40 19L50 10L60 13L73 3L73 30L1 30Z" fill="currentColor" opacity=".055"/></svg></div><div className="kpi-bottom"><span className="trend"><ArrowUpRight size={13}/><b dir="ltr">{k.trend}</b></span><span>{k.caption}</span></div></div>)}</div>
          <div className="analytics-grid"><RevenueChart period={period} setPeriod={setPeriod}/><GoalCard total={totalSales}/></div>
        </>}
        {section === 'dashboard' && <div className="bottom-grid">{table(true)}<section className="panel activity-panel"><div className="panel-head"><h2>آخر النشاطات</h2><span className="today-label">اليوم</span></div><div className="activity-list">{[{ icon: FileText, color: 'mint', title: 'تم إنشاء فاتورة جديدة', detail: `${sales[sales.length - 1]?.reference || '—'} · ${sales[sales.length - 1]?.name || 'لا توجد مبيعات'}`, time: 'منذ ٥ دقائق', link: '/sales' }, { icon: Users, color: 'blue', title: 'تمت إضافة عميل جديد', detail: records.filter(r => r.module === 'customers').at(-1)?.name || 'لا يوجد عملاء', time: 'منذ ٢٠ دقيقة', link: '/customers' }, { icon: Package, color: 'orange', title: 'تنبيه انخفاض المخزون', detail: 'لوحة مفاتيح لاسلكية · ٣ قطع متبقية', time: 'منذ ٤٥ دقيقة', link: '/inventory' }, { icon: CheckCircle2, color: 'violet', title: 'تم استلام طلب شراء', detail: 'شركة التقنية المتقدمة · PO-2024-001', time: 'منذ ساعة', link: '/purchases' }].map((a, i) => <Link className="activity-item" href={a.link} key={i}><span className={`activity-icon ${a.color}`}><a.icon size={16}/></span><div><h4>{a.title}</h4><p>{a.detail}</p><small>{a.time}</small></div><i className="activity-new"/></Link>)}</div><Link className="activity-all" href="/reports">عرض التقارير والتحليلات <ArrowLeft size={14}/></Link></section></div>}
        {isModule && <><div className="module-summary"><div><span>إجمالي السجلات</span><strong>{records.filter(r => r.module === currentModule).length}</strong></div><div><span>{currentModule === 'team' ? 'إجمالي المهام' : 'إجمالي القيمة'}</span><strong>{number(records.filter(r => r.module === currentModule).reduce((a, r) => a + r.amount, 0))}<small>{currentModule === 'team' ? ' مهمة' : ` ${currency}`}</small></strong></div><div><span>{moduleInfo[currentModule].statuses[0]}</span><strong>{records.filter(r => r.module === currentModule && r.status === moduleInfo[currentModule].statuses[0]).length}</strong></div><span className="module-summary-icon">{(() => { const Icon = icons[sections.find(s => s.id === section)!.icon]; return <Icon size={40} strokeWidth={1}/>; })()}</span></div>{table()}</>}
        {section === 'reports' && <section className="panel reports-panel"><div className="panel-head"><div><h2>تقارير مساحة العمل</h2><p>صدّر السجلات الحالية لكل وحدة بصيغة CSV</p></div><span className="overview-tag">بيانات تجريبية</span></div><div className="report-grid">{(Object.keys(moduleInfo) as Module[]).map(m => <button key={m} className="report-card" onClick={() => exportData(records.filter(r => r.module === m))}><span className="report-icon"><FileText size={24}/></span><div><h3>تقرير {moduleInfo[m].title}</h3><p>{records.filter(r => r.module === m).length} سجلات · CSV</p></div><Download size={19}/></button>)}</div><p className="report-disclaimer"><CircleHelp size={15}/>المؤشرات والرسم البياني تتضمن أرصدة تاريخية توضيحية. ملفات التصدير تحتوي على السجلات التفصيلية المتاحة فقط.</p></section>}
        {section === 'settings' && <div className="settings-grid"><section className="panel"><div className="panel-head"><div><h2>معلومات مساحة العمل</h2><p>هذه الإعدادات محفوظة لجلسة العرض الخاصة بك فقط</p></div><Building2 size={22}/></div><form className="settings-form" onSubmit={async e => { e.preventDefault(); await mutate({ action: 'settings', preferences }, 'تم حفظ إعدادات مساحة العمل'); }}><label>اسم المنشأة<input value={preferences.company} maxLength={100} required onChange={e => setPreferences({ ...preferences, company: e.target.value })}/></label><label>البريد الإلكتروني<input dir="ltr" type="email" value={preferences.email} maxLength={150} required onChange={e => setPreferences({ ...preferences, email: e.target.value })}/></label><label>عملة عرض السجلات<select value={preferences.currency} onChange={e => setPreferences({ ...preferences, currency: e.target.value })}><option value="SAR">ريال سعودي (SAR)</option><option value="AED">درهم إماراتي (AED)</option><option value="USD">دولار أمريكي (USD)</option></select><small>تغيير رمز العرض فقط، دون تحويل أسعار الصرف.</small></label><div className="setting-toggle"><div><b>إشعارات مساحة العمل</b><p>عرض تنبيهات المبيعات والمخزون التجريبية</p></div><button type="button" className={`toggle ${preferences.notifications ? 'on' : ''}`} role="switch" aria-checked={preferences.notifications} aria-label="تفعيل الإشعارات" onClick={() => setPreferences({ ...preferences, notifications: !preferences.notifications })}><i/></button></div><button className="button primary" type="submit" disabled={busy || loading || !!loadError}>{busy ? <LoaderCircle className="spin" size={17}/> : <Check size={17}/>}حفظ التغييرات</button></form></section><section className="panel session-card"><span className="session-shield"><ShieldCheck size={35}/></span><h2>بيئة آمنة للتجربة</h2><p>لديك وصول كامل إلى جميع الوحدات، بدون كلمة مرور أو بيانات دخول.</p><ul><li><Check size={16}/>جلسة مستقلة مدتها ٢٤ ساعة</li><li><Check size={16}/>لا تؤثر على بيانات أي زائر آخر</li><li><Check size={16}/>لا يتم تنفيذ مدفوعات أو إرسال رسائل</li><li><Check size={16}/>يمكنك إعادة ضبطها في أي وقت</li></ul><button className="button" onClick={() => setModal('reset')}><RotateCcw size={16}/>إعادة ضبط البيانات التجريبية</button></section></div>}
        {section === 'help' && <div className="help-layout"><section className="help-hero"><span className="help-icon"><CircleHelp size={36}/></span><h2>كيف يمكننا مساعدتك؟</h2><p>كل ما تحتاجه للبدء واستكشاف مساحة عملك الجديدة.</p><button className="button primary" onClick={() => setModal('tour')}><Play size={17}/>ابدأ الجولة التعريفية</button></section><section className="panel faq-panel"><div className="panel-head"><h2>الأسئلة الشائعة</h2></div>{[{ q: 'كيف تعمل المساحة التجريبية؟', a: 'عند زيارتك، ننشئ جلسة مستقلة لمدة ٢٤ ساعة مع بيانات توضيحية. يمكنك إضافة وتعديل وحذف السجلات دون تسجيل دخول. نحفظ معرّف الجلسة في ملف تعريف ارتباط آمن من وصول JavaScript.' }, { q: 'هل تؤثر التغييرات على بيانات حقيقية؟', a: 'لا. كل البيانات في جداول تجريبية خاصة بالجلسة. لا توجد مدفوعات حقيقية أو رسائل تُرسل للعملاء. أسماء الشركات والبريد الإلكتروني هي أمثلة فقط.' }, { q: 'كيف أضيف فاتورة أو منتجًا جديدًا؟', a: 'اختر الوحدة من القائمة الجانبية ثم اضغط زر الإضافة. أدخل البيانات المطلوبة واضغط حفظ. لتعديل سجل أو حذفه، اضغط مرجعه أو زر النقاط في صفه.' }, { q: 'هل يمكنني تصدير بياناتي؟', a: 'نعم. استخدم تصدير القائمة من أي وحدة، أو اختر تقريرًا من صفحة التقارير والتحليلات. يمكنك أيضًا تحديد صفوف معينة وتصديرها بصيغة CSV قابلة للفتح في Excel.' }, { q: 'كيف أبدأ التجربة من جديد؟', a: 'اضغط إعادة ضبط التجربة في الشريط الأخضر. بعد التأكيد، تُحذف التعديلات الخاصة بك وتُستعاد البيانات والإعدادات الافتراضية، دون التأثير على أي جلسة أخرى.' }].map((item, i) => <div className="faq" key={i}><button aria-expanded={faq === i} onClick={() => setFaq(faq === i ? null : i)}>{item.q}<ChevronDown size={18} className={faq === i ? 'rotated' : ''}/></button>{faq === i && <p>{item.a}</p>}</div>)}</section></div>}
        <footer className="page-footer"><span>© ٢٠٢٤ مدار. كل أعمالك في مدار واحد.</span><span><ShieldCheck size={13}/>بيئة تجريبية آمنة <i/>الإصدار 1.0</span></footer>
      </main>
    </div>
    {toast && <div className="toast" role="status"><CheckCircle2 size={20}/><span>{toast}</span><button onClick={() => setToast('')} aria-label="إغلاق التنبيه"><X size={15}/></button></div>}
    {modal === 'record' && <Modal title={editRecord ? `تفاصيل ${moduleInfo[formModule].singular}` : `إضافة ${moduleInfo[formModule].singular} جديدة`} close={closeModal}><div className="modal-demo-note"><FlaskConical size={15}/>سيُحفظ هذا السجل في مساحتك التجريبية فقط</div><form className="record-form" onSubmit={saveRecord}>{editRecord && <div className="record-reference"><FileText size={17}/><span dir="ltr">{editRecord.reference}</span><span className="overview-tag">سجل تجريبي</span></div>}<label>{moduleInfo[formModule].nameLabel}<input name="name" defaultValue={editRecord?.name} required maxLength={150} placeholder={`أدخل ${moduleInfo[formModule].nameLabel}`}/></label><div className="form-row"><label>{moduleInfo[formModule].amountLabel}{formModule !== 'team' && ` (${currency})`}<input name="amount" type="number" min="0" max="1000000000" step={formModule === 'team' ? '1' : '0.01'} defaultValue={editRecord?.amount} required placeholder="0.00"/></label><label>الحالة<select name="status" defaultValue={editRecord?.status || moduleInfo[formModule].statuses[0]}>{moduleInfo[formModule].statuses.map(s => <option key={s}>{s}</option>)}</select></label></div><label>التاريخ<input name="date" type="date" defaultValue={editRecord?.date || new Date().toISOString().slice(0, 10)} required/></label><label>{moduleInfo[formModule].detailLabel}<input name="detail" defaultValue={editRecord?.detail} maxLength={500} placeholder={moduleInfo[formModule].detailLabel}/></label>{formError && <p className="form-error" role="alert">{formError}</p>}<div className="form-actions"><button className="button primary" disabled={busy} type="submit">{busy ? <LoaderCircle className="spin" size={17}/> : <Check size={17}/>}حفظ {editRecord ? 'التغييرات' : 'السجل'}</button><button className="button" type="button" onClick={closeModal}>إلغاء</button>{editRecord && <button className="button danger delete-button" type="button" disabled={busy} onClick={async () => { if (window.confirm(`هل تريد حذف ${editRecord.name} من المساحة التجريبية؟`)) { if (await mutate({ action: 'delete', id: editRecord.id }, 'تم حذف السجل التجريبي')) closeModal(); } }}><Trash2 size={16}/>حذف</button>}</div></form></Modal>}
    {modal === 'reset' && <Modal title="بدء تجربة جديدة" close={closeModal}><div className="reset-content"><span className="reset-icon"><RotateCcw size={30}/></span><h3>هل تريد إعادة ضبط مساحتك؟</h3><p>ستُحذف جميع الإضافات والتعديلات التجريبية في جلستك، وتُستعاد البيانات والإعدادات الأصلية. لا يمكن التراجع عن هذا الإجراء.</p><div className="safe-note"><ShieldCheck size={18}/>لن تتأثر بيانات أي زائر آخر</div><div className="form-actions"><button className="button primary" disabled={busy || loading || !!loadError} onClick={async () => { if (await mutate({ action: 'reset' }, 'مساحتك جاهزة! تمت استعادة البيانات التجريبية')) { setSelected([]); closeModal(); } }}>{busy ? <LoaderCircle className="spin" size={17}/> : <RotateCcw size={17}/>}نعم، إعادة ضبط التجربة</button><button className="button" onClick={closeModal}>الاحتفاظ بتغييراتي</button></div></div></Modal>}
    {modal === 'tour' && <Modal title="أهلًا بك في مدار" close={closeModal} wide><div className="tour-intro"><span className="session-shield"><Sparkles size={30}/></span><h3>كل أعمالك. مساحة واحدة. إمكانات أكثر.</h3><p>اختر ما تريد استكشافه، وجرّب بنفسك. لا تحتاج إلى إنشاء حساب.</p></div><div className="tour-grid">{sections.slice(1, 8).map(s => { const Icon = icons[s.icon]; return <Link href={`/${s.id}`} key={s.id} onClick={closeModal}><Icon size={23}/><div><h3>{s.label}</h3><p>{s.id === 'reports' ? 'تابع الأداء وصدّر التقارير' : moduleInfo[s.id as Module].description}</p></div><ArrowLeft size={16}/></Link>; })}</div><div className="tour-footer"><ShieldCheck size={17}/>جميع المزايا متاحة · بيانات معزولة · بدون تسجيل دخول</div></Modal>}
    {modal === 'search' && <Modal title="البحث في مساحة العمل" close={closeModal} wide><div className="command-search"><Search size={22}/><input autoFocus value={globalQuery} onChange={e => setGlobalQuery(e.target.value)} placeholder="ابحث عن عميل، فاتورة، منتج أو وحدة..." aria-label="البحث الشامل"/><kbd>ESC</kbd></div><div className="search-results"><p className="search-section-label">الوحدات</p><div className="search-modules">{sections.filter(s => s.label.includes(globalQuery)).map(s => <Link key={s.id} href={s.id === 'dashboard' ? '/' : `/${s.id}`} onClick={closeModal}>{s.label}<ArrowUpLeft size={13}/></Link>)}</div><p className="search-section-label">السجلات {globalQuery ? 'المطابقة' : 'الأخيرة'}</p>{searchResults.map(r => <button key={r.id} className="search-result" onClick={() => openRecord(r.module, r)}><span className="search-result-icon"><FileText size={18}/></span><div><b>{r.name}</b><small>{moduleInfo[r.module].title} · {r.reference}</small></div><ArrowLeft size={16}/></button>)}{searchResults.length === 0 && <div className="empty-state"><Search size={27}/><p>لم نجد سجلات تطابق بحثك</p></div>}</div></Modal>}
  </div>;
}
