import { useMemo, useState } from "react";
import { Archive, BookOpenCheck, CheckCircle2, ClipboardEdit, FilePlus2, Loader2, RotateCcw, Send, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useLocalization } from "@/contexts/LocalizationContext";
import { trpc } from "@/lib/trpc";

type Props = { organizationId: number | null; branchId: number | null; jurisdictionId?: number | null; canManage?: boolean };
type Status = "draft" | "pending_review" | "approved" | "archived";
type Article = { id: number; title: string; category: string; content: string; sourceReference?: string | null; branchId?: number | null; jurisdictionId?: number | null; status: Status; version: number; updatedAt?: Date | string | null };

const statusClasses: Record<Status, string> = { draft: "border-slate-200 bg-slate-50 text-slate-700", pending_review: "border-amber-200 bg-amber-50 text-amber-800", approved: "border-emerald-200 bg-emerald-50 text-emerald-800", archived: "border-zinc-200 bg-zinc-50 text-zinc-600" };
const emptyForm = { title: "", category: "", content: "", sourceReference: "" };

export function PolicyKnowledgeWorkspace({ organizationId, branchId, jurisdictionId = null, canManage = false }: Props) {
  const { language, direction } = useLocalization();
  const isArabic = language === "ar";
  const text = isArabic ? {
    draft: "مسودة", pendingReview: "بانتظار المراجعة", approved: "معتمد", archived: "مؤرشف", savedDraft: "تم حفظ المقال كمسودة.", updatedDraft: "تم تحديث المسودة.", sentReview: "أُرسلت المقالة إلى المراجعة البشرية.", policyApproved: "تم اعتماد السياسة وأصبحت متاحة للمساعد.", policyArchived: "تمت أرشفة السياسة.", title: "قاعدة معرفة سياسات النظام", description: "المحتوى المعتمد فقط يدخل سياق المساعد. كل تعديل يبدأ كمسودة ويمر بمراجعة بشرية قبل النشر.", search: "ابحث في العنوان أو المحتوى…", searchAria: "البحث في السياسات", all: "الكل", scope: "النطاق الحالي", organization: "مؤسسة", branch: "فرع", jurisdiction: "الاختصاص", notSpecified: "غير محددة", general: "عام", governance: "حوكمة المحتوى", managerRule: "المسؤولون ينشئون ويعدلون ويرسلون للمراجعة ويعتمدون أو يؤرشفون.", readerRule: "المستخدمون يقرأون السياسات المعتمدة الواقعة داخل نطاق مؤسستهم وفرعهم فقط.", draftRule: "لا يتم استخدام المسودات أو المحتوى المؤرشف في إجابات المساعد.", editDraft: "تعديل مسودة سياسة", addPolicy: "إضافة سياسة جديدة", policyTitle: "عنوان السياسة", category: "التصنيف، مثل: المشتريات أو الخصوصية", policyText: "النص الرسمي للسياسة والإجراء المعتمد…", source: "مرجع السياسة أو رقم الإصدار (اختياري)", saveEdit: "حفظ التعديل", saveDraft: "حفظ كمسودة", cancelEdit: "إلغاء التعديل", selectOrganization: "اختر مؤسسة صالحة قبل إدارة قاعدة المعرفة.", loading: "جارٍ تحميل السياسات…", empty: "لا توجد مقالات ضمن الفلتر والنطاق الحالي.", version: "الإصدار", branchScope: "نطاق الفرع", edit: "تعديل", sendReview: "إرسال للمراجعة", approve: "اعتماد", archive: "أرشفة", reference: "المرجع", reviewNote: "تمت المراجعة من مساحة السياسات.",
  } : {
    draft: "Draft", pendingReview: "Pending review", approved: "Approved", archived: "Archived", savedDraft: "The article was saved as a draft.", updatedDraft: "The draft was updated.", sentReview: "The article was sent for human review.", policyApproved: "The policy was approved and is now available to the assistant.", policyArchived: "The policy was archived.", title: "System policy knowledge base", description: "Only approved content enters the assistant context. Every change begins as a draft and passes human review before publication.", search: "Search title or content…", searchAria: "Search policies", all: "All", scope: "Current scope", organization: "Organization", branch: "Branch", jurisdiction: "Jurisdiction", notSpecified: "Not selected", general: "General", governance: "Content governance", managerRule: "Authorized managers create, edit, submit for review, approve, or archive content.", readerRule: "Users can read only approved policies within their organization and branch scope.", draftRule: "Draft and archived content is never used in assistant responses.", editDraft: "Edit policy draft", addPolicy: "Add new policy", policyTitle: "Policy title", category: "Category, such as procurement or privacy", policyText: "Official policy text and approved procedure…", source: "Policy reference or version number (optional)", saveEdit: "Save changes", saveDraft: "Save as draft", cancelEdit: "Cancel edit", selectOrganization: "Select a valid organization before managing the knowledge base.", loading: "Loading policies…", empty: "There are no articles within the current filter and scope.", version: "Version", branchScope: "Branch scope", edit: "Edit", sendReview: "Send for review", approve: "Approve", archive: "Archive", reference: "Reference", reviewNote: "Reviewed from the policy workspace.",
  };
  const statusLabels: Record<Status, string> = { draft: text.draft, pending_review: text.pendingReview, approved: text.approved, archived: text.archived };
  const isScoped = Boolean(organizationId);
  const scope = organizationId ? { organizationId, branchId, includeDrafts: canManage } : undefined;
  const [form, setForm] = useState(emptyForm);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [filter, setFilter] = useState<"all" | Status>("all");
  const [search, setSearch] = useState("");
  const [notice, setNotice] = useState("");
  const list = trpc.policyKnowledge.list.useQuery(scope!, { enabled: Boolean(scope) });
  const utils = trpc.useUtils();
  const create = trpc.policyKnowledge.create.useMutation({ onSuccess: () => { setNotice(text.savedDraft); resetForm(); void utils.policyKnowledge.list.invalidate(); } });
  const update = trpc.policyKnowledge.update.useMutation({ onSuccess: () => { setNotice(text.updatedDraft); resetForm(); void utils.policyKnowledge.list.invalidate(); } });
  const submit = trpc.policyKnowledge.submitForReview.useMutation({ onSuccess: () => { setNotice(text.sentReview); void utils.policyKnowledge.list.invalidate(); } });
  const approve = trpc.policyKnowledge.approve.useMutation({ onSuccess: () => { setNotice(text.policyApproved); void utils.policyKnowledge.list.invalidate(); } });
  const archive = trpc.policyKnowledge.archive.useMutation({ onSuccess: () => { setNotice(text.policyArchived); void utils.policyKnowledge.list.invalidate(); } });
  const articles = useMemo(() => ((list.data ?? []) as Article[]).filter(article => { const matchesStatus = filter === "all" || article.status === filter; const haystack = `${article.title} ${article.category} ${article.content}`.toLowerCase(); return matchesStatus && haystack.includes(search.trim().toLowerCase()); }), [list.data, filter, search]);
  function resetForm() { setForm(emptyForm); setEditingId(null); }
  function edit(article: Article) { setEditingId(article.id); setForm({ title: article.title, category: article.category, content: article.content, sourceReference: article.sourceReference ?? "" }); window.setTimeout(() => document.getElementById("policy-editor")?.scrollIntoView({ behavior: "smooth", block: "center" }), 0); }
  function save() { if (!canManage || !organizationId) return; const input = { organizationId, branchId, jurisdictionId, ...form }; if (editingId) update.mutate({ ...input, articleId: editingId }); else create.mutate(input); }
  const busy = create.isPending || update.isPending || submit.isPending || approve.isPending || archive.isPending;
  const canSave = Boolean(organizationId && form.title.trim().length >= 4 && form.category.trim().length >= 2 && form.content.trim().length >= 20);

  return <div dir={direction} className="space-y-4"><div className="grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><Card className="border-cyan-200 bg-gradient-to-br from-cyan-50/80 to-white"><CardHeader className="flex flex-row items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-cyan-950"><BookOpenCheck className="h-5 w-5" />{text.title}</CardTitle><p className="mt-2 text-sm leading-6 text-cyan-900/70">{text.description}</p></div><ShieldCheck className="h-8 w-8 text-cyan-600" /></CardHeader><CardContent className="space-y-3"><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><Input value={search} onChange={event => setSearch(event.target.value)} placeholder={text.search} aria-label={text.searchAria} /><div className="flex flex-wrap gap-2">{(["all", "draft", "pending_review", "approved", "archived"] as const).map(value => <Button key={value} type="button" size="sm" variant={filter === value ? "default" : "outline"} onClick={() => setFilter(value)}>{value === "all" ? text.all : statusLabels[value]}</Button>)}</div></div><p className="text-xs text-muted-foreground">{text.scope}: {text.organization} {organizationId ?? text.notSpecified} · {text.branch} {branchId ?? text.general} · {text.jurisdiction} {jurisdictionId ?? text.general}</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ClipboardEdit className="h-5 w-5 text-amber-600" />{text.governance}</CardTitle></CardHeader><CardContent className="space-y-2 text-sm leading-6 text-muted-foreground"><p>{text.managerRule}</p><p>{text.readerRule}</p><p className="font-medium text-emerald-700">{text.draftRule}</p></CardContent></Card></div>
    {canManage && <Card id="policy-editor" className="border-slate-200"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><FilePlus2 className="h-5 w-5 text-cyan-700" />{editingId ? text.editDraft : text.addPolicy}</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-3 md:grid-cols-2"><Input value={form.title} onChange={event => setForm(current => ({ ...current, title: event.target.value }))} placeholder={text.policyTitle} aria-label={text.policyTitle} /><Input value={form.category} onChange={event => setForm(current => ({ ...current, category: event.target.value }))} placeholder={text.category} aria-label={text.category} /></div><Textarea value={form.content} onChange={event => setForm(current => ({ ...current, content: event.target.value }))} placeholder={text.policyText} aria-label={text.policyText} className="min-h-36" /><Input value={form.sourceReference} onChange={event => setForm(current => ({ ...current, sourceReference: event.target.value }))} placeholder={text.source} aria-label={text.source} /><div className="flex flex-wrap gap-2"><Button type="button" disabled={!canSave || busy} onClick={save}>{busy ? <Loader2 className="me-2 h-4 w-4 animate-spin" /> : <FilePlus2 className="me-2 h-4 w-4" />}{editingId ? text.saveEdit : text.saveDraft}</Button>{editingId && <Button type="button" variant="outline" onClick={resetForm}><RotateCcw className="me-2 h-4 w-4" />{text.cancelEdit}</Button>}</div>{notice && <p role="status" className="text-sm text-emerald-700">{notice}</p>}{!isScoped && <p className="text-sm text-amber-700">{text.selectOrganization}</p>}</CardContent></Card>}
    <div className="space-y-3">{list.isLoading ? <Card><CardContent className="flex min-h-32 items-center justify-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />{text.loading}</CardContent></Card> : articles.length === 0 ? <Card><CardContent className="p-8 text-center text-sm text-muted-foreground">{text.empty}</CardContent></Card> : articles.map(article => <Card key={article.id} className="overflow-hidden"><CardContent className="space-y-3 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-900">{article.title}</h3><Badge className={statusClasses[article.status]}>{statusLabels[article.status]}</Badge><Badge variant="outline">{text.version} {article.version}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{article.category} · {text.branchScope} {article.branchId ?? text.general}</p></div><div className="flex flex-wrap gap-2">{canManage && article.status === "draft" && <><Button type="button" size="sm" variant="outline" onClick={() => edit(article)}><ClipboardEdit className="me-1 h-4 w-4" />{text.edit}</Button><Button type="button" size="sm" disabled={busy} onClick={() => organizationId && submit.mutate({ organizationId, branchId, jurisdictionId, articleId: article.id })}><Send className="me-1 h-4 w-4" />{text.sendReview}</Button></>}{canManage && article.status === "pending_review" && <Button type="button" size="sm" disabled={busy} onClick={() => organizationId && approve.mutate({ organizationId, branchId, jurisdictionId, articleId: article.id, reviewNote: text.reviewNote })}><CheckCircle2 className="me-1 h-4 w-4" />{text.approve}</Button>}{canManage && article.status === "approved" && <Button type="button" size="sm" variant="outline" disabled={busy} onClick={() => organizationId && archive.mutate({ organizationId, branchId, jurisdictionId, articleId: article.id })}><Archive className="me-1 h-4 w-4" />{text.archive}</Button>}</div></div><p className="whitespace-pre-wrap text-sm leading-7 text-slate-700">{article.content}</p>{article.sourceReference && <p className="border-t pt-2 text-xs text-muted-foreground">{text.reference}: {article.sourceReference}</p>}</CardContent></Card>)}</div>
  </div>;
}
